- pkg/build/package.go
Note that `d` can be nil if there's an error
> fix: check for errors when computing the installed size

- internal/sign/rsa.go
(ioutil was deprecated since go 1.16)
Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>
> Remove deprecated ioutil calls

- .github/workflows/e2e.yaml
- go.mod
- pkg/build/build.go
- pkg/build/package.go
- pkg/cli/build.go
This PR adds support for building packages for all architectures in parallel.  Some work needs to be done to skip architectures where the package is not declared supported, but that's out of scope for this PR.
Like with `docker buildx`, qemu-binfmt will need to be configured to make use of multiarch.
> multiarch support

- pkg/build/build.go
- pkg/build/package.go
Implements basic dependency tracing, compatible with `abuild` and `cbuild` (Chimera's build system), only `so:` and `cmd:` namespaces are presently implemented.  We can add additional namespaces in later PRs.
> basic dependency tracing

- examples/sshfs.yaml
- pipelines/autoconf/make-install.yaml
- pipelines/autoconf/make.yaml
- pipelines/fetch.yaml
- pipelines/git-checkout.yaml
- pipelines/meson/compile.yaml
- pipelines/meson/configure.yaml
- pipelines/meson/install.yaml
- pipelines/patch.yaml
- pipelines/strip.yaml
- pkg/build/build.go
- pkg/build/pipeline.go
This implements a new section for a pipeline:
```yaml
needs:
packages:
- foo
- bar
```
These package needs are deduplicated and merged with the configured build environment, which, when combined with apko inheritance, will allow for the YAML files to focus on the explicit dependencies needed by a package.
> Implement 'package needs' for pipelines

- .github/workflows/add-issues.yaml
A Github action that will automatically add all new issues from melange to the Images Tent Pole Github project board.
https://github.com/orgs/chainguard-dev/projects/12/
> Creating Github action to automatically add issues to project board.

- pkg/build/build.go
- pkg/cli/build.go
this is needed to allow compatibility between github actions and other
github action runners like act, which place the github workspace in
slightly different locations
> build: add support for --keyring-append and --repository-append like apko

- pkg/build/build.go
Previously, it would keep checking for possible config filenames if multiple ones existed.
> build: stop looking for default config filenames when one is found

- .ko.yaml
Just to make it easier to build the image on systems without LDFLAGS env, remove the last line form .ko.yaml.
> Try removing LDFLAGS from ko build

- pkg/build/build.go
- pkg/cli/build.go
In the very early days of melange, we defaulted to use the current
directory as the workspace directory.  This had a lot of problems,
and evolved to ./workspace instead.
When copying from the source directory to the workspace was
implemented, this resulted in workspaces being copied over.
Using a temporary directory also ensures that the build begins
from a clean state every time.
Fixes #66.
Fixes #73.
> build: use a temporary directory for workspace by default

- .gitignore
- README.md
This replaces #23 and #76
If we were to add make and go into the melange image, then this could be even simpler
> Add note to README on how to get a dev env

- go.mod
- go.sum
- pkg/build/build.go
- pkg/build/build_test.go
- pkg/cli/build.go
I'm thinking this will make it easier to build and release multiple versions of the same package  (e.g. nginx:1.20.3, nginx:1.20). 
My plan is that in CI, we can use the Github actions [matrix strategy](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#using-a-matrix-strategy) to run the melange/apko jobs for different versions of the same package. The specific version can passed in via the flag, and will be applied to `melange.yaml` in code: 
So, melange.yaml could look like this:
```
package:
name: nginx
version: {{ .Version }}
```
and we'd pass in 
```
melange build --template '{"Version": "1.20.3"}'
```
Signed-off-by: Priya Wadhwa <priya@chainguard.dev>
> Add --template flag to melange build

- pkg/build/build.go
- pkg/build/build_test.go
- pkg/build/pipeline.go
the pipeline provides some vars which we replace in code:
```
"${{package.name}}"
"${{package.version}}"
"${{package.epoch}}"
"${{targets.destdir}}"
```
Any config file with these is panicking out w/ template bc it doesn't know how to parse them. Unfortunately go templates don't allow ignoring certain values (TIL a proposal was denied https://github.com/golang/go/issues/31147) 
There are a couple options:
1. change the delimiter from `{{ }}` to `[[ ]]` so go templates can differentiate.
2. do an ugly string substitution before applying the go template and then reset it
I started with (1) but figured that would be really inconvenient for users so switched to (2)
Signed-off-by: Priya Wadhwa <priya@chainguard.dev>
> Fix bug in template, clashing with pipeline substitutions

- pkg/build/build.go
- pkg/build/package.go
- pkg/cli/build.go
This adds a new option `--dependency-log` to `melange build`, which dumps a dependency graph sorted by SONAME (e.g. `libc.so.6: [...]`).  It is intended to be used for debugging why an unexpected SONAME dependency is detected during a build.
> dependency logging feature

- pkg/build/build.go
- pkg/cli/build.go
This can be used to speed up QEMU builds by overlaying a native `/bin/sh`.  As the overlay is strictly for /bin/sh, it has no noticeable effects on the build environment itself.
The overlay `/bin/sh` must be staticly linked, as it is running inside the build environment.
For example, it is possible to do: `melange build --overlay-binsh /bin/busybox.static` on Alpine to speed up QEMU builds.
> add support for overlaid /bin/sh

- .gitignore
- examples/minimal.yaml
- internal/index/index.go
- internal/sign/sign.go
- pkg/build/build.go
- pkg/cli/build.go
- pkg/cli/index.go
- pkg/cli/sign.go
Add new flag --generate-index (defaulting to true) which will generate the index after build.
In addition, if --signing-key is provided, proceed to sign the index after it is generated.
Also moved index and signing code into internal/sign/in order to prevent circular dependency.
Lastly, added examples/minimal.yaml to have a melange build to quickly test these things with.
> Automatically index and sign on build

- pipelines/fetch.yaml
- pkg/build/pipeline.go
- pkg/build/pipeline_test.go
This came up while trying to build ICU, which only provides sha512s of its source, e.g., https://github.com/unicode-org/icu/releases/tag/release-71-1
Replaces #120
cc @imjasonh
> fetch: support expected-sha512

- pipelines/autoconf/configure.yaml
- pipelines/autoconf/make-install.yaml
- pipelines/autoconf/make.yaml
On using the fetch pipeline, some tarballs contain nested locations for `configure` or `Makefile`. This allows using the autoconf pipelines in a different directory.
> Add dir input for autoconf pipelines

- .github/workflows/e2e.yaml
- README.md
- examples/mbedtls.yaml
- pipelines/fetch.yaml
- pkg/build/build.go
- pkg/cli/build.go
This adds a `--cache-dir` flag (default `"/var/cache/melange"`), which is bound into the build environment at `/var/cache/melange` (constant), and updates the fetch.yaml pipeline to look for files matching the `expected-sha{256,512}` in that directory.
The intention is that builds could pre-fetch external dependencies into
the cache directory, then execute builds without hitting the network.
If --cache-dir doesn't exist, it's not bound and fetch will always wget.
Also adds CI checks to build all examples.
Fixes https://github.com/chainguard-dev/melange/issues/144
> fetch: check a cache directory for files matching expected SHAs

- docs/BUILD-CACHE.md
- docs/BUILD-PROCESS.md
- docs/SHELL-OVERLAY.md
First cut at documenting how the build process works at a high level, what directories it uses, what it depends upon.
> document the build process and directories, cache and shell overlay

- pkg/build/build.go
- pkg/build/pipeline.go
- pkg/cli/build.go
This is a commonly requested feature when debugging builds.
With this PR, you can define labels in pipelines, which can be used as breakpoints and continuation points.  That looks like:
```yaml
pipeline:
- label: foo
runs: |
echo hello!
- label: bar
- label: baz
```
When you use `--breakpoint-label=bar`, it will stop before executing `bar`, like a traditional breakpoint.
To continue with the example from above, you can also continue from points in the build with `--continue-label=bar`.  This depends on providing a pre-existing workspace, and optionally, a pre-existing guest environment.  If you provide a pre-existing guest environment, apko will be used to refresh the guest without downloading everything again.
This allows for rerunning build steps that previously failed (e.g. after you …
> add support for breakpoints and continuation points

- README.md
- go.mod
- go.sum
- pkg/build/build.go
- pkg/build/build_test.go
- pkg/cli/build.go
Signed-off-by: Jason Hall <jason@chainguard.dev>
This expands on an idea @luhring had in #161 to rely on YAML-defined key/value pairs instead of Go templates.
It's not yet a fully complete idea, just a starting point to discuss how we might like this to work.
As an example:
```
package:
name: hello
version: world
pipeline:
- name: hello
runs: world
data:
- name: animals
items:
dogs: loyal
cats: angry
turtles: slow
subpackages:
- range: animals
name: ${{range.key}}
pipeline:
- runs: ${{range.key}} are ${{range.value}}
```
When a `subpackage` specifies a `range`, key/value pairs for that range must be specified in `data`, where each item in the k/v pair gets expanded in the `subpackages` array before proceeding to the next one.
Multiple named `data`s can be provided, and the order according …
> Support range for subpackages; drop templates

- examples/go-hello.yaml
- pkg/build/pipelines/go/build.yaml
This PR adds a new built-in pipeline to melange run go builds.
It supports a few options to pass to the compiler like tags, ldflags
and support to relocate the binary using a prefix and target directory.
Example usage:
```yaml
pipeline:
- uses: fetch
with:
uri: https://github.com/puerco/hello/archive/refs/tags/v0.0.1.tar.gz
expected-sha512: 8b6a997ef52711cfe29ede1510cd4b2.....
- uses: go/build
with:
package: main.go
output: hello
```
A simple example is included.
> Go pipeline

- .github/workflows/e2e.yaml
- pkg/build/build.go
- pkg/sbom/bom.go
- pkg/sbom/generator.go
- pkg/sbom/implementation.go
- pkg/sbom/implementation_test.go
This PR wires SBOM generation into the melange build process.
It creates basic SBOMs for all apks built by melange. The SBOMs themselves only inventory the apk contents and write them to the SBOM. In the next iterations we will start adding features to the SBOMs like language and build deps, vcs references, smarter licensing, etc.
Closes https://github.com/chainguard-dev/melange/issues/141
> Basic SBOM generation in apks

- go.mod
- go.sum
- pkg/sbom/implementation.go
Previously, if there were more files than `RLIMIT_NOFILE`, Melange would fail to generate the package-level SBOM due to exhausting the file descriptors.  Accordingly, limit the number of hashing jobs that can run at the same time to avoid FD exhaustion.
> fix file descriptor exhaustion when hashing files for SBOMs

- pkg/build/pipelines/fetch.yaml
Adds `timeout` option to fetches to ensure `wget` does not hang forever when there are networking issues.
> pipelines: fetch: add timeout option

- pkg/renovate/bump/bump.go
For example, when an existing package version is only `major`.`minor` say texinfo.yaml which is currently 6.8, the go yaml library reads the version as a float.  When writing the file back is is including the `!!float` text in the version value.
Here's an example of a file where this problem exists https://github.com/wolfi-dev/os/pull/148/files/9fa0cc8cc597f5626a1fbffa458e6122a28cb201#r1036805295
> fix: issue with bump where !!float appears the config file

- pkg/build/build.go
- pkg/build/package.go
- pkg/cli/build.go
Bootstrap packages cannot use origin names safely, the APK solver uses them to collapse dependency nodes.
> add --strip-origin-name option for bootstrapping

- pkg/build/build.go
options was typoed as packageOption in e9e20df4, fix the annotation so that it matches what bootstrap packages are actually using
Signed-off-by: Ariadne Conill <ariadne@dereferenced.org>
> build: fix YAML annotation for subpackage.options

- pkg/build/pipeline.go
- factor out on-disk pipeline loading into loadPipelineData
- require on-disk pipeline locations to actually be explicitly configured
Signed-off-by: Ariadne Conill <ariadne@dereferenced.org>
> pipeline: loadUse: refactor pipeline loading

- pkg/container/bubblewrap_runner.go
Builds of Wolfi packages were found to be not reproducible with Melange git outside of the SDK environment (which clears the environment itself).
https://twitter.com/kpcyrd/status/1598712375305289731
Clear the host environment explicitly in Melange to ensure that host CFLAGS do not leak into the build container environment.
> container: BubblewrapRunner: fix leaking of host environment

- go.mod
- go.sum
- pkg/build/build.go
- pkg/build/build_test.go
- pkg/cli/build.go
Previously, we inherited the build environment variables from the SDK image environment.  This causes Melange builds to have problems with reproducibility outside of the SDK image environment.  Accordingly, we add `--env-file` to make the build environment configuration explicit via an environment file.
> Implement support for environment files

- pkg/build/build.go
Now that we explicitly do builds with a blank environment, we must set up some defaults.
> build: set some default environment variables

- pkg/build/build.go
This commit changes the interna SBOM path inside the apk to use the full
version string, including the epoch.
> Rename internal SBOM to use full version

- pkg/build/build.go
This is a follow-up to #202, which fixed the SBOM package version for subpackages. This PR applies the same fix to main packages as well.
> Include epoch in SBOM package version

- pkg/build/pipeline.go
needed for cases where you have a subpipeline which has its own needs
> build: pipeline: apply pipeline needs recursively

- pkg/sbom/generator.go
- pkg/sbom/implementation.go
This PR adds a new stage in SBOM generation, melange will now check the working directory of the apk and if it does not exist, it will skip SBOM generation altogether assuming the apk is empty.
Note log hooks are commented while we wire a logger into the generator
> Skip SBOM generation for empty apks

- pkg/build/pipelines/go/build.yaml
Fixes the error:
`invalid value "{{inputs.ldflags}}" for flag -ldflags: missing =<value> in <pattern>=<value>`
> Fix go pipeline LDFLAGS variable interpolation

- pkg/build/build.go
- pkg/build/logger.go
Previously, the best method available for parsing a Melange config was to call `Load`, which required creating a `build.Context` first.
As our ecosystem consolidates its Melange config parsing logic into Melange itself (which is a good thing), it needs to be as easy as possible to get a decoded configuration to meet a given consumer's needs.
This PR introduces a new `ParseConfiguration` function, along with options for adjusting configuration parsing behavior.
This PR also introduces a `Logger` interface so that it's easier to use the stdlib `log.Logger`, _or not_, depending on one's needs.
> Export functionality for config parsing

- pkg/build/pipelines/go/build.yaml
- pkg/build/pipelines/go/install.yaml
This PR adds a small improvement to the `go/build` pipeline to allow running a build in a different directory than the current $CWD. More importantly, it introduces a new `go/install` pipeline [as suggested by @imjasonh](https://github.com/chainguard-dev/melange/pull/180#pullrequestreview-1192458615)  that runs a go build using `go install ...`.
Here's a sample from my tests:
```yaml
pipeline:
- uses: go/install
with:
package: github.com/uservers/miniprow/actions/broker
version: HEAD
```
Using go install lets us rely on the go binary to download all packages and avoid having to clone repos or `fetch` manually.
> New pipeline go/install

- go.mod
- pkg/build/build.go
- pkg/cli/build.go
- pkg/sbom/bom.go
- pkg/sbom/generator.go
- pkg/sbom/implementation.go
This PR adds package URLs to entries in the SBOMs describing the packages built by melange. In order to configure the purl we now expose a `--namespace` flag that sets the string which will be used as the namespace value in the purl.
@luhring : This PR also removes the aliased `distro=` qualifier that used the same value as the namespace. As wolfi is a rolling (un)distro, we don't need to define it now (we only have one flavor at the moment). If we need a distro qualifier we can add it later.
Here's an example:
```
melange build --namespace=wolfi --arch=x86_64 openssh.yaml
```
```json
"packages": [
{
"SPDXID": "SPDXRef-Package-openssh-server",
"name": "openssh-server",
"versionInfo": "9.0_p1-r0",
"filesAnalyzed": true,
"hasFiles": [
"SPDXRef-File-/etc/ssh/sshd_config", …
```
> Add purl generation and --namespace option to melange build

- pkg/index/index.go
This commit fixes a bug that caused melange to leak file descriptors when generating the apk index, possibly hitting the max open files limit.
> Close lingering file descriptor at index generation

- docs/DEVENV.md
- hack/make-devenv.sh
- hack/melange-devenv.yaml
This PR introduces the first iteration of the melange development environment. It is based on the apko equivalent
with two main differences:
1. It uses our apko image to build the devenv image
2. It is based on Wolfi packages :tada:
To run it, execute the same command as the apko devenv:
./hack/make-devenv.sh
It requires https://github.com/wolfi-dev/os/pull/118 to fix a bug with the wolfi key locations and to enable https://github.com/wolfi-dev/os/pull/119 which is required to build the `alpine-keys` wolfi package (required to build the devenv image).
> melange development environment

- pkg/sbom/bom.go
- pkg/sbom/implementation.go
This PR introduces a change to make sure all packages and files in the SBOM have valid SPDX identifier strings 
> Ensure valid SPDX identifier strings

- pkg/build/build.go
- pkg/build/package.go
this is needed for cases where we have two providers which are otherwise equivalent
> allow provider priority to be configured

- go.mod
- go.sum
- pkg/build/build.go
This commit drops the dependency on the old chainguard/vex module in the melange builder.
> Drop dependency on chainguard/vex 

- pkg/build/build.go
- pkg/sbom/bom.go
- pkg/sbom/generator.go
- pkg/sbom/implementation.go
This PR modifies melange to generate an SBOM describing the build environment assembled to build the apks in a build. The new SBOM lists all the SBOMs installed into the build environment in a package describing them as a bundle.
The build environment package links to the produced apks identifying itself as a `BUILD_TOOL_OF` of the package. It looks like this:
```
📂 SPDX Document apk-hello-2.12-r0
│ 
│ 📦 DESCRIBES 1 Packages
│ 
├ hello-build@2.12-r0
│  │ 🔗 29 Relationships
│  ├ DEPENDS_ON PACKAGE glibc-locale-posix@2.36-r4
│  ├ DEPENDS_ON PACKAGE wolfi-baselayout@20221118-r0
│  ├ DEPENDS_ON PACKAGE glibc@2.36-r4
│  ├ DEPENDS_ON PACKAGE binutils@2.39-r4
│  ├ DEPENDS_ON PACKAGE libstdc++-dev@12.2.0-r6
│  ├ DEPENDS_ON PACKAGE libgcc@12.2.0-r6
│  ├ DEPENDS_ON PACKAGE libstdc++@12.2.0-r6
│  ├ …
```
> Generate build environment SBOM

- examples/working-directory.yaml
- pkg/build/build.go
- pkg/build/pipeline.go
This allows pipelines like:
```yaml
pipeline:
- working-directory: /home/build/foo
runs: |
echo "current working directory: $(pwd)"
- working-directory: /home/build/bar
pipeline:
- runs: |
echo "current working directory: $(pwd)"
- working-directory: /home/build/baz
runs: |
echo "current working directory: $(pwd)"
```
This will output:
```
current working directory: /home/build/foo
current working directory: /home/build/bar
current working directory: /home/build/baz
```
`working-directory` can also be used with `uses`, e.g.
```yaml
pipeline:
- working-directory: /home/build/srcA
uses: fetch
with:
...
```
In that example, the fetched source will be populated in `/home/build/srcA`, rather than the default `/home/build`.
cc @luhring
> pipelines: add working-directory modifier

- examples/vars.yaml
- pkg/build/build.go
- pkg/build/pipeline.go
- pkg/cli/build.go
This adds a new section to the melange configuration: a *variable configuration block*.
```yaml
vars:
uri: https://example.com/foo.tar.gz
expected-sha256: 2f2846c86932b2b70dcc791e58e8c2c1e11d0ec25ba3df5ed67641d73e763822
build-directory: /home/build/foobar
baz: "hello world"
```
These variables can be used as one would expect, e.g.
```yaml
pipeline:
- working-directory: ${{vars.build-directory}}
uses: fetch
with:
uri: ${{vars.uri}}
expected-sha256: ${{vars.expected-sha256}}
- runs: |
echo "${{vars.baz}}"
```
A yaml file containing an alternative variable configuration block can be specified with `--vars-file`.  The variables defined in that alternative configuration block file will overwrite the variable data defined in the configuration file.
> add build variable configuration block, --vars-file build option

- pkg/build/build.go
- pkg/index/index.go
I'm new to melange codebase so bear with me here :)
This PR will help to speed up apkindex generation when we build a new package by merging apkindex if exists.
Fixes: #279 (hopefully :)))
Signed-off-by: Tuan Anh Tran <me@tuananh.org>
> use merge option to speed up apkindex generation when build

- pkg/build/package.go
previously we depended on libc appearing in the DT_NEEDED list to pull in the ELF interpreter.
closes #281.
> package: ensure PT_INTERP is always added as an explicit dependency

- pkg/build/package.go
ELF specification requires the PT_INTERP program header to be nul-terminated.  Since go does not make use of nul-terminated strings, this meant that the nul was captured into the string.
Strip the nul at the end to deal with it.
> package: findInterpreter: chop trailing nul from interpBuf

- pkg/build/build.go
- pkg/build/package.go
a "replaces" relationship is used to define that a package may overwrite files belonging to the package declared in the "replaces" relationship.
> build: package: add support for defining "replaces" relationships

- examples/options.yaml
- pkg/build/build.go
- pkg/build/build_option.go
- pkg/build/pipeline.go
- pkg/cli/build.go
Adds two new features:
**Build options**
These allow patching the build configuration with configurable build variants.  Packages can be added, or removed from the build dependencies, and build variables can be changed.  Additional variables reflecting the build option name are reflected in conditionals.
**Subpackage conditionals**
These control whether or not specific subpackages get built.  They are intended to be used with the `${{options.foo.enabled}}` variables, for example:
```yaml
subpackages:
- if: ${{options.foo.enabled}} == 'true'
name: 'foo'
pipeline:
...
```
> add configurable package building options and if-conditionals for subpackages

- pkg/build/package.go
- pkg/build/package_test.go
Although apk can handle self-dependencies just fine, it warns about them when using "apk dot".
Noticed while debugging a dependency issue in Wolfi.
> remove self-provided dependencies from the runtime dependency set

- pkg/build/package.go
the logic for generating provides entries was copied too closely.
this resulted in some dependencies being generated, e.g. `so:libc.so.6=6`.  while this is a valid APK dependency, we should avoid this type of dependency, as we may change the provide in the future to be the package version.
> package: only use base soname when generating runtime dependencies across symlinks

- pkg/build/build.go
These fields are regularly expected to be empty, and YAMLifying them results in unnecessary lines.
> add omitempty to some fields

- .chainguard/source.yaml
The check isn't required, but at least this will give us a nice ✅ instead of the big scary ❌.
> accept dependabot's GPG key for commit signing CI check

- pkg/cli/build.go
Should help make things like https://github.com/chainguard-dev/melange/pull/304 easier.
cc @strongjz
> change --out-dir to not depend on cwd

- pkg/build/pipelines/autoconf/configure.yaml
Needed for packages like dhcping which have very old `config.guess` files.
> autoconf: always define the GNU host and build triplets in configure step

- pkg/container/bubblewrap_runner.go
Without it, it is possible to escape the sandbox via TIOCSTI ioctls on the session PTY.
Related: https://github.com/containers/bubblewrap/issues/555
Related: https://github.com/containers/bubblewrap/issues/142
Related: https://news.ycombinator.com/item?id=30825088
> container: bubblewrap runner: use --new-session to mitigate CVE-2017-5226

- pkg/build/pipeline.go
in some cases, mkdir -p will fail if a directory already exists, if the permissions wouldnt have allowed it to be created to begin with.
> pipeline: only run mkdir -p if absolutely needed

- pkg/index/index.go
I've seen this occur a few times in prod, and it's just a guess, but I think new package versions aren't making it into the index when run in merge index mode.
I attributed it to a race condition (which I think happens too), but I think this is also an issue.
> Try to fix a strange index generation bug.

- pkg/build/pipelines/ruby/build.yaml
- pkg/build/pipelines/ruby/clean.yaml
- pkg/build/pipelines/ruby/install.yaml
The `ruby/clean` pipeline was removing files from the wrong directory causing bloat in gems. I also added some more options to the other gem pipelines to make them a little more flexible
> Fix `ruby/clean` pipeline to remove files from the right directory

- pkg/build/pipelines/git-checkout.yaml
This suppresses weird "dubious permissions" errors from Git when Melange is running builds as a Docker controller rather than using Bubblewrap.
cc @dlorenc (who pointed this out in Slack with a testcase)
> pipelines: git-checkout: mark clone directory as a safe directory for git

- pkg/build/build.go
- pkg/build/pipeline.go
- pkg/build/pipeline_test.go
- pkg/cond/parser_test.go
- pkg/cond/subst.go
- pkg/cond/subst_test.go
The `cond` package was introduced for `if` expressions.  It allows whitespace in variables such as `${{ foo }}`, instead of `${{foo}}`.
By using `cond` package for substitutions, we can have whitespace in variable substitutions.
Needs more extensive tests, but is promising.
Closes #176.
> Use cond package to do variable substitution

- docs/md/melange_build.md
- go.mod
- go.sum
- pkg/build/build.go
- pkg/cli/build.go
Previously `--cache-dir` was assumed to be both a GCS bucket and a destination directory.  This made the feature unusable on Darwin hosts, which rejected the GCS bucket name as a valid filename on disk.
Fixes #329.
> Refactor --cache-dir and separate preloading concerns into --cache-source

- pkg/cli/commands.go
- pkg/cli/packageversion.go
- pkg/cli/query.go
Since melange already is parsing yaml files, might as well use it to report on information.
> add query and package-version commands

- pkg/cli/packageversion.go
- pkg/cli/query.go
Previously we relied on `build.New()` to get a `BuildContext`, which has `bc.Configuration`, which we passed to the template.
But that assumed a lot of things about the build environment, since it is a build context. Those things sometimes break. In any case `build.ParseConfiguration()` is exported.
This changes it to just call `ParseConfiguration` directly.
> directly parse configuration for query

- pkg/build/package.go
Otherwise cross-compilation gets... interesting...
Pointed out by @dlorenc.
> build: package: do not add interpreter dependency when no-depends option is enabled

- examples/pipelineless.yaml
- pkg/build/build.go
- pkg/build/package.go
This is intended to allow empty packages which just pull in other dependencies like `wolfi-base` and `build-base` to be built without the need for a pipeline.
This is the first step in realizing #311.
> Allow construction of empty packages without environment/pipelines

- pkg/index/index.go
Before:
```
melange: generating index at packages/aarch64/APKINDEX.tar.gz with new packages: [0x140001c2000]
```
After:
```
melange: generating index at packages/aarch64/APKINDEX.tar.gz with new packages: [aws-sdk-core-3.168.4-r0]
```
> fix: log package new names+versions when regenerating index

- README.md
- docs/BUILD-PROCESS.md
- examples/aws-sdk-core.yaml
- examples/build-ruby-webrick.yaml
- examples/conditional.yaml
- examples/gnu-hello-wolfi.yaml
- examples/gnu-hello.yaml
- examples/mbedtls.yaml
- examples/options.yaml
- examples/simple-hello/melange.yaml
- examples/sshfs.yaml
- examples/vars.yaml
- examples/working-directory.yaml
- go.mod
- go.sum
- melange.yaml
- pkg/build/build.go
- pkg/cli/build.go
This lets configs describe which archs they want to be built for. If the field is unset, this assumes all architectures. If the field is set to `['all']`, we'll log a warning and interpret it as if it was unset.
I've updated an example to specify it only wants to be built for one arch. These work, and build only for that one configured arch:
```
$ go run ./ build examples/aws-sdk-core.yaml --arch=x86_64
$ go run ./ build examples/aws-sdk-core.yaml
```
This fails:
```
$ go run ./ build examples/aws-sdk-core.yaml --arch=aarch64
Error: target-architecture and --arch do not overlap, nothing to build
```
> feat: respect target-architecture to filter archs

- pkg/build/pipelines/autoconf/make-install.yaml
Otherwise these `.la` files stick around and cause all sorts of problems, such as overlinking, and wasting developer time chasing things that aren't really problems.
> pipelines: autoconf/make-install: delete all GNU libtool metadata files

- pkg/build/build.go
- pkg/build/logger.go
- pkg/build/pipeline.go
The Melange `Pipeline` type shouldn't rely on a concrete type like `*logrus.Entry`, because this requires users to have a concrete type or `nil`, and `nil` causes panics in the logger implementation.
Using an abstraction instead allows consumers to use other loggers (including a `nopLogger`) when logging isn't needed or wanted.
This caused a panic in `wolfictl`, and a forthcoming wolfictl PR will take advantage of this change (with tests!).
> Do not depend on concrete logger

- pkg/build/build.go
- pkg/cli/build.go
- pkg/renovate/bump/bump_test.go
This PR fixes two issues:
1. A test for the bump logic was using `assert.NoError` instead of `require.NoError`, so it panicked when the test proceeded to use a nil object after an error case.
2. `ParseConfiguration` wasn't correctly handling abstract filesystems. In general, when using an `fs.FS`, the code should be able to trust that the config file path is meant for that filesystem, but it was using `filepath.Base` in anticipation of receiving an absolute filepath for the actual OS filesystem. This PR detects if the caller is setting their own `fs.FS` and uses the given path "as-is" if so. In the future, we should adjust `ParseConfiguration` to always use a provided `fs.FS` and thus always trust that the given config path is correct as-is.
These issues were caught via tests in …
> Fix parse configuration's use of abstract filesystems

- go.mod
- go.sum
To pick up the `~` version matching fixes.  Thanks @deitch!
> upgrade apko to 20230421 snapshot

- pkg/build/build.go
changes the `DataItemList` type in favor of a `map[string]string` type.
This makes lets us use the default serialization for `map[string]string`, while still retaining the deterministic sort behavior.
This makes it easier for external tooling that parses the struct types/encoding to figure out what's going on, and supports efforts like https://github.com/wolfi-dev/wolfictl/pull/190
> simplify DataItems to use the builtin marshallable map type

- pkg/build/build.go
This is useful in `wolfictl`, and implements a `Configuration` interface used as a generic type constraint.
See related: https://github.com/wolfi-dev/wolfictl/pull/198
> Add name method to build config

- pkg/build/pipelines/go/build.yaml
This seems like a best practice. I've been working to convert some non-pipeline go build yamls over to use the pipeline, and this would help.
> Add trimpath to the go pipeline.

- pkg/build/package.go
End-user programs are the only type of ELF object where it would make sense for an ELF interpreter to be set on the on the ELF object.  Accordingly, treat any object which has an ELF interpreter set on it as an end-user program and skip SONAME analysis for them.
Certain end-user programs such as the ones included with OpenJDK 8 have a bogus SONAME (`lib.so`) set on them, which otherwise should not be there.
> build: package: skip SONAME analysis when ELF interpreter setting is present

- mac/README.md
- mac/lima/melange-playground.yaml
I had a few issues getting up and running, I think this was mostly due to some out of date paths/filenames
> chore: improve mac quick-start guide

- docs/PIPELINES-GO.md
- pkg/build/pipelines/go/build.yaml
We can use this to hoist up some of the imperative "go get'ing" we do to fix CVEs into a structured format.
> Add an optional "deps" paramter to the go/build pipeline.

- pkg/build/build.go
- pkg/container/bubblewrap_runner.go
a recent change made bubblewrap the default when running melange build natively on mac, as a result builds fail to start...
```
2023/05/13 11:29:15 error during command execution: unable to run container
```
This change adds a warning when the check fails and offers the user help of how to fix.  For example now I need to run `melange build --runner docker`
> add extra logging when runner fails to TestUsability

- pkg/build/build.go
- pkg/build/build_test.go
- pkg/build/pipelines/go/build.yaml
This PR makes sure range data is included in var substitutions for subpackage pipeline `with:` options.  It also allows a boolean to indicate a built go binary should be written to `${{targets.subpkgdir}}` rather than `${{targets.destdir}}`
> Allow built in melange pipelines to be used in subpackages

- go.mod
- go.sum
This pulls in https://gitlab.alpinelinux.org/alpine/go/-/merge_requests/24 to try and get `t:` entries in our `APKINDEX` and installation databases.
> Pull in index builddate support.

- pkg/build/build.go
It can be useful when parsing fails to log the filename of the offending file.
> include filename when parsing fails

- examples/options.yaml
- go.mod
- go.sum
- pkg/build/build.go
This data is no longer managed by Melange (it's managed by `wolfictl`) and should not be used within a build configuration.
> Remove secfixes and advisories altogether

- pkg/build/build.go
- pkg/build/build_test.go
- pkg/build/testdata/configuration_load/invalid-package-name.melange.yaml
- pkg/build/testdata/configuration_load/invalid-range-subpackage-name.melange.yaml
- pkg/build/testdata/configuration_load/missing-package-name.melange.yaml
This ensures we fail fast when detect that a user-supplied value in the build configuration is not valid.
This helps guard against package names like `boost-"atomic"`, which we saw recently (see https://github.com/wolfi-dev/os/pull/2269).
**Note:** For names of packages and subpackages, this implementation requires the following:
- all letters are lowecase
- must start with letter
- the only valid characters are letters, numbers, periods (`.`), dashes (`-`), and underscores (`_`)
Underscores in package names are very rare, but they do exist in Wolfi right now. If we wanted, we could disallow underscores and update any offending package names accordingly:
- `libnetfilter_conntrack`
- `libnetfilter_cthelper`
- `libnetfilter_cttimeout`
- `libnetfilter_queue`
- `ruby3.2-http_parser.rb`
> Validate configuration at the end of parsing

- pkg/build/pipelines/fetch.yaml
Keeping it as true breaks the behavior for extract: false.
Ref: https://github.com/wolfi-dev/os/pull/2533
> Change the default for delete to false.

- .github/workflows/e2e.yaml
- pkg/build/build.go
- pkg/container/kubernetes_runner.go
- pkg/container/kubernetes_runner_test.go
fixes an issue with local files not being bundled correctly in the k8s runner.
this fix is temporary until `kontext.Bundle()` is refactored to use the `go-apk.FullFS` filesystem to bundle/extract, which assumes the workspace is rooted at the base directory by default.
the e2e test is changed to pick a leg that enforces this behavior, so it'll break if we forget to implement the TODO in the future.
> ensure bundles are rooted correctly

- pkg/build/pipelines/split/debug.yaml
adds a `split/debug` package, adopted from splitfunc dbg
sample output testing with openjdk:
```bash
bash-5.2# ls /home/build/melange-out/openjdk-17-dbg/usr/lib/debug/lib/jvm/java-17-openjdk/*
/home/build/melange-out/openjdk-17-dbg/usr/lib/debug/lib/jvm/java-17-openjdk/bin:
jar.debug          jconsole.debug     jinfo.debug        jshell.debug
jarsigner.debug    jdb.debug          jlink.debug        jstack.debug
java.debug         jdeprscan.debug    jmap.debug         jstat.debug
javac.debug        jdeps.debug        jmod.debug         jstatd.debug
javadoc.debug      jfr.debug          jpackage.debug     keytool.debug
javap.debug        jhsdb.debug        jps.debug          rmiregistry.debug
jcmd.debug         jimage.debug       jrunscript.debug   serialver.debug …
```
> add a split/debug pipeline

- pkg/build/build.go
- pkg/cli/apkbuild.go
- pkg/cli/bump.go
- pkg/cli/gem.go
- pkg/cli/index.go
- pkg/cli/python.go
- pkg/cli/update_cache.go
- pkg/container/kubernetes_runner.go
- pkg/container/kubernetes_runner_test.go
- pkg/convert/apkbuild/apkbuild.go
- pkg/convert/apkbuild/apkbuild_test.go
- pkg/convert/gem/gem.go
- pkg/convert/gem/gem_test.go
- pkg/convert/python/pypi.go
- pkg/convert/python/python.go
- pkg/convert/python/python_test.go
- pkg/convert/wolfios/wolfi-os.go
- pkg/convert/wolfios/wolfi-os_test.go
- pkg/http/http.go
- pkg/index/index.go
- pkg/renovate/bump/bump.go
- pkg/renovate/bump/bump_test.go
- pkg/renovate/cache/cache.go
- pkg/renovate/renovate.go
- pkg/util/util.go
Use NewRequestWithContext where applicable and plumb missing contexts to get there. Also handle any stray context.TODO and context.Background instances.
> Add missing context propagation

- pkg/build/build.go
- pkg/build/build_test.go
- pkg/build/testdata/configuration_load/env-vars-set-that-have-default-values.melange.yaml
Melange has sensible default values for the build environment variables for `HOME` and `GOPATH`. But it was using these values even if the Melange user had explicitly set env var values in their config — so their env var values were silently ignored in this case.
> Bug fix: silent env var replacement

- .github/workflows/wolfi-presubmit.yaml
- pkg/build/package.go
the GNU variant of libc (GLIBC) is built as a PIE binary, which otherwise behaves as a shared library.  this is done to enable the `/lib/libc.so.6 --about` command.
> build: package: forcibly treat libc as a shared library

- pkg/build/pipelines/git-checkout.yaml
Deep cloning can cost a lot of time on a per-dev-cycle basis. This changes the default depth to `1` — and it can still be adjusted to any number on a per-build-config basis as needed.
> Change git-checkout depth default to 1

- pkg/container/lima.yaml
- pkg/container/lima_runner.go
1. `limactl` now accepts a more normal `-` for stdin
2. There was a misalignment in our template `lima.yaml`. Older limactl did not care, but newer is stricter (as it should be)
> lima startup issues fixed

- pkg/container/kubernetes_runner.go
this fixes a class of flakes that appear when trying to run a remote command (`k exec`) in a pod that isn't ready to receive requests yet.
the most common example we've seen is on gke autopilot, where nodes can scale up all the way to pod `Running`, but not have a healthy networking backplane yet (`anetd` is still spinning), resulting in a flake that looks like:
```
2023/07/16 05:58:08 error during command execution: failed to build package: unable to run pipeline: running remote command: failed to run remote command: error dialing backend: No agent available
```
this ensures we retry everything that isn't an actual build error, up to 4 times
> K8s runner retry exec

- docs/md/melange_build.md
- pkg/build/build.go
- pkg/cli/build.go
Change the default for runners that create a persisting build environment (everything except `bwrap`) to always destroy the build environment when the build succeeds/fails.
This means runners like `docker`/`kubernetes` don't leave dangling resources around on failures unless the user opts in (`--debug-runner`).
I originally coupled this to the existing `--debug` flag, but then changed my mind and used `--debug-runner`. I'm not married to the semantics so please suggest otherwise!
> Default remove builder

- pkg/build/build.go
splitting this out of #545 because it changes the signature of `RetrieveWorkspace`.
This primarily fixes the kubernetes runner not fetching the full contents of the post-build workspace, which resulted in invalid and mismatched apk's vs the other local runners.
Since this is now really just doing an untar using `apkofs.FullFS`, I think there's merit to moving this out of `melange` and into `go-apk` (maybe `tarball.Untar()`? Say the word and I'll be happy to move it there
> use go-apk.FullFS for retrieving builder workspaces

- pkg/build/build.go
- pkg/container/bubblewrap_runner.go
- pkg/container/docker_runner.go
- pkg/container/kubernetes_runner.go
- pkg/container/lima_runner.go
- changes the workspace fetcher to use a tgz stream instead
- adds a retryable workspace fetcher for the k8s runner. this was a significant source of flakes that is mostly eliminated now
- updates the other runners that use workspace fetcher to use tgz (`lima`)
> K8s runner fetch workspace tgz

- go.mod
- pkg/build/package.go
Switching from pargzip to pgzip showed much better efficiency over in apko, so let's do the same here to see if it frees up any resources during megabuilds.
For smaller sections (control and signature), this just uses klauspost's gzip implementation instead of pgzip since don't need parallel compression for such tiny inputs.
This will change the hashes of APKs because the compression will be different, but I don't believe we rely on reproducibility in melange.
> Avoid using pargzip for compression

- pkg/build/build.go
- pkg/container/config.go
- pkg/container/kubernetes_runner.go
the melange cache mounts are primarily designed for bind-mounted runners, which k8s is not. in remote execution environments, it's usually just faster to redownload things than to push/pull them in.
using the cache mount for k8s runner ends up just creating more things that need to be transferred over the network via kontext -> OCI registry, and can lead to pretty silly processing if you're not careful.
this also prevents @mattmoor from destroying his poor computer/network
> skip the cache mount for kubernetes runner builds

- pkg/cli/build.go
This reverts fdf0cbfc73548c6bae6bf85a5a7120889867c81e which avoided double-printing (some?) errors, but the net effect of this is that some errors are never printed.
Performing world builds, I see half a dozen failures(?) where the logs end without actually printing anything actionable:
```
...
ℹ️  x86_64    | populating cache from
ℹ️  x86_64    | populating workspace /home/user/tmp/melange-workspace-2016802746 from ./jaeger-agent/
ℹ️  x86_64    | --cache-dir ./melange-cache/ not a dir; skipping
ℹ️  x86_64    | ImgRef = gcr.io/mattmoor-chainguard/wolfi-os-builds@sha256:98b659b74c47411018b386fdb4fbb8aa0140eb5b11c19b1473c99c96da2524ef
ℹ️  x86_64    | creating mount 'mount-0' from /home/user/tmp/melange-workspace-2016802746 at /home/build
ℹ️  x86_64    |   workspace dir: …
```
> Make sure we log errors.

- go.mod
- go.sum
- pkg/container/kubernetes_runner.go
- pkg/container/kubernetes_runner_test.go
adds a 3rd config loading strategy to put us at:
1. env (for certain fields)
2. `.melange.k8s.yaml`
3. defaults
adds tests to cover
> add k8s runner config loading from envvars

- pkg/build/pipelines/fetch.yaml
This removes the `-q` from the `wget` options in the `fetch` pipeline because it masks any errors `wget` saw that resulted in failures, which hinders our ability to triage without retrying the `wget` ourselves (in some cases enough for it to fail again).
This logging seems like small peas compared to other things, so hopefully this isn't contentious.
As anecdata, in my last world build, 4 of the builds failed with silent `wget` failures, and I was only able to reproduce `nasm.us` being down.
> Remove `wget -q` from `fetch`

- pkg/build/pipelines/strip.yaml
This seems like a less racy way of achieving the temp file check, so figured I'd propose it. 🤞
> Tweak the strip pipeline so that it never fails for deleted files

- pkg/convert/python/python.go
In case there is no `sdist` package, `convert python` command currently error out `SHA256 Generation FAILED`. Which might be slightly mislead. The actually error is that, we couldn't even find any release to proceed.
Example package to reproduce: https://pypi.org/pypi/ml-metadata/json
> convert/python: check if release is found

- pkg/build/build.go
We need to generate SBOMs after we fetch the workspace, since the subpackage filesystem may not be available locally.
> Fix subpackage SBOM generation

- pkg/build/build_test.go
- pkg/config/config.go
- pkg/renovate/bump/bump.go
- pkg/renovate/cache/cache.go
- pkg/renovate/renovate.go
This is part of the project to add var transforms to renovate.
This does not yet do the var transforms, that is forthcoming work.
> renovate: update to use new config infrastructure

- pkg/build/pipelines/meson/configure.yaml
Meson has deprecated the default behavior of invoking the setup action when a path is provided as the first command-line argument, printing:
```
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```
> pipelines: meson/configure: explicitly invoke meson setup action

- pkg/build/build_test.go
- pkg/build/pipeline.go
- pkg/build/pipeline_test.go
- pkg/config/vars.go
- pkg/renovate/bump/bump.go
- pkg/renovate/bump/testdata/major_minor_patch.yaml
- pkg/renovate/renovate.go
- pkg/util/map_subst.go
My previous work has now come to a head and now var transforms work in bump with this patch.
Not all variables are available for substitution at the moment, as that would complicate the logic considerably. Variables that are presently supported for substitution:
- ${{package.name}}
- ${{package.version}}
- ${{package.epoch}}
- ${{build.arch}}
This is sufficient for now. All packages that use var transforms only transform the version at present.
> Make var transforms work in bump

- pkg/container/bubblewrap_runner.go
In go, defer statements are scoped to the function level, not the block level, so this results in file descriptor exhaustion for guests which have more than RLIMIT_NOFILE files installed in them.
Instead, immediately close files after writing their contents.
> container: bubblewrap: do not defer closing files

- go.mod
- go.sum
- pkg/build/package.go
This creates providers such as `pc:glib-2.0=2.76.4`.
It can optionally create *dependencies* too, which result in the relevant `-dev` packages relating to pkg-config dependencies being pulled in as build-time dependencies.  This feature is disabled until we have rebuilt enough of Wolfi to make it tenable.
> build: package: add pkgconf-based SCA to catalog SDKs which use it

- .pre-commit-config.yaml
- README.md
- hack/make-devenv.sh
- pkg/build/runner.go
- pkg/cli/index.go
- pkg/cli/packageversion.go
- pkg/cli/sign.go
- pkg/cli/update_cache.go
- pkg/config/config.go
- pkg/container/kubernetes_runner.go
- pkg/convert/gem/gem_test.go
- pkg/http/http.go
- pkg/renovate/bump/bump.go
- Some typo corrections
- Doc line above exported consts and functions
- Implemented some golint suggestions
I also added `.pre-commit-config.yaml` to the repo. To use it:
- `pip install pre-commit`
- Install the following Go packages:
* go install github.com/go-critic/go-critic/cmd/gocritic@latest
* go install https://pkg.go.dev/golang.org/x/tools/cmd/goimports@latest
* go install golang.org/x/lint/golint@latest
- In your clone, run: `pre-commit install`
This will create .git/hooks/pre-commit and following that, these tests will run every time you invoke `git commit`:
```sh
go fmt...................................................................Passed
go imports...............................................................Passed
go …
```
> doc and lint revisions

- pkg/config/config.go
This is preliminary work to add reverse version mapping to map package versions to valid APK versions.
This only teaches Melange about the proposed new block, there are no functional changes beyond this as of yet.
> Version transform block in melange

- pkg/container/kubernetes_runner.go
Also, thanks to https://github.com/chainguard-dev/melange/blob/main/pkg/container/kubernetes_runner.go#L502-L505, this is settable in an env var as well.
> Support for setting context in .melange.k8s.yaml

- docs/md/melange.md
- docs/md/melange_sign.md
- pkg/build/package.go
- pkg/build/sign.go
- pkg/build/sign_test.go
- pkg/cli/commands.go
- pkg/cli/sign.go
Adds a `melange sign ...` command to (re-)sign apks with the provided key.
This also slightly refactors the emit signature section of the PackageBuild to reuse the signing method.
The refactor includes:
- handle the control data + signing in memory
- hoist the signing into `build.EmitSignature(...)` to reuse the content digest for the various `ApkSigner` implementations
Sample:
```bash
❯ tar tvf packages/aarch64/kubelet-latest-0-r0.apk
-rwxrwxrwx  0 root   root      512 Dec 31  1969 .SIGN.RSA.local-melange.rsa.pub
-rw-r--r--  0 root   root      333 Aug 16 12:26 .PKGINFO
drwxr-xr-x  0 root   root        0 Aug 16 12:26 usr
drwxr-xr-x  0 root   root        0 Aug 16 12:26 usr/bin
lrwxr-xr-x  0 root   root        0 Aug 16 12:26 usr/bin/kubelet -> kubelet-1.28
drwxr-xr-x  0 root   root        0 …
```
> add melange sign command, slightly refactor and make public the signing methods

- examples/replacement-provides.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/vars.go
This enables:
```
package:
name: go-1.23
version: 1.23.0
dependencies:
provides:
- go=${{package.version}}
```
Also supported for subpackages, also supporting `vars:`.
> support substitutions in provides lists

- pkg/build/pipeline.go
- pkg/build/pipelines/autoconf/make-install.yaml
- pkg/build/pipelines/cmake/install.yaml
- pkg/build/pipelines/go/build.yaml
- pkg/build/pipelines/go/install.yaml
- pkg/build/pipelines/meson/install.yaml
- pkg/build/pipelines/ruby/install.yaml
- pkg/build/pipelines/split/debug.yaml
- pkg/build/pipelines/split/dev.yaml
- pkg/build/pipelines/split/infodir.yaml
- pkg/build/pipelines/split/locales.yaml
- pkg/build/pipelines/split/manpages.yaml
- pkg/build/pipelines/split/static.yaml
- pkg/build/pipelines/strip.yaml
- pkg/config/vars.go
Adds `${{targets.contextdir}}` variable expansion which maps to the current package output context directory.  This is intended to be used as a destination target instead of `${{targets.destdir}}` and `${{targets.subpkgdir}}`, allowing pipelines to be more reusable in subpackages, without hacks like `${{inputs.subpackage}}`.
> Add ${{targets.contextdir}}

- docs/md/melange_sign-index.md
- pkg/cli/sign.go
adds an opt in `--force` to `melange sign-index` that when provided, will create a new apk index with the provided key file, regardless of any existing signatures.
```bash
➜ curl -sfL https://packages.wolfi.dev/os/aarch64/APKINDEX.tar.gz -o idx
➜ tar tvf idx
-rw-r--r--  0 root   root      512 Dec 31  1969 .SIGN.RSA.wolfi-signing.rsa.pub
-rw-r--r--  0 0      0     3822057 Dec 31  1969 APKINDEX
-rw-r--r--  0 0      0           0 Dec 31  1969 DESCRIPTION
➜ melange sign-index --signing-key something-else.rsa idx -f
ℹ            | signing index /var/folders/5v/6gvb9x954sbd9tmqq14cwgrh0000gn/T/melange-sign-index2134875588 with key something-else.rsa
ℹ            | appending signature to index /var/folders/5v/6gvb9x954sbd9tmqq14cwgrh0000gn/T/melange-sign-index2134875588
ℹ            | writing …
```
> add --force option to recreate apk indexes with given signatures

- pkg/cli/sign.go
Previously, we used os.CreateTemp to create the new index in /tmp, but renaming from tmpfs to on-disk storage cannot work due to being on different filesystems.
> sign: do not rename across device boundaries

- .github/workflows/verify.yaml
- Makefile
- docs/main.go
- docs/md/melange.md
- docs/md/melange_build.md
- docs/md/melange_bump.md
- docs/md/melange_completion.md
- docs/md/melange_convert.md
- docs/md/melange_convert_apkbuild.md
- docs/md/melange_convert_gem.md
- docs/md/melange_convert_python.md
- docs/md/melange_index.md
- docs/md/melange_keygen.md
- docs/md/melange_package-version.md
- docs/md/melange_query.md
- docs/md/melange_sign-index.md
- docs/md/melange_sign.md
- docs/md/melange_update-cache.md
- docs/md/melange_version.md
Fixes #623 
Since it would seem that the existing behavior creates something elsewhere, added a new Makefile target that produces correct links within the repo, and to control that needed to add a --suffix flag (previously, it hardcoded '/').
Also add two previously missed files:
`query`, and `package-version`.
> Fix the links to commands, fix the URLs generated.

- pkg/convert/apkbuild/apkbuild.go
- pkg/convert/gem/gem.go
- pkg/convert/python/python.go
- pkg/manifest/manifest.go
I missed the fact that the file was generated in ./generated and because of a .gitignore in wolfi-os repo, it seemed to my untrained eye like nothing was created and I didn't see anything in the logs printed, so figured this might save somebody else a little bit of time/troubleshooting.
Example output 
```
vaikas@vaikas-MBP os % melange convert python pycparser
2023/08/29 14:21:32 convert:python: generating convert config files for python package pycparser version: 3.11 on python version:
2023/08/29 14:21:32 convert:python: [pycparser] Generating manifests
<SNIP SNIP SNIP>
2023/08/29 14:21:33 convert:python: [pycparser] Generate Pipeline for version 2.21
2023/08/29 14:21:33 convert:python: Generated melange config: generated/py3.11-pycparser.yaml
```
> Print the path to generated melange config.

- pkg/build/pipelines/git-checkout.yaml
Include the ability to use the flag --recurse-submodules to the git-checkout pipeline. This allows repositories that include submodules to be checked out in one go.
> feat: support --recurse-submodules in git clone

- docs/md/melange_convert.md
- docs/md/melange_convert_apkbuild.md
- docs/md/melange_convert_gem.md
- docs/md/melange_convert_python.md
- go.mod
- go.sum
- pkg/cli/apkbuild.go
- pkg/cli/convert.go
- pkg/cli/gem.go
- pkg/cli/python.go
- pkg/convert/gem/gem.go
- pkg/convert/gem/gem_test.go
- pkg/convert/python/python.go
- pkg/convert/python/python_test.go
Prior to this change, wolfi repo / keyring was hardcoded to python/gem convert command. Add a flag --wolfi-defaults if set to false will not do that. Motivation is that then removing them is manual work, that shouldn't be necessary. Default behaviour is unchanged.
Also unified the flag handling so that the common flags are specified in one place and not replicated.
Also fixed couple of .Equal commands where the expected / got were reversed which made it wonky to read the output.
> Add --wolfi-defaults flag, clean up flag handling.

- docs/BUILD-FILE.md
While learning about, couldn't really find one place to understand the build file, fields, etc. so figured I'd take a crack at creating one. Not comprehensive, but a start to see if keeping on going makes sense.
> Start of exhaustively documenting the build file.

- pkg/build/pipelines/maven/configure-mirror.yaml
We've seen some slowness and flakiness on GCP runners when hitting maven central. Configuring this is tricky, so I made a pipeline.
> Add a maven/configure-mirror pipeline to redirect to GCP.

- pkg/config/config.go
- pkg/convert/apkbuild/apkbuild.go
- pkg/convert/apkbuild/apkbuild_test.go
- pkg/convert/apkbuild/testdata/no_sub_packages.yaml
- pkg/convert/apkbuild/testdata/with_multi_sub_packages.yaml
- pkg/convert/apkbuild/testdata/with_unrecognised_sub_packages.yaml
- pkg/manifest/manifest.go
In order to make the tests pass, I had to change the tests (which I always dislike), but after talking it through, the Environment is required field, so make that change in tests. But I think not having to double-define things is a good thing.
> Change GeneratedMelangeConfig to embed pkg/config/config instead of redefining it.

- .github/workflows/wolfi-presubmit.yaml
- pkg/build/package.go
Fixes building ncurses, which uses symlinks to alias pkg-config modules to other identifiers.
> package: dereference symlinks for aliased pkg-config modules

- pkg/convert/apkbuild/apkbuild.go
Add generated file logs for the APKBUILD converter to match the behaviour of the remaining file converters. This makes the resulting folder more visible to the user.
> feat: add output logs for the apkbuild converter

- pkg/build/pipeline.go
- pkg/build/pipeline_test.go
- pkg/config/vars.go
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>
For version streams you can now use this (instead of the previous .999)
```
dependencies:
provides:
- php=${{package.full-version}}
```
To get version streams.
> add ${{package.full-version}} = ${{package.version}}-r${{package.epoch}}

- docs/BUILD-FILE.md
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>
Document the ${{package.full-version}} variable, and examples on how to / when to use it.
> document / examples for ${{package.full-version}}

- docs/PIPELINES.md
- pkg/build/pipelines/README.md
Add some documentation on how to add new built-in pipelines and the process to bump the melange dependency on wolfictl.
> docs: add documentation for built-in pipelines

- pkg/config/config.go
- pkg/config/config_test.go
Follow up to #662 where the ${{package.full-version}} was only available in pipelines, now available for provides block where it was originally supposed to be in the first place.
> construct the package.full-version in higher context than just pipeline.

- pkg/build/pipelines/README.md
Minor fix in the `pkg/build/pipelines/README.md` to point to the correct header.
> docs: fix link in pkg/build/pipelines/README.md

- pkg/build/pipeline.go
- pkg/build/pipeline_test.go
- pkg/config/config.go
Add environment var overriding to the pipeline block in Melange config.
Fixes #675
> Add environment var overriding to the pipeline.

- pkg/build/package.go
Fixes: daf8941 (package: constrain library SCA to library search paths only)
> package: only constrain library search paths for provides entries

- .github/workflows/build.yaml
- .github/workflows/go-tests.yaml
- .github/workflows/release.yaml
- .github/workflows/verify.yaml
- .github/workflows/wolfi-presubmit.yaml
This bumps the Go tests to 1.21. Blocking #680 because slices is a 1.21 package.
> Bump go tests to 1.21

- pkg/build/pipeline.go
- pkg/config/config_test.go
A melange pipeline can reference other pipelines with the `uses` statement, e.g.
```yaml
pipeline:
- uses: foo
```
However, a long standing bug has existed where the pipeline settings did not necessarily propagate downstream.  This bug recently became exposed by refactoring of the pipeline code to perform downward propagation at configuration load time rather than runtime.
We also add regression tests for various forms of downward propagation in the config struct.
> Add regression tests for workdir propagation, fix long-standing bug with propagation across referenced pipelines

- .github/workflows/e2e.yaml
I missed this in #682. Exactly what it says on the tin.
> Bump k8s test workflows to Go 1.21

- .github/workflows/verify.yaml
This updates golangci-lint to 1.54. 1.53 seems to have some bugs...
> golangci-lint version bump to 1.54

- .github/workflows/e2e.yaml
- examples/git-checkout.yaml
- pkg/build/pipelines/git-checkout.yaml
fuzzy matching of refs.
Previously, we were somewhat loose with allowed revisions - the branch check for origin/foo could technically match a tag named origin/foo, and vice-versa for tag names. This changes the behavior to use rev-parse --verify to guarantee that we are looking up by the intended branch/tag name.
This also looses the allowed revisions for tags to allow the true SHA for an annotated tag. Previously we only allowed the unpeeled values and would reject the true SHA.
Fixes https://github.com/chainguard-dev/melange/issues/685
> git-checkout: Allow tags to matched annotated tag SHAs, don't allow

- pkg/build/build.go
- pkg/build/linter.go
- pkg/build/linter_test.go
- pkg/config/config.go
This implements binary package linting per the spec, as found [here](https://inky.wtf/linterdesign).
A few things I want looked at:
- Is the linter context part ok? It hasn't been reviewed in the doc yet, but I went ahead and did it.
- Should more linters be added? If so, what? So far there is a setuid/setgid linter, a linter for checking for packages writing files in temp dirs, a linter for checking if /var/empty is being written to, and a check for /usr/local.
- ~~Should [chainguard-dev/go-apk#117](https://github.com/chainguard-dev/go-apk/issues/117) be fixed first or should I not bother?~~ **EDIT:** Decided not to bother for now.
> Binary package linting

- pkg/build/pipelines/goreleaser/build.yaml
The idea behind using GoReleaser as one of the optional pipelines in Melange is that GoReleaser is very popular in both the open source and go world. We thought it would be good to join forces to bring the attention of GoReleaser fans to Wolfi OS as well.
Let's consider building [grpc-health-probe](https://github.com/grpc-ecosystem/grpc-health-probe) project for a second, if we assume using this new goreleaser pipeline do to this, the pipeline for this would be looking like the following:
```shell
pipeline:
- uses: git-checkout
with:
repository: https://github.com/grpc-ecosystem/grpc-health-probe
tag: v${{package.version}}
expected-commit: 1089f40639043ee46cc47cbea1bcb0cc48cfc284
destination: grpc-health-probe
- uses: goreleaser/build
with:
args: --snapshot
working-dir: grpc-health-probe …
```
> add goreleaser pipeline

- pkg/build/linter.go
We can't do much about -compat packages, so we shouldn't lint them.
> Disable linters on -compat packages

- pkg/build/package.go
Also only match files ending in `.pc`
We weren't able to build some packages that contained paths like `usr/share/mime/application/vnd.tcpdump.pcap.xml` because the post-build pkgconfig pass tried to parse that file and failed.
> log and continue when .pc file can't be loaded

- pkg/build/linter.go
- pkg/build/linter_test.go
- pkg/config/config.go
These linters catch writing to /dev, /opt, and /srv respectively. These are locations that should not be written to under normal circumstances by a package.
> Add dev, opt, and srv linters

- pkg/build/pipelines/goreleaser/build.yaml
We expect from end users to set the output dir as an explicit way so we just need to grab the dir name and create that dir without adding ${{targets.contextdir}} in front of it.
Also, we noticed an error for file format while stripping the binary, so, this PR also aims to fix that as well: #693
> fix the dir name as we already expect dir to be set explicit

- pkg/build/linter.go
- pkg/build/linter_test.go
- pkg/config/config.go
This checks for world-writeable files in packages, and will warn about them. Especially serious are world-writeable packages that are also executable. This is a security risk.
Directories are skipped on purpose.
> Add worldwrite linter

- pkg/build/linter.go
- pkg/build/linter_test.go
- pkg/config/config.go
This checks for empty packages and also adds a facility to allow for post-walk lints that can walk the tree or do whatever.
> Add post-file walk linting and empty package linting

- pkg/build/build.go
- pkg/linter/linter.go
- pkg/linter/linter_test.go
I intend to write an interface that mounts an APK as a filesystem and scans it with the file linter. This is preliminary work in that direction.
> Refactor the package linter into a submodule

- examples/git-checkout.yaml
- pkg/build/build.go
Add package lints to a queue rather than running them at the end of the pipeline, this allows linting to be deferred until after the pipelines complete and the workspace is retrieved from the Kubernetes environment.
> build: refactor package linter invocation

- pkg/build/pipelines/ruby/clean.yaml
These directories were previously being deleted but they contain metadata necessary for gem native extensions and plugins. They should only contain files when they are required so we should keep them around.
> Do not delete extensions and plugins directories with ruby/clean

- pkg/build/pipelines/strip.yaml
This preserves the symbol table, allowing tools like addr2line to work, while still stripping the raw debugging information.
> pipelines: strip: use -g by default when stripping

- pkg/linter/linter.go
The tempfile needs to be closed.
> strip linter: properly close tempfile

- docs/LINTER.md
This is useful for packagers to know when they should turn off a linter, and when to do so.
> Add section to linter docs about disabling linters

- .github/PULL_REQUEST_TEMPLATE.md
This introduces a PR checklist to `melange` to remind folks that being able to rebuild Wolfi is the primary feature of `melange`, and that changes shouldn't be make that risk our ability to keep building Wolfi successfully.
> Add a PR checklist to melange.

- docs/md/melange_build.md
- pkg/build/build.go
- pkg/cli/build.go
- pkg/linter/linter.go
- pkg/linter/linter_test.go
This also adds the flag `--fail-on-lint-warning` to force all active linters to error instead of simply printing their message.
Notes:
All linters are now warn-only.
- [N/A] Examining several representative APKs show no regression / the desired effect (details in notes)
Notes:
This doesn't touch APK generation at all.
Notes:
All checks are warnings.
> Enable linters to warn (via callback) instead of just failing.

- NEWS.md
the full list of changes is available on the release page [here](https://github.com/chainguard-dev/melange/releases/tag/v0.5.0) 
I did a pass and only included "user" facing changes, namely I filtered out:
- dependency bumps
- docs
- follow up PRs fixing nits
> update with 0.5.0 changes

- pkg/build/package.go
- pkg/config/config.go
If we discover a vendored dependency (outside of libdirs), we will use that to self-satisfy any generated runtime dependencies. Notably, we will not use these vendored dependencies to satisfy any explicitly configured runtime dependencies so that we have an escape hatch for overriding the SCA.
This also adds `# vendored = ...` comments to .PKGINFO so that we can debug cases that would otherwise appear as a missing runtime dependency.
(Draft for now because I would like to do a dry run of this new logic against existing packages to see if there are any unexpected diffs.)
> Track vendored deps for .PKGINFO

- pkg/linter/linter.go
It's `.PKGINFO` not `PKGINFO` 😅
> linter: fix a typo in package linting function

- pkg/config/config.go
- pkg/config/config_test.go
Fix a bug where substitutions were not done for `runtime`.
Notes:
Notes:
Notes:
> Fix a bug where substitutions were not done for runtime.

- pkg/convert/python/python.go
- pkg/convert/python/python_test.go
- replace the fetch python url to more friendly URI
per @rawlingsj comments (https://github.com/wolfi-dev/os/pull/6936#discussion_r1361716083)
we can replace the release url to this format:
```
https://files.pythonhosted.org/packages/FIRST_CHAR_OF_PACKAGE_NAME/PACKAGE_NAME/PACKAGE_NAME-${{package.version}}.tar.gz
```
tested that with a bunch of packages and all matched, so this PR replace the URL with the sha with one that is a bit more friendly
Notes:
Notes:
Notes:
> replace the fetch python url to more friendly URI

- pkg/build/build.go
- pkg/sbom/implementation.go
- pkg/util/env.go
- pkg/util/env_test.go
Before we could get into weird situations where `SOURCE_DATE_EPOCH=""` particularly with Makefiles doing conditional setting. os.LookupEnv will treat "" as the env being set (https://go.dev/play/p/sOI08BfjdhV) which means that we can get inconsistent behavior where the melanage build will default SOURCE_DATE_EPOCH to 0, but the SBOM generation would not.
This consolidates the parsing behavior so we are consistent everywhere we are parsing the environment var.
Notes:
Notes:
Notes:
> Centralize SOURCE_DATE_EPOCH parsing.

- pkg/linter/defaults/defaults.go
- pkg/linter/linter.go
- pkg/linter/linter_test.go
Take two after resolving git issues.
This implements a lint checking if a package contains multiple Python packages.
It's rather simplistic at the moment but I think this should get the job done.
> Add multiple Python packages post-linter

- pkg/renovate/bump/bump.go
- pkg/renovate/bump/bump_test.go
This can happen when an upstream deletes a tag and re-uses it with a different commit, so we need to bump the epoch rather than reset it. Example https://github.com/wolfi-dev/os/pull/6126/commits/4a7ae4002985401afaab03b50f9cff8073462ec8
If there are no version or expected commit changes we still expect the epoch to be bumped
> melange bump: only reset the epoch if version changes, else increment it

- pkg/linter/defaults/defaults.go
- pkg/linter/linter.go
- pkg/linter/linter_test.go
This checks if a doc or docs "package" was left in site-packages. This seems to be a recurring issue, so let's make a lint for it.
Fixes #778
Notes:
> Add Python docs linter

- pkg/build/readlinkfs.go
Packages built on a host with selinux enabled will inherit filesytem xattr labels from the host and result in 'operation not permitted' errors when installed in an unpriv'd docker container.
fixes #787
Notes:
Notes:
Notes:
> readlinkfs: ignore security.selinux xattrs

- pkg/linter/defaults/defaults.go
- pkg/linter/linter.go
- pkg/linter/linter_test.go
This checks if tests are in the Python site-packages directory. This has been encountered in the wild.
> Add python/test linter

- pkg/config/config.go
This mirrors https://github.com/chainguard-dev/apko/pull/933 to add json tags.
Notes:
Notes:
Notes:
> Add json tags to melange Configuration.

- pkg/build/build.go
- pkg/cli/lint.go
- pkg/config/config.go
- pkg/linter/defaults/defaults.go
- pkg/linter/linter.go
- pkg/linter/linter_test.go
This ensures a package won't write to the SBOM directory inadvertently.
> Add SBOM linter

- examples/npm-install.yaml
- pkg/build/pipelines/npm/install.yaml
This PR adds an `npm/install` pipeline supporting overrides.
Notes:
> pipelines: add npm-install pipeline

- pkg/linter/defaults/defaults.go
- pkg/linter/linter.go
- pkg/linter/linter_test.go
The documentation linter checks for the presence of documentation files in non-documentation packages.
The object linter checks for the presence of intermediate object files in the generated packages.
Notes:
No breaking changes
Notes:
No breaking changes
Notes:
> Add linters for documentation and object files

- pkg/config/config_test.go
Related to #603, which seems to be fixed
Notes:
This is a change to tests
Notes:
This is a change to tests that aren't related to SCA
Notes:
This will not affect linting.
> Add a test to ensure that ranges are handled properly.

- pkg/linter/linter.go
Instead of attempting every file, only try to parse files that start with the ELF magic header.
Rebase of https://github.com/chainguard-dev/melange/pull/803 onto https://github.com/chainguard-dev/melange/pull/810
> Filter out noise opening non-ELF files

- pkg/build/package.go
- pkg/build/pipeline.go
- pkg/util/util.go
- pkg/util/util_test.go
`slices.Compact` requires the input to be sorted in order to deduplicate the list.
> Fix deduplication of strings because slices.Compact doesn't sort the input

- pkg/build/build.go
- pkg/build/pipeline.go
- pkg/build/pipeline_test.go
Some of these constructors are redundant and/or have error return types that don't ever actually return an error.
> Remove impossible errors

- pkg/build/build_test.go
- pkg/build/testdata/configuration_load/uses-and-runs.melange.yaml
- pkg/config/config.go
We ignore "runs" if "uses" is present, so specifying both should fail.
> Error early if uses and runs are both present

- pkg/build/testdata/configuration_load/with-and-runs.melange.yaml
- pkg/config/config.go
`with` has no effect in this case, so it's likely a bug to specify it.
There's one example of this in Wolfi, which I'm cleaning up in https://github.com/wolfi-dev/os/pull/8067
(This PR is draft until that PR is merged)
> fail if 'with' is used with 'runs'

- pkg/build/build.go
- pkg/config/config.go
- pkg/sbom/generator.go
- pkg/sbom/implementation.go
This indirection isn't used to test anything, and all the generator options are hardcoded. Some of the methods that don't do anything were also removed and the corresponding sbom config removed because it's misleading.
I've kept NewGenerator around to hold the same logger across calls to GenerateSBOM.
> Delete no-op sbom code

- pkg/build/build.go
I don't think the per-package check configs were working because these weren't plumbed.
> Plumb check configs through to linters

- pkg/config/config_test.go
This adds a small bit of testing to demonstrate that `${{package.version}}` is replaced in runtime deps for packages and subpackages.
> test runtime replacements

- pkg/convert/python/python.go
- pkg/convert/python/python_test.go
- don't specify `python-3` or `py3.12-setuptools` since they get picked up by the dep on `python/build-wheel` automagically (I don't think we actually need a dep on `setuptools`?)
- drop `repositories` and `keyring` since we don't need them in wolfi (we pass them in via flags to `melange build`)
- drop manual `README` step since running the pipeline checks the digest for you
> improve 'melange convert python' to remove manual steps

- docs/md/melange_build.md
- pkg/cli/build.go
The value of `GetDefaultRunner` is environment-dependent, which can lead to confusion when the environment used to generate docs produces docs that claim a different default.
This is not expected to have any behavior change.
> fix docs for --runner

- docs/md/melange_convert.md
- docs/md/melange_convert_apkbuild.md
- docs/md/melange_convert_gem.md
- docs/md/melange_convert_python.md
- pkg/cli/convert.go
- pkg/convert/python/python.go
This bails early before re-generating a melange config if we already have it.
We still crawl the package's deps in case we need to, but we won't overwrite existing files.
This also updates `-o` to default to the pwd, which is normally the wolfi-dev/os repo, where files generally already exist.
Ideally this _would_ overwrite the config if it could determine it had originally been generated and hadn't been updated since. This would let us account for package updates that bring in new runtime deps, if `melange convert` was integrated in the update/renovate workflow. In that case, we can workaround by deleting the file and regenerating it.
> convert python: don't overwrite existing files

- docs/md/melange_convert.md
- docs/md/melange_convert_apkbuild.md
- docs/md/melange_convert_gem.md
- docs/md/melange_convert_python.md
- pkg/cli/convert.go
- pkg/cli/python.go
- pkg/convert/python/python.go
This only does anything interesting for `melange convert python` but this opts us in to using `git-checkout` instead of `fetch`.
Also drop some unnecessary additions to the package.
> default --use-github=true

- go.mod
- go.sum
- internal/gen-jsonschema/generate.go
- internal/gen-jsonschema/main.go
- pkg/config/config.go
- pkg/config/schema.json
Mirrors https://github.com/chainguard-dev/apko/pull/964 for melange config types.
> Add jsonschema generation binary.

- pkg/linter/linter.go
- pkg/linter/linter_test.go
Fix the linter warnings. Left one about stuttering include, as we can fix that if we want to or silence it.
Notes:
Notes:
Notes:
> Fix the lint warnings in pkg/linter

- docs/md/melange_build.md
- examples/simple-hello/melange.yaml
- pkg/build/build.go
- pkg/cli/build.go
- pkg/config/config.go
- pkg/container/config.go
- pkg/container/docker_runner.go
- pkg/container/kubernetes_runner.go
- pkg/container/kubernetes_runner_test.go
- pkg/util/env.go
This adds config values and flags to configure resource requests and timeouts for build pipelines.
```
package:
name: hello
...
resources:
cpu: .5
memory: 128Mi
```
This is used by the docker and k8s runners to start containers with these requests. This also adds flags that override these values on a per-run basis:
```
melange build hello.yaml --cpu=10 --memory=40Gi
```
For the k8s runner only, if no resources are requested, it defaults to 2 CPU and 4 Gi to satisfy GKE autopilot requirements.
Likewise, this adds a `timeout:` field and `--timeout` flag, which enforces a build pipeline timeout (NB: time to fetch packages and setup the environment is not counted in this timeout, only the build steps)
```
$ melange build examples/simple-hello/melange.yaml --timeout=1s
2023/12/01 10:23:42 …
```
> support resource requests and timeouts

- .github/workflows/melange-test-pipelines.yaml
- docs/TESTING.md
- docs/md/melange.md
- docs/md/melange_test.md
- e2e-tests/php-8.2-msgpack-test.yaml
- e2e-tests/py3-pandas-test.yaml
- e2e-tests/test-fixtures/py3-pandas-test.py
- pkg/build/build.go
- pkg/build/pipeline.go
- pkg/build/pipeline_test.go
- pkg/build/test.go
- pkg/build/test_test.go
- pkg/build/testdata/test_configuration_load/py3-pandas.melange.yaml
- pkg/build/testdata/test_configuration_load/range-subpackages.melange.yaml
- pkg/cli/build.go
- pkg/cli/commands.go
- pkg/cli/test.go
- pkg/config/config.go
Example test file that I've been playing with
https://gist.github.com/vaikas/b2cf4d96b7601bdccf39a2b34bcc0dc2
Notes:
Notes:
Notes:
> Add Test pipelines

- pkg/cli/apkbuild.go
- pkg/cli/gem.go
- pkg/cli/python.go
- pkg/config/vars.go
- pkg/convert/apkbuild/apkbuild.go
- pkg/convert/gem/gem.go
- pkg/convert/python/pypi.go
- pkg/convert/relmon/release_monitoring.go
- pkg/convert/wolfios/wolfi-os.go
- pkg/http/http.go
- pkg/manifest/manifest.go
https://github.com/pkg/errors is deprecated and archived for more than two years, since `fmt.Errorf` added support for `%w` in Go 1.13, [~three years ago](https://go.dev/blog/go1.13-errors).
This removes our usage of `pkg/errors` using this analyzer: https://github.com/zchee/go-analyzer/tree/main/pkgerrors
> cleanup: don't use pkg/errors

- go.mod
- go.sum
> Pull in `go-apk` with `provider_priority` `ini` fix.

- pkg/build/build_test.go
- pkg/build/pipelines/go/build.yaml
- pkg/config/config.go
Melange supports a filesystem based cache, but it's not used anywhere AFAICT. To use it for Go, we've documented how to set this env var. Instead of making everyone set it in every pipeline and build, let's just set it to the correct path by default in melange itself.
This dramatically improves build times for me.
Notes:
> Set a default env var for GOMODCACHE.

- pkg/build/pipelines/git-checkout.yaml
This avoids log spam like this:
```
⚠️  aarch64   | Cloning into '/tmp/tmp.Dvzsqj'...
⚠️  aarch64   | Note: switching to 'ec85d900b413d3d9d6f60cece3fb5bc665275087'.
⚠️  aarch64   | 
⚠️  aarch64   | You are in 'detached HEAD' state. You can look around, make experimental
⚠️  aarch64   | changes and commit them, and you can discard any commits you make in this
⚠️  aarch64   | state without impacting any branches by switching back to a branch.
⚠️  aarch64   | 
⚠️  aarch64   | If you want to create a new branch to retain commits you create, you may
⚠️  aarch64   | do so (now or later) by using -c with the switch command. Example:
⚠️  aarch64   | 
⚠️  aarch64   |   git switch -c <new-branch-name>
⚠️  aarch64   | 
⚠️  aarch64   | Or undo this operation with:
⚠️  aarch64   | 
⚠️  aarch64   | …
```
> Bypass warning about detached head

- pkg/test/pipelines/python/test.yaml
Example usage (tested locally):
```
test:
pipeline:
- uses: python/test
with:
command: python -c "import azure.cosmos"
```
Notes:
Notes:
Notes:
> Add a python/test pipeline.

- pkg/build/pipelines/meson/configure.yaml
https://mesonbuild.com/Subprojects.html#commandline-options
> * **--wrap-mode=nodownload**
> Meson will not use the network to download any subprojects or fetch any wrap information. Only preexisting sources will be used. This is useful (mostly for distros) when you want to only use the sources provided by a software release, and want to manually handle or provide missing dependencies.
> meson/configure: don't download subprojects by default

- pkg/build/pipelines/split/dev.yaml
This will aid in developing mysql package `-dev` variants. MySQL ships with `mysql_config` for its pkgconfig-style tool.
Notes:
Notes:
Notes:
> add `*_config` pattern to split/dev pipeline

- .github/workflows/melange-test-pipelines.yaml
- docs/TESTING.md
- docs/md/melange_test.md
- e2e-tests/php-8.2-msgpack-nopkg-test.yaml
- e2e-tests/py3-pandas-nopkg-test.yaml
- pkg/build/test.go
- pkg/cli/test.go
Add a new flag `--test-package-append` that allows you to omit specifying packages in the `yaml` file, and instead specify
them from the command line. They are handy if you have a common package that all tests require so that you don't have
to keep specifying them in your yaml.
Notes:
Notes:
Notes:
> Add --test-package-append that you can specify extra test packages for each test.

- pkg/index/index.go
- pkg/index/index_test.go
I believe this is the source of a lot of confusion around the development process where rebuilding a package with the same version and epoch would appear to do nothing because the APKINDEX wasn't getting updated.
The code before looks like it wants to do this, but assigning to the loop variable is ineffectual. This change fixes that ineffectual assignment to actually overwrite the existing package.
Hopefully this removes a point of friction in local development where folks have been nuking caches in attempts to work around this bug.
> Replace packages in APKINDEX with same version

- pkg/sca/sca.go
- pkg/sca/sca_test.go
Fixes https://github.com/chainguard-dev/melange/issues/920
There are not many shared objects that do this, but it does happen, and checking for ".so." is a little more better than looking for "libc" if we want this to work for any execable shared object (like libcap.so.2).
Notes:
```
tar -Oxf packages/aarch64/libcap-2.69-r2.apk .PKGINFO
pkgname = libcap
pkgver = 2.69-r2
arch = aarch64
size = 148643
origin = libcap
pkgdesc = POSIX 1003.1e capabilities
url =
commit = a474f16f202c5672a94c7fac31b7d671f6808908
builddate = 1705015782
license = BSD-3-Clause OR GPL-2.0-only
depend = so:ld-linux-aarch64.so.1
depend = so:libc.so.6
provides = so:libcap.so.2=2
provides = so:libpsx.so.2=2
datahash = ca1db049dc00c838fe2d168fa44cdebeb11f2e42d5e6007f5b76e76f079abe14
```
Looking at `glibc` to make sure I …
> Allow execable shared objects if name has ".so."

- pkg/config/config.go
This was promoted from an Info here: https://github.com/chainguard-dev/melange/commit/6d6fdc0225094a4a86a9e0cd7346c1f3e70af8bb#diff-a3d824da3c42420cd5cbb0a4a2c0e7b5bfddd819652788a0596d195dc6e31fa5R565
But it's not that useful, especially when parsing lots and lots and lots of configs from the same git-commit-less filesystem.
> Make "unable to detect git commit" a debug message

- pkg/build/pipeline.go
- pkg/build/pipeline_test.go
- pkg/build/pipelines/autoconf/configure.yaml
- pkg/cond/subst.go
Tested this with this diff to crane.yaml:
```
diff --git a/crane.yaml b/crane.yaml
index 3f5c32dc2..9d458809f 100644
--- a/crane.yaml
+++ b/crane.yaml
@@ -1,13 +1,15 @@
package:
name: crane
version: 0.18.0
-  epoch: 0
+  epoch: 1
description: Tool for interacting with remote images and registries.
copyright:
- license: Apache-2.0
dependencies:
runtime:
- ca-certificates-bundle
+    provides:
+      - foo=${{package.fullversion}}
environment:
contents:
```
```
ℹ️            | error during command execution: failed to apply replacement to provides "foo=${{package.fullversion}}": variable package.fullversion not defined
```
> Fail if unknown variable is used in substitution

- pkg/build/pipeline.go
Before (recent release)
```
ℹ️  aarch64   | running pipeline for subpackage containerd-stress
❕ aarch64   |     ${{targets.contextdir}}: /home/build/melange-out/containerd-stress
❕ aarch64   |     ${{targets.package.ctr}}: /home/build/melange-out/ctr
❕ aarch64   |     ${{cross.triplet.gnu.musl}}: aarch64-unknown-linux-musl
❕ aarch64   |     ${{targets.subpkgdir}}: /home/build/melange-out/containerd-stress
❕ aarch64   |     ${{targets.package.containerd-shim-runc-v1}}: /home/build/melange-out/containerd-shim-runc-v1
❕ aarch64   |     ${{package.epoch}}: 3
❕ aarch64   |     ${{targets.destdir}}: /home/build/melange-out/containerd
❕ aarch64   |     ${{targets.package.containerd}}: /home/build/melange-out/containerd
...
```
After (including clog improvements)
```
ℹ️  aarch64   | running step …
```
> sort with key/values

- pkg/sbom/generator.go
- pkg/sbom/implementation.go
These aren't called outside of this package, and exposing implementation details like this can make future refactorings harder.
> unexport some methods in pkg/sbom

- examples/one-arch.yaml
- pkg/build/test.go
If you `melange build` a package for one arch, it should not cause an error to `melange test` that package on a different arch -- it shouldn't even care that the package to test doesn't exist.
Tested with:
```
$ go run ./ build examples/one-arch.yaml
$ go run ./ test examples/one-arch.yaml  ./packages/x86_64/one-arch-0.0.1-r0.apk --arch=x86_64
$ go run ./ test examples/one-arch.yaml  ./packages/x86_64/one-arch-0.0.1-r0.apk --arch=aarch64              
⚠️            | skipping test for one-arch on arm64
$ go run ./ test examples/one-arch.yaml  ./packages/armv7/one-arch-0.0.1-r0.apk --arch=aarch64
⚠️            | skipping test for one-arch on arm64
```
> test: skip when executing on an unsupported arch

- pkg/build/test.go
When we create the container, the build environment ENV variables are used instead of the ones from the test.environment.environment.
Notes:
Notes:
Notes:
> Pass the correct env.env to the container.

- pkg/container/docker_runner.go
- pkg/container/kubernetes_runner.go
- pkg/container/monitor_pipe.go
- pkg/container/runner.go
For some reason we were using os.Pipe instead of io.Pipe for an in-process pipe. I've switched those over to using io.Pipe so we can CloseWithError.
Also, switched to using errgroup.Group instead of manual channel signaling.
Now, when we hit an error, we actually log that error instead of the line just before that error.
> Fix race condition in log monitoring

- pkg/build/build.go
- pkg/build/test.go
- pkg/cli/build.go
- pkg/cli/test.go
- pkg/container/bubblewrap_runner.go
- pkg/container/docker_runner.go
- pkg/container/kubernetes_runner.go
- pkg/container/runner.go
We were doing some needless RPCs to the docker daemon because we reconstruct a new client every time.
Instead, construct a client once and close it in a Close() method. Plumb Close() methods up through to melange build/test as well.
> Add Close() method to container runners

- pkg/container/bubblewrap_runner.go
- pkg/container/docker_runner.go
- pkg/container/kubernetes_runner.go
- pkg/container/monitor_pipe.go
- pkg/container/runner.go
This is racey and silly because a log function is closer to a writer than it is to a reader, so using a pipe doesn't make sense. We can just turn a writer into a log function.
> Don't use goroutines for monitoring logs

- pkg/container/docker_runner.go
- pkg/container/monitor_pipe.go
Since StdCopy is a blocking call, even if ctx is cancelled, we won't actually clean up any containers. This ~fixes that.
This isn't a complete solution, but it's really straightfoward to implement, so I'm starting here. This only works when logs are being actively streamed (so we are actually calling Read). If the container isn't very chatty, this isn't as effective.
This is harmless to keep in, but we can also remove it when we have a better solution.
> Respond to cancelled context while streaming logs

- docs/md/melange_build.md
- pkg/build/build.go
- pkg/cli/build.go
- pkg/container/bubblewrap_runner.go
- pkg/container/docker_runner.go
- pkg/container/kubernetes_runner.go
- pkg/container/runner.go
This instructs melange to clean up after itself. Currently, this only applies to the guest container image, but we can expand the scope over time.
Sample output:
```
ℹ️  aarch64   | wrote packages/aarch64/crane-0.19.0-r0.apk
ℹ️  aarch64   | generating apk index from packages in packages/aarch64
ℹ️  aarch64   | processing package packages/aarch64/crane-0.19.0-r0.apk
ℹ️  aarch64   | updating index at packages/aarch64/APKINDEX.tar.gz with new packages: [crane-0.19.0-r0]
ℹ️  aarch64   | signing apk index at packages/aarch64/APKINDEX.tar.gz
ℹ️            | signing index packages/aarch64/APKINDEX.tar.gz with key local-melange.rsa
ℹ️            | appending signature to index packages/aarch64/APKINDEX.tar.gz
ℹ️            | writing signed index to packages/aarch64/APKINDEX.tar.gz
ℹ️            | …
```
> Add --rm flag (and options) to Build

- main.go
This gives melange a chance to clean up processes and images.
> Cancel context on interrupt signal

- pkg/container/bubblewrap_runner.go
This prevents us from failing when background processes have not exited.
> Add --die-with-parent to bwrap flags

- pkg/build/pipelines/go/build.yaml
- pkg/build/pipelines/go/install.yaml
This PR adds support for the optional [GOEXPERIMENT](https://pkg.go.dev/internal/goexperiment) environment variable in the `go/build` and `go/install` pipelines which can tweak the behavior of various Golang features, ex: [Fixing For Loops in Go 1.22](https://go.dev/blog/loopvar-preview).
> feat: GOEXPERIMENT support to go/build and go/install pipelines

- examples/go-build.yaml
This example had been broken because the `git checkout` didn't happen inside the directory that we cloned into.
> fix go-build example

- docs/md/melange_build.md
- docs/md/melange_test.md
- go.mod
- go.sum
- pkg/build/build.go
- pkg/build/options.go
- pkg/build/pipeline.go
- pkg/build/test.go
- pkg/build/test_options.go
- pkg/cli/build.go
- pkg/cli/test.go
- pkg/container/bubblewrap_runner.go
- pkg/container/docker_runner.go
- pkg/container/kubernetes_runner.go
- pkg/container/monitor_pipe.go
- pkg/container/runner.go
This introduces a new --interactive/-i flag that, if set, will drop you into an interactive tty with the melange build. This allows you to inspect the state of the filesystem and poke around.
> Make debugging melange builds less terrible

- pkg/build/build.go
- pkg/build/options.go
- pkg/build/runner.go
- pkg/build/test.go
- pkg/build/test_options.go
- pkg/cli/build.go
- pkg/cli/test.go
This should mean that callers that depend on `pkg/build` (like wolfictl) won't necessarily have to depend on k8s libraries, making their builds slower.
We may also need to move the runner implementations into separate subpackages in `pkg/container`, we can investigate that separately.
> move runner determination to pkg/cli

- pkg/build/pipeline.go
- pkg/container/bubblewrap_runner.go
If you exit the session with an error (e.g. "exit 1"), we will abort the pipeline.
If instead you type "exit 0" from within the pod, we will exit that build step and continue with the rest of the build or test.
Note that hitting ctrl+C will cancel the root context and cause things to exit no matter what. This is a bug, and we now log that caveat.
> Continue interactive execution on exit 0

- pkg/build/build.go
This adds WorkspaceDir to the Close() method and also guards against nil panic when cleaning up images.
> Do more cleanup with --rm

- internal/contextreader/contextreader.go
- internal/logwriter/logwriter.go
- pkg/cli/build.go
- pkg/container/bubblewrap_runner.go
- pkg/container/docker/docker_runner.go
- pkg/container/k8s/kubernetes_runner.go
- pkg/container/k8s/kubernetes_runner_test.go
- pkg/container/runner.go
Two new internal packages: contextreader and logwriter, both of which are independently useful and probably worth publishing as non-internal.
Two new public packages: k8s and docker.
Both docker and k8s are huge dependencies, so we owe it to our users (and ourselves) to make them optional.
> Split pkg/container up into smaller packages

- pkg/config/config.go
- pkg/config/config_test.go
This looks like an oversight. I don't love how this code works but I'm favoring consistency over introducing a larger diff.
> Allow substitutions in dependencies.replaces

- pkg/build/build.go
- pkg/build/pipeline.go
The cleanup step would fail if we called RemoveImage with a cancelled context. This fixes that.
> Remove images even with cancelled ctx

- docs/md/melange_build.md
- pkg/build/build.go
- pkg/build/options.go
- pkg/build/pipeline.go
- pkg/cli/build.go
The `--interactive` flag should be a suitable replacement for this.
Fixes https://github.com/chainguard-dev/melange/issues/1023
> Remove breakpoint labels

- pkg/cli/build.go
When building a single arch, we don't have to log the arch.
Before:
```
go run ./ build examples/minimal.yaml --arch=aarch64      
2024/02/13 19:27:12 INFO melange is building: arch=aarch64
2024/02/13 19:27:12 INFO   configuration file: examples/minimal.yaml arch=aarch64
2024/02/13 19:27:12 INFO   workspace dir: /var/folders/gw/86t1jg2109s5j8vzszj281kc0000gn/T/melange-workspace-1982439457 arch=aarch64
2024/02/13 19:27:12 INFO evaluating pipelines for package requirements arch=aarch64
2024/02/13 19:27:12 INFO populating workspace /var/folders/gw/86t1jg2109s5j8vzszj281kc0000gn/T/melange-workspace-1982439457 from examples arch=aarch64
2024/02/13 19:27:12 INFO --cache-dir ./melange-cache/ not a dir; skipping arch=aarch64
```
After:
```
go run ./ build examples/minimal.yaml --arch=aarch64 …
```
> omit arch log key when building one arch

- docs/md/melange_build.md
- go.mod
- go.sum
- pkg/cli/build.go
We could do this globally but I'm going to add this here for now as an experiment. This takes a filename and writes an otel JSON trace to it.
> Add a --trace flag to melange build

- pkg/container/docker/docker_runner.go
simple change to attach labels to containers created with melange's docker runner.
this makes it easier for external management for things like cleanup:
```
docker rm -f $(docker ps -q --filter "label=melange=true")
```
I'm not married to the label, feel free to suggest others!
> label containers created by docker runner for easier external management

- pkg/container/docker/docker_runner.go
follow on to #1028.
keeps the `melange=true` for general use, but also adds a package name
> add package name to docker labels

- docs/md/melange_build.md
- pkg/build/build.go
- pkg/build/options.go
- pkg/build/test.go
- pkg/cli/build.go
This passes through any additional packages to add to the guest environment for builds.
Mostly, this is useful when combined with --interactive so that you can add e.g. "apk-tools" to the build environment without having to modify the build file.
> Add --package-append flag to build

- pkg/build/pipelines/python/import.yaml
> Fix the yaml file so that it actually gets parsed properly. Details matter!

- internal/contextreader/contextreader.go
- pkg/container/docker/docker_runner.go
Apparently `for { select { break } }` doesn't do what I thought.
This cleans up orphaned goroutines after the reader is done.
> Fix resource usage in melange

- pkg/build/pipelines/maven/pombump.yaml
Tested on spark image with:
```
- uses: maven/pombump
with:
debug: true
```
and just:
```
- uses: maven/pombump
```
Notes:
Notes:
Notes:
> Add pombump pipeline.

- pkg/build/pipeline.go
- pkg/config/vars.go
Unlike host.triplet.rust, these use hardcoded values for the libc flavor, which removes the need for trying to detect this at runtime.
See https://github.com/chainguard-dev/melange/issues/1056
We can migrate to these at our leisure, but we will want to figure out what to do with host.triplet.* substitutions to avoid breaking anyone using them.
> Add ${{cross.triplet.rust.[glibc,musl]}}

- pkg/container/bubblewrap_runner.go
I think --die-with-parent might have fixed this for us.
> Drop WaitDelay from bubblewrap

- pkg/config/config.go
- pkg/config/schema.json
the default for the jsonschema we use calls this `test.Environment`, but the schema itself is actually `test.environment`
> fix test.environment jsonschema struct tag

- docs/PIPELINES-CARGO.md
- examples/cargo-build.yaml
- pkg/build/pipelines/cargo/build.yaml
Produces and installs an auditable rust binary with an embedded dependency tree in its own dedicated linker section in JSON format. This simplifies the packaging processes for rust packages and ensures that all rust binaries we build are able to be audited for bugs/vulnerabilities in crates fetched during the build process
Notes:
Notes:
Notes:
> feat(pipelines): Add cargo build for rust packages

- pkg/build/pipeline.go
simple qol change to drop the user in the specified pipeline step workdir when `--interactive` is toggled.
by default this is `/home/build`, but when the pipeline step specifies `working-dir`, that is now respected
> open debug session in the specific workdir

- pkg/container/bubblewrap_runner.go
This currently spams a ton of logs which aren't terribly helpful unless you're debugging something:
```
2024/03/13 13:49:06 INFO executing: bwrap --bind /tmp/melange-guest-712322663 / --bind /tmp/melange-workspace-1734788743 /home/build --bind /etc/resolv.conf /etc/resolv.conf --bind /gihtub/.melangecache /var/cache/melange --unshare-pid --die-with-parent --dev /dev --proc /proc --chdir /home/build --clearenv --new-session --setenv GOMODCACHE /var/cache/melange/gomodcache --setenv CFLAGS -O2 -Wall -fomit-frame-pointer -march=armv8-a+crc+crypto -mtune=neoverse-n1 --setenv SOURCE_DATE_EPOCH 0 --setenv LDFLAGS -Wl,--as-needed,-O1,--sort-common -Wl,-z,relro,-z,now,-z,noexecstack --setenv GOPATH /home/build/.cache/go --setenv GOTOOLCHAIN local --setenv CPPFLAGS -O2 -Wp,-D_FORTIFY_SOURCE=3 …
```
> Move "executing:" logging to debug

- pkg/build/build.go
- pkg/build/test.go
- pkg/build/test_test.go
- pkg/container/bubblewrap_runner.go
- pkg/container/config.go
- pkg/container/docker/docker_runner.go
This works for both build and test, but will probably be harder to make work with builds because of file ownership shenanigans. For tests, this makes it possible to test non-root users for packages that get mad if you run them as root.
> Propagate user from image configuration

- pkg/container/dagger/dagger.go
- pkg/container/docker/docker_runner.go
we've been improperly mounting in the hosts `/etc/resolv.conf` forever, and have gotten away with it because some systems (docker desktop) works okay because the `nameserver` still resolves, but does not on others.
this ignores `/etc/resolv.conf` for the docker runner so we just fallback to letting docker manage its own `/etc/resolv.conf`
this should fix the `could not resolve host: ...` errors we've been seeing in GHA everytime we try to migrate to `--runner docker`
> skip mounting resolv.conf for the docker runner

- pkg/build/pipelines/go/build.yaml
- pkg/build/pipelines/go/install.yaml
Improve go pipelines:
- default to higher microarchitecture level on amd64 to match Wolfi C/C++ -march=x86-64-v2
- default to current microarchitecture level on arm64 to match what golang does today v8.0 (no effective change, but gives us a toggle to be able to raise it in the future)
- strip DWARF debug information by default
- strip symbols table information by default
* unless go-package is fips
- trimpath in go/install pipeline by default
- by default opt into go build tags osusergo and netgo, meaning whilst we can keep implicit default of CGO_ENABLED=1 all binaries (when possible and don't otherwise use cgo) are compiled statically linked
- but when using go-fips toolchain, or have any other cgo features those are automatically used
This reduces go binaries size significantly, those …
> Better go pipelines

- .github/workflows/go-tests.yaml
- Makefile
- pkg/sca/sca.go
- pkg/sca/sca_test.go
- pkg/sca/testdata/go-fips-bin/go-fips-bin.yaml
- pkg/sca/testdata/go-fips-bin/go.mod
- pkg/sca/testdata/go-fips-bin/main.go
Automatically generate runtime deps for go binaries that smell like go-fips ones. Specifically check if CGO is on, and boringcrypto experiment is on, and in that case generate runtime dependencies on openssl libraries, fips config, and fips provider.
This will reduce number of by-hand declared runtime dependencies on the go-fips compiled binaries.
It reduces manually specified runtime dependencies in many golang based -fips packages.
Notes:
The `openssl-config-fipshardened` is Chainguard-specific, however in practice it means "anything that will get one correctly configured OpenSSL fips provider" with no restriction as to which OpenSSL it is, or which fips provider build it is. Non-chainguard APK distributions can call that thing whatever they want, and add a virtual providers for it.
If …
> Go fips deps

- pkg/config/config.go
Currently the configuration file is opened but never closed. While it will be closed implicitly when the file is garbage collected, best practice would be to close the file when the function returns.
> Ensure configuration file is closed

- go.mod
- go.sum
- pkg/container/docker/docker_runner.go
```
Error: SA1019: types.ImageRemoveOptions is deprecated: use [image.RemoveOptions].  (staticcheck)
```
> cleanup: update docker dep, stop using deprecated method

- .github/workflows/wolfi-presubmit.yaml
This build seems to be broken, and shouldn't block melange presubmit
> presubmit: remove gdk-pixbuf

- .github/workflows/wolfi-presubmit.yaml
Reverts chainguard-dev/melange#1143
This package should build now, and it's a required check.
> Revert "presubmit: remove gdk-pixbuf"

- pkg/config/config.go
- pkg/config/schema.json
This allows to create subpackages with dynamic scriplets, which take range key/value subsitutions just like other subapckage values.
Example fun usage shown in https://github.com/xnox/os/commit/3a964132ebe26225b8510ec2875b506a8e617633
```yaml
scriptlets:
post-install: |
#!/usr/bin/python${{range.key}}
import glob, shutil
for b in glob.glob("/usr/pybin/${{range.key}}/*"): shutil.copy2(b, "/usr/bin/")
```
```console
bb6225aab2ee:/# head -n1 /usr/bin/pip
#!/usr/bin/python3.10
bb6225aab2ee:/# apk add py3.11-pip
(1/4) Installing python-3.11-base (3.11.9-r0)
(2/4) Installing py3.11-flit-core (3.9.0-r2)
(3/4) Installing py3.11-setuptools (69.5.1-r1)
(4/4) Installing py3.11-pip (24.0-r2)
Executing py3.11-pip-24.0-r2.post-install
OK: 140 MiB in 35 packages
bb6225aab2ee:/# head -n1 /usr/bin/pip …
```
> config: allow scriplets in subpackages with range replacements

- pkg/build/pipelines/cargo/build.yaml
Support installing multiple rust binaries after building them with cargo
Notes:
Notes:
Notes:
> fix(cargo): Install all built binaries if output isn't defined

- pkg/sca/sca.go
generateCmdProviders would pick up all files under /usr/bin, /bin, /usr/sbin, /sbin.  The result was that files installed in /usr/bin/subdir/here/some/thing would get marked as Provides.
Thsi was found in sqlpad-7.4.1-r3.apk, which installs things under usr/bin/sqlpad-server/ like
usr/bin/sqlpad-server/test/fixtures/config.json
Notes:
Notes:
Notes:
> Only consider that are in a PATH dir from generateCmdProviders

- pkg/sca/sca.go
Previously code that added automatic 'cmd:' provides ignored symlinks.  That doesn't seem right.
Possible fall out of this is busybox and /bin/sh related things as well as python -> python3 -> python3.12
Notes:
Notes:
Notes:
> Allow symlinks to provide cmd:

- pkg/sca/sca.go
Reverts chainguard-dev/melange#1188
> Revert "Allow symlinks to provide cmd:"

- Makefile
- pkg/convert/gem/gem.go
- pkg/convert/gem/gem_test.go
- pkg/convert/python/e2e_test.go
- pkg/convert/python/pypi.go
- pkg/convert/python/python_test.go
- pkg/convert/relmon/release_monitoring.go
- pkg/http/http.go
- pkg/sca/e2e_test.go
- pkg/sca/sca_test.go
I was flummoxed to find that `go test ./...` was both very slow and did not work. The very slowness comes from a couple sources. One is that we use a 1 QPS rate limiter in a lot of places, even when we are using an in-process http server to serve up testdata. I've removed those instances. In one particular python test, we are fetching a 10MB targz from the internet twice. I've gated that behind an `e2e` build tag, so to run that test you need to execute:
go test -tags e2e ./...
That's cumbersome, so I've added it to the `make test` target.
I've also added the `e2e` build tag to the go fips generated APK test because it requires you to first generate a binary before the test will pass. This is unacceptable to me, so the `make test` target will still test that, but `go test ./...` will not. …
> Make unit tests faster

- pkg/build/pipelines/go/build.yaml
This passes through -buildmode for e.g. c-shared targets.
> Add buildmode to go/build

- .github/workflows/e2e.yaml
- .github/workflows/wolfi-presubmit.yaml
- examples/git-checkout.yaml
- pkg/build/build.go
- pkg/build/pipeline.go
- pkg/build/pipelines/fetch.yaml
- pkg/sbom/bom.go
- pkg/sbom/generator.go
- pkg/sbom/implementation.go
External References to sources
=======
This aids with many aspects of compliance, and ability to self-locate all relevant source code.
This will be present in every package sbom, and by extension every image sbom accessible from console and container registry.
This is extensible to accommodate any other future inputs.
Current state:
=======
Currently we generate external self-reference to the binary APK package
```json
"externalRefs": [
{
"referenceCategory": "PACKAGE_MANAGER",
"referenceLocator": "pkg:apk/wolfi/acl@2.3.2-r2?arch=x86_64",
"referenceType": "purl"
}
]
```
This proposal extends this array with additional references to the source code.
For fetch:
=======
Add Package-URL to the download URI with checksum argument.
> 2024/05/17 16:18:51 INFO    adding external refs …
> sbom: include external refs for fetched sourcecode in SPDX

- pkg/config/config.go
- pkg/config/config_test.go
Fixes https://github.com/chainguard-dev/melange/issues/1236
We don't actually need range in pipelines AFAICT since we fixed the existing usages that would be broken by this change in other ways.
> Disallow duplicate subpackage names

- .github/workflows/wolfi-presubmit.yaml
wolfictl scan is very slow to start, and glibc has like a million subpackages, so the presubmit jumped from 15 to 30 minutes when we started wolfictl scanning every package.
> Speed up presubmit

- pkg/build/pipelines/go/build.yaml
Unused since ea789df (pipelines: use ${{targets.contextdir}} where it
makes sense, 2023-08-21)
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@surgut.co.uk>
> go/build: remove subpackage input

- pkg/build/pipelines/git-checkout.yaml
> Remove depth option from git clone if inputs.depth is set to -1

- pkg/config/config.go
- pkg/config/config_test.go
We should fail if you use ``with`` without ``uses``.
Example of where it should error out:
```
- uses:
with:
pom: management-api-agent-5.0.x/pom.xml
properties-file: pombump-properties-management-api-agent-5.0.x.yaml
```
> fix: error out when pipeline contains with but no uses

- pkg/build/test.go
This happens at the end of the loop (after we run the test) and is immediately deleted after the loop completes, so this seems to be a NOP.
> test: Drop seemingly useless mkdir -p

- docs/md/melange_build.md
- pkg/build/build.go
- pkg/build/options.go
- pkg/cli/build.go
This replaces the heuristic for `${{host.triplet.*}` substitutions, which relied on calling Stat() 2-4x in the guest dir for every pipeline executed.
See https://github.com/chainguard-dev/melange/issues/1056 for some more context.
In the fullness of time we'd like to remove these substitutions altogether, but for now let's just default to `gnu` which should make this a no-op for wolfi.
This is a breaking change for anyone using `melange` to build musl-based packages that also relies on the `${{host.triplet.*}}` substitutions. If that's you, I'm sorry. You can set `--override-host-triplet-libc-substitution-flavor musl` to override the default or use the `${{cross.triplet.*.*}}` substitutions instead.
> Add build flag to override host libc flavor

- docs/md/melange.md
- docs/md/melange_compile.md
- pkg/build/build.go
- pkg/build/compile.go
- pkg/build/package.go
- pkg/build/pipeline.go
- pkg/build/pipeline_test.go
- pkg/build/sca_interface.go
- pkg/build/test.go
- pkg/build/test_test.go
- pkg/cli/commands.go
- pkg/cli/compile.go
- pkg/cli/scan.go
- pkg/config/config.go
- pkg/convert/apkbuild/apkbuild.go
- pkg/linter/linter_test.go
- pkg/sbom/generator.go
- pkg/sca/sca_test.go
- pkg/util/map_subst.go
This also adds a compile subcommand to melange that outputs the fully rendered melange yaml as JSON to stdout for a build.
See https://github.com/chainguard-dev/melange/issues/1056
As an example, if you want to check that you've got the right mangled version for `jed.yaml`:
```yaml
package:
name: jed
version: 0.99.19
epoch: 0
var-transforms:
- from: ${{package.version}}
match: \.(\d+)$
replace: -$1
to: mangled-package-version
pipeline:
- uses: fetch
with:
uri: https://www.jedsoft.org/releases/jed/jed-${{vars.mangled-package-version}}.tar.gz
expected-sha256: 5eed5fede7a95f18b33b7b32cb71be9d509c6babc1483dd5c58b1a169f2bdf52
```
```
melange compile --pipeline-dir ./pipelines/ --arch x86_64 jed.yaml 2>/dev/null | jq '.pipeline[0].with'
{
"expected-sha256": …
```
> Separate compilation from execution

- pkg/build/compile.go
- pkg/build/pipeline.go
- pkg/build/pipeline_test.go
The purpose of this struct never really made any sense to me, and it got muddied a lot when we introduced build.Test, so drop it altogether.
Instead of plumbing a pb around everywhere so we can re-instantiate a substitution map every time we want to do anything, this creates a subtitution map up from based on the build/test configuration and passes it along, cloning and augmenting it for subpackages.
This should avoid generating a good amount of garbage maps, as well.
> Remove build.PipelineBuild as a concept

- pkg/cli/compile.go
```
Error: pkg/cli/compile.go:108:11: undefined: build.WithLogPolicy
```
> unbreak build at head from log policy removal

- pkg/build/pipeline.go
- pkg/build/pipeline_test.go
This is a big quality of life improvement for debugging broken builds.
> Populate history for --interactive builds

- pkg/build/pipelines/autoconf/configure.yaml
- pkg/convert/apkbuild/apkbuild.go
Verifies the absence of ./configure and that ./configure.ac is present before attempting to generate the configuration with autoreconf
Also - currently, autoconf and automake are added everywhere we utilize our autoconf pipelines. Just make them packages required by the autoconf/configure pipeline
Notes:
Notes:
Notes:
> chore(autoconf/configure): Generate configuration with autoreconf when configuration doesn't exist

- e2e-tests/test-git-checkout.yaml
- e2e-tests/test-git-checkout/create-git-repo
- pkg/build/pipelines/git-checkout.yaml
If the remote repository has a branch and a tag with the provided name (in there exists a branch in the remot with the same name as the provided tag (inputs.tag), then git rev-parse will fail with:
fatal: Needed a single revision
If that happens, then try to get a value with:
git ls-remote --tags origin ${tag}
Fixes #1272.
> git-checkout - try harder if getting hash from tag fails.

- e2e-tests/numpy-test.yaml
Needed for default python until multiversion python supported see #1306
> melange numpy test include python-3.12

- pkg/build/pipelines/git-checkout.yaml
It appears recurse-submodules got broken, as tag/branch reset flags
variable discarding recurse-submodule setting. Discovered with failure
to build neom.yaml in wolfi.
> git-checkout: fix recurse='true' does nothing

- docs/md/melange_build.md
- docs/md/melange_lint.md
- pkg/linter/linter.go
The ones upgraded to `Require` don't currently match any packages in Wolfi.
The ones downgraded to `Ignore` are noisy and problematic.
Also plumb through `ctx` to the HTTP request to get a remote APK.
> enforce some more lint checks

- pkg/renovate/bump/bump.go
- pkg/renovate/bump/bump_test.go
- pkg/renovate/bump/testdata/minio.yaml
Currently the wolfitcl renovate bumps are failing for git-checkout with mangled vars in the tags https://github.com/wolfi-dev/os/pull/22892 this should enable to handle the mangled vars in the checkout tags and correctly update the commit-sha
> wolfictl bump : handled mangled vars in updateGitCheckout tags

- e2e-tests/py3-pandas-test.yaml
- pkg/build/pipelines/python/import.yaml
cc/ @smoser @pnasrat 
Seems to work!
`make melange && export MELANGE=$PWD/melange && cd e2e-tests && ./run-tests py3-pandas-test.yaml`
```
2024/06/30 00:02:36 INFO running the main test pipeline
2024/06/30 00:02:36 INFO running step "Test a python package import, with optional from clause"
2024/06/30 00:02:36 INFO "from numpy import ma": PASS
2024/06/30 00:02:36 WARN /usr/lib/python3.12/site-packages/dateutil/zoneinfo/__init__.py:26: UserWarning: I/O error(2): No such file or directory
2024/06/30 00:02:36 WARN   warnings.warn("I/O error({0}): {1}".format(e.errno, e.strerror))
2024/06/30 00:02:36 INFO "from pandas import DataFrame": PASS
2024/06/30 00:02:36 INFO "import tzdata": PASS
2024/06/30 00:02:36 INFO running step "Test a python package import, with optional from clause"
2024/06/30 …
```
> Support multiple python imports

- pkg/container/docker/docker_runner.go
Reverts chainguard-dev/melange#1298
This broke a couple valid use cases, rolling back till we figure out a different fix for the original issue:
```
I'm hitting go: could not create module cache: mkdir /var/cache/melange: permission denied on my mac with v0.10.0 but building on a workstation with v0.10.0 works fine
I'm not able to test the openssh package locally with v0.10.0 but I can with v0.9.0 . The error I get with the test is No user exists for uid 501 (.. uid 1000 for the workstation)..
```
> Revert "Use current user's ID when building via Docker"

- pkg/build/pipelines/goreleaser/build.yaml
Notes: goreleaser new version refactored the skip flags https://github.com/goreleaser/goreleaser/blob/9786269e109eabbfb6e7220f3133ebe2bf884179/www/docs/deprecations.md?plain=1#L241. We need to replace it with `--skip=docker,ko,publish`
Notes:
> goreleaser pipeline: --skip flag refactor

- e2e-tests/py3-setuptools-test.yaml
- pkg/build/pipelines/python/import.yaml
The following things here:
a. fix a bug that hid failure of a 'imports'
This demonstrates the failure:
sh -c 'fails=0; echo foo |
while read line; do fails=$((fails+1)); echo "$fails"; done
echo fails=$fails
exit $fails'
The right side of the pipeline runs in a subshell that does not
affect the setting of 'fails' in the parent shell.
b. do not require specifying 'python' but rather use
/usr/bin/python3.* if and only if there is only one matching
executable.
This is needed for new packages built that do not depend
on python3.XX, but instead only python3.XX-base.  The latter
does not install 'python3' symlink, so you can't just default
to python3.
Add a test here as py3-setuptools-test to cover this.
c. be more quiet (set +x) - otherwise output gets written to
stderr and is very noisy with …
> python/import - fix a bug in 'imports', do not require specifying python

- pkg/build/pipelines/python/import.yaml
These python versions may be found in the wild, but the previous pull request would not have 'seen' them in /usr/bin.
Things older than python3.7 are intentionally not matched.
> python/import pipeline - find python3.7, python3.8, python3.9

- pkg/build/pipelines/python/build-wheel.yaml
- pkg/build/pipelines/python/build.yaml
- pkg/build/pipelines/python/install.yaml
Running 'python3 -m installer my.whl' (as gets done in build-wheel) will write shebang lines with 'python3'.
The melange SCA is ignoring symlinks in shebang at the moment, so it will not create any dependencies for that.
The larger problem here is that the python package that installs /usr/bin/foo with a shebang '#!/usr/bin/python3' will get a dependency in the SCA on python3.12-base (due to the site-packages python files), but the 'python3' may end up being python3.11. That situation would end up with broken /usr/bin/foo.
I chose to take the least invasive path here, and only change behavior when the 'python3' in the PATH is a symlink.
I *also* left the build and install pipelines calling 'python' rather than 'python3'.  I do not like that, but did not want to change it here.
> python/pipelines - resolve symlink to full path.

- pkg/build/pipeline.go
- pkg/build/pipeline_test.go
- pkg/container/bubblewrap_runner.go
- pkg/container/dagger/dagger.go
- pkg/container/docker/docker_runner.go
- pkg/container/runner.go
Fixes https://github.com/chainguard-dev/melange/issues/1359
For reasons I don't understand, the bubblewrap runner would not have $PATH set in interactive builds. The way we were setting PATH was to prepend it to the shell script we execute for each step, which is kind of janky. I've shifted things around to make that overriding of the environment happen in go via arguments rather than at runtime.
This does break the ability for pipeline-specified environment variables to be evaluated at runtime, but that is actually terrifying and I don't think we want that.
> Fix env overrides for interactive builds

- pkg/build/pipelines/npm/install.yaml
- pkg/build/pipelines/pecl/install.yaml
- pkg/build/pipelines/perl/cleanup.yaml
- pkg/build/pipelines/ruby/clean.yaml
A few of these pipelines could otherwise be used in subpackages if they defaulted to contextdir instead of destdir. I'd imagine they already may be used in some, but no-op
Notes:
Notes:
Notes:
> fix(pipelines): Use contextdir instead of destdir in a few places

- pkg/build/pipelines/cargo/build.yaml
Hi :wave:,
I tried to use the `cargo/build` pipeline for the first time and I noticed that the pipeline seems to test the wrong condition. This PR fixes this behaviour.
Greets,
Jan
> fix(cargo/build): test for non-zero length

- pkg/config/config.go
- pkg/config/schema.json
Adds ExcludeReason field for tracking why package auto updates are disabled.
Part of https://github.com/chainguard-dev/mono/issues/18290
Notes:
This change does nothing on it's own. Linting rules will be added to wolfictl in another PR.
Notes:
Notes:
IIUC (somewhat confusingly), melange lint lints apks, wolfictl lint lints melange configs, so the corresponding lint rule should be added in wolfictl.
> Add update.exclude-reason field.

- pkg/sca/sca.go
With Python, we can get away with checking for the "python" prefix in the package name as all other Python packages are prefixed with py<X.Y> instead of "python". For Ruby however, main Ruby packages follow a "ruby-<X.Y>" syntax and Ruby packages are "ruby<X.Y>"
This addresses the above by checking for "ruby-" instead of "ruby". In case a package explicitly sets "ruby" as a runtime dependency to pull in the latest version, we just skip over it
Notes: Ran against packages without a versioned Ruby rt dep, ran with it set, and ran with just `ruby` set
> fix(sca): Correctly check for existing Ruby runtime dependency

- docs/md/melange_build.md
- pkg/build/build.go
- pkg/build/options.go
- pkg/build/test.go
- pkg/cli/build.go
Expose ignoreSignatures functionality from apko to melange CLI clients.
Follow up for this PR: https://github.com/chainguard-dev/apko/pull/1179
Notes: I've run the full test suite locally without issue, but do not see wolfi as an E2E test case, so leaving this unchecked as unable to verify.
Notes: E2E test suite passes. Was also able to build an custom APK locally without issues.
Notes: Linter checks passed locally as well
> Expose ignoreSignatures functionality

- pkg/build/compile.go
This is extra spammy when we're loading lots of configs, like we do to construct a build graph.
> move 'adding package %q for pipeline %q' to debug logging

- pkg/build/build_test.go
- pkg/build/testdata/configuration_load/invalid-duplicate-package-name.melange.yaml
- pkg/config/config.go
We had a test for duplicate subpackages names, but it didn't catch the case where a subpackage had the same name as the main package.
> Add test to catch duplicate package names

- pkg/convert/python/python.go
- pkg/convert/python/python_test.go
without this we try to add py3-Jinja2 or py3-MarkupSafe each time
Signed-off-by: Pris Nasrat <pris.nasrat@chainguard.dev>
> melange convert python: use normalized names

- docs/UPDATE.md
It is not immediately obvious which repository is queried when using this option so best to
add some clarifying documentation.
This option will use the first repository specified in the `pipeline: / uses: git-checkout`
section of the melange config.
Signed-off-by: philroche <phil.roche@chainguard.dev>
> docs: Add information on the repository used with the `git` `update` configuration option

- pkg/build/test.go
- pkg/config/config.go
- pkg/config/config_test.go
This thing is a bit of a beast, so I'm not going to do it all at once, but some of these string replacements are incredibly mutate-y, so I've rewritten them to be a bit more functional.
This still isn't great, but I think it's better than before.
> Refactor parts of the ParseConfiguration

- pkg/config/config.go
- pkg/config/config_test.go
We were calling this for subpackages but not the main package.
> config: Replace pipelines at top level

- .github/workflows/wolfi-presubmit.yaml
- pkg/build/build.go
- pkg/config/config.go
- pkg/sbom/bom.go
- pkg/sbom/generator.go
- pkg/sbom/implementation.go
This PR continues to improve the state of melange's SBOM code:
1. Fixes the issue where our external references used `PACKAGE_MANAGER` instead of `PACKAGE-MANAGER`.
2. Breaks apart "SBOM generation" logic from "writing the SBOM back into the APK's filesystem" logic. The hope is we can then use this seam to implement tests in the near future.
> More SBOM logic improvements

- pkg/build/pipelines/cargo/build.yaml
Previously, we defaulted to bin. Allow this to be overriden with another install directory (i.e., libexec)
Additionally, depend on busybox to avoid needing to add the package to the environment in the package file
> chore(cargo/build): Allow changing install dir, add busybox

- pkg/sca/sca.go
github.com/microsoft/go toolchain uses custom experiments for FIPS
support. Add them to sca generator, to support FIPS binaries built
with that toolchain.
Test remains the same, as go-msft toolchain is not trivially available
to compile binaries on the fly.
> sca: add support for more go fips toolchains

- pkg/sca/sca.go
- pkg/sca/sca_test.go
.pc file version can be an aribitrary string value, without any
relation to soname, nor semver.
This yields the very opaque errors
provides = pc:gdal=3.8.5dev
datahash = c4638ec49b51aac1fc8f1d948b06a5b6c7a9f41dca2f980629b1f12f8e8be711
ERROR: ./packages/x86_64/gdal-3.8-dev-3.8.5-r0.apk: package file format error
Which pointlessly waste engineering time.
Node we do not generate depends on pc: provides, as currently
`wolfictl text` transitive dependencies checks are unable to resolve
these.
Fixes: https://github.com/chainguard-dev/melange/issues/1172
Note there is sense that this may have been a missfeature in abuilds
too.
> sca: make pc: provides/vendored use full package version

- pkg/build/pipelines/split/debug.yaml
- pkg/build/pipelines/split/dev.yaml
- pkg/build/pipelines/split/infodir.yaml
- pkg/build/pipelines/split/locales.yaml
- pkg/build/pipelines/split/manpages.yaml
- pkg/build/pipelines/split/static.yaml
Currently, our split pipelines only support splitting targets from the main package in destdir. There are cases where this behavior could be useful for subpackages
I.E., minizip is built as part of the zlib packaging process as a subpackage. As a result, it includes development headers. As we can now override the source package, we can provide a minizip-dev subpackage without bundling it in zlib-dev
Example:
```
- name: minizip-dev
pipeline:
- uses: split/dev
with:
package: minizip
```
> feat(pipelines/split): Support overriding source package

- pkg/build/pipelines/split/dev.yaml
- pkg/build/pipelines/split/static.yaml
/usr/local/\*/lib64 was added to accomodate splitting away libraries used for development. This was incorrect. Now ALL libraries in /usr/local/\*/lib64 get split away
This fixes that and removes the behavior. We add `usr/` to library paths and that is sufficient for what we need
Broken behavior introduced by me here: https://github.com/chainguard-dev/melange/pull/1472
> fix(split pipelines): Don't split lib64 libraries

- pkg/convert/apkbuild/apkbuild.go
- pkg/convert/apkbuild/apkbuild_test.go
- pkg/convert/apkbuild/testdata/no_sub_packages.yaml
- pkg/convert/apkbuild/testdata/scanner_error.yaml
- pkg/convert/apkbuild/testdata/with_multi_sub_packages.yaml
- pkg/convert/apkbuild/testdata/with_unrecognised_sub_packages.yaml
Based on discussion with Dustin, this PR aims to:
> - converting the tarball fetches to git checkouts and tags
> - fixing up the update stanza to handle tag checkouts
> - adding a test stanza with some basic tests
Existing melange output for `melange convert apkbuild argon2 ` : 
```yaml
package:
name: argon2
version: "20190702"
epoch: 0
description: The password hash Argon2, winner of PHC
copyright:
- license: Apache-2.0 OR CC0-1.0
environment:
contents:
packages:
- build-base
- busybox
- ca-certificates-bundle
pipeline:
- uses: fetch
with:
expected-sha256: daf972a89577f8772602bf2eb38b6a3dd3d922bf5724d45e7f9589b5e830442c
uri: https://github.com/P-H-C/phc-winner-argon2/archive/${{package.version}}.tar.gz
- uses: autoconf/configure
- uses: autoconf/make
- uses: autoconf/make-install
- uses: …
```
> adds git checkout fetch,update,test and yams the melange apkbuild yamls

- pkg/config/config.go
- pkg/config/config_test.go
We weren't substituting anything in Test or the apko ImageConfiguration.
Fixes https://github.com/chainguard-dev/melange/issues/1478
> config: Whack more moles for string replacement

- pkg/build/pipelines/ruby/build.yaml
If it exist, remove the signing_key from gemspec by default since it leads to build failures as the key is not available in the build environment and is not needed.
> pipelines/ruby: remove signing_key by default

- pkg/build/build.go
- pkg/index/index.go
It is obsolete, as only melange tool used to write it and much better
options now exist to convert .tar.gz to .json using [apkrane] tool
instead.
[apkrane]: https://github.com/jonjohnsonjr/apkrane
> index: stop writing APKINDEX.json

- pkg/container/qemu_runner.go
- pkg/linter/linter.go
These seem to be relatively common cases where someone writes `log.Warn` and goimports chooses to import charmbracelet/log. This shouldn't be necessary when you call `log := clog.FromContext(ctx)` first.
For CLI users the result is not really any different (we use charm logging via clog anyway), but for places where this code might get embedded in another service where a different logger is used, it can be surprising.
> cleanup: remove some direct imports of charm log

- pkg/build/pipelines/maven/pombump.yaml
This PR adds a flag to the pombump pipeline to display the dependency tree for a pom.xml file.
> pombump: add flag to display the dependency tree

- pkg/sca/sca.go
- pkg/sca/sca_test.go
I noticed this when I was playing with a shbang program like:
#!/usr/bin/env busybox sh
echo hello world
Melange would give a warning like this:
Error reading shbang from usr/bin/hello-busybox:
a shbang of only '/usr/bin/env' with multiple arguments
(6 /usr/bin/env busybox sh echo "hello world")
> Only read the first line for shbang.

- pkg/sca/sca.go
In most programming languages compiler would raise a warning unused
variable, assigned but never used.
Or am I missing something?
> sca: remove set but never used variable

- pkg/build/compile.go
- pkg/build/pipeline.go
I noticed while testing this that loading a pipeline via "uses" will overwrite that pipeline's name, which probably isn't what we want, so I've updated Compile() as well to keep the parent's name. This has the nice effect of allowing both "name" and "uses" to be meaningful (if you want to provide more context to why you're using the pipeline) while omitting redundant information (if we have "uses" in the slog context we don't really need to know that pipeline's "name" too).
> Add uses and name to slog values

- pkg/build/pipelines/git-checkout.yaml
lifecycle now supports scheduled, periodic updates. Typically these
point at a branch checkout with an expected commit, which is fast
moving.
Instead of expecting for that commit/branch to remain static forever,
reset to it, if depth is set to -1 (full clone, rather than
shallow/single commit). And update messaging.
This will correctly build scheduled periodic packages, even as
upstream branch moves forward.
The builds will fail, if upstream rewrites branch history, or if depth
is not set to -1 (non-shallow). Meaning default behaviour of expected
commit is preserved.
Thus the typical hard-failure of:
> 2024/09/20 15:08:22 INFO [git checkout] FAIL expected commit 4a19238a0920463b9582c8593526d322ac78dc13 on release-v2.9,  got 4fb4544cea4f9be4fad23bf6bbce764738472ea6
New message is:
> …
> git-checkout: support scheduled updates

- pkg/sca/sca.go
libcuda.so.1 is not a real library with a stable API/ABI. Instead it
is coupled to the runtime kernel. It is typically provided inside
containers, via mounts that ultimately provide it as libcuda.so.1 ->
libcuda.so.555.34 or some such. As no packages in wolfi provide
libcuda.so.1 never emit dependency on it, as it will always make such
packages uninstallable.
This should fix ~120 or so packages that currently declare
"no-depends: true" due to this issue.
> sca: never emit libcuda.so.1 runtime dep

- README.md
- pkg/build/pipeline.go
- pkg/build/pipelines/split/debug.yaml
- pkg/build/pipelines/split/dev.yaml
- pkg/build/pipelines/split/infodir.yaml
- pkg/build/pipelines/split/locales.yaml
- pkg/build/pipelines/split/manpages.yaml
- pkg/build/pipelines/split/static.yaml
- pkg/config/vars.go
Adds a substitution, `targets.outdir`, for melange's output directory. Useful for when we need to reference a package outside of destination directory or subpackage directory. I.E., copying files from one subpackage to another
> feat(melange): Add sub for output directory

- e2e-tests/py3-pandas-test.yaml
Installing py3-pandas does not guarantee you a /usr/bin/python3.
This is fallout of our choice to make pythons co-installable.
More info on this https://github.com/wolfi-dev/os/issues/26818
There isn't any serious value gained in this test here
versus the pipeline import tests that are still there, so
just drop it.
> Adjust an e2e-test that made a bad assumption.

- docs/md/melange_build.md
- docs/md/melange_test.md
- pkg/build/build.go
- pkg/build/options.go
- pkg/build/test.go
- pkg/build/test_options.go
- pkg/cli/build.go
- pkg/cli/test.go
Fixes https://github.com/chainguard-dev/melange/issues/1528
> add --cleanup flag (default true)

- pkg/sca/e2e_test.go
- pkg/sca/sca.go
Fixes: https://github.com/wolfi-dev/os/issues/29828
Currently sca only adds files ending in '.so.' as valid deps. Some libraries, libgallium in mesa for example, don't have a numbered suffix and are being dropped by sca.
```
ldd usr/lib/libEGL.so.1.0.0 | grep gallium
libgallium-24.2.3.so => not found
```
Notes:
This isn't a functional change as far as I'm ware. I didn't find issues building other packages.
Notes:
Previously mesa-egl was missing the dep on so:libgallium. With this change it is not. Other packages missing deps should now have them once this lands and they're rebuilt.
> Properly detect .so files as deps

- pkg/sca/sca.go
As discovered in https://github.com/chainguard-dev/melange/pull/1522
and ongoing test pipelines of pc files discrepancy discovered between
wolfi configured pkgconf and what melange generates.
In wolfi https://github.com/wolfi-dev/os/blob/9ad9b181cee6bc20fd090b942c2355990724bf7c/pkgconf.yaml#L39
```
--with-pkg-config-dir=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig \
```
pkgconf is configured to look for the above paths. But melange looks at different set of paths.
pkgconf installs pc-files into "usr/lib" ("usr/lib64" is acceptable too, because of lib64->lib link in base layout) and into "usr/share". However "usr/share" is not considered public by melange, but should be. As "architecture independent" pc files are there, for example for …
> fix: pc provides

- pkg/build/pipelines/cmake/configure.yaml
It is a choice of optimisation levels to apply at build time of C/C++
code. There are choices spanning from -00 to -03 and -0s. Most
distributions build with debug symbols which are then stripped, but
otherwise apply release optimisations at -O2 or -O3 level.
This is evident from dpkg-buildflags & debhelper pipelines in
Debian-like systems, as well as rpm macros on Fedora-like systems.
In C/C++ there are code optimisations at -O2 and higher levels that
increate binary size. And compiler has an option, do not optimise
things that would increase binary size -Os (Optimize for size. -Os
enables all -O2 optimizations except those that often increase code
size).
In wolfi by default we choose to build with -O2 via build-env files,
and openssf-compiler-options. However our CMAKE pipeline switches …
> cmake: switch from MinSizeRel to Release

- pkg/sca/sca.go
Developer impact:
I want to compile and link against curl, i installed curl-dev and nothing works, i even installed openssl-dev and everything still does not work:
```
diff --git a/scans/curl.yaml.scan b/scans/curl.yaml.scan
index 98c235989..5260fd010 100644
--- a/scans/curl.yaml.scan
+++ b/scans/curl.yaml.scan
@@ -13,6 +13,11 @@ depend = brotli-dev
depend = libpsl-dev
depend = nghttp2-dev
depend = openssl-dev
+depend = pc:libbrotlidec
+depend = pc:libnghttp2
+depend = pc:libpsl
+depend = pc:openssl
+depend = pc:zlib
depend = so:libcurl.so.4
provides = cmd:curl-config=8.10.1-r1
provides = pc:libcurl=8.10.1-r1
```
With this change curl-dev automatically gains depends on openssl zlib libpsl libnghttp2 libbrotlidec dev packages to ensure that building and linking against curl-dev "just …
> Make installing -dev package "just work" and pull in all other dev libraries it needs

- pkg/build/pipelines/split/debug.yaml
Currently the variable substitution for the destination debug symbols
results in one level of directories being expanded and substituted
away. This breaks gdb automatic discovery of the debug symbols. Gdb is
looking for /usr/lib/debug/usr/bin/openssl.debug, whilst current
split/debug pipelines installs the dst to
/usr/lib/debug/bin/openssl.debug instead.
I think the substituition intends to strip the prefix path of the
installed file, to achieve the intended path without the leading '/',
e.g. usr/bin/openssl.debug. Thus make it do just that.
> pipelines: fix split/debug

- pkg/build/test.go
- pkg/build/test_test.go
Until now `melange test` was failing with QEMU runners
This fixes the behaviour thanks to the investigation of @maxgio92 :+1: 
EDIT: depends on https://github.com/wolfi-dev/os/pull/30922
> fix(qemu): fix failing test pipeline when using qemu runner

- pkg/sca/sca.go
Do not add a cmd:awk dependency as nothing will ever provide cmd:awk
awk is only provided by busybox or gawk.  Both of those do so with a
symlink.  That means that we have to ignore shbang that have awk or
we'll get a 'cmd:awk' dep that will never be provided.
Sad face.
Somehow we need to fix the symlink provider thing, but for
now, just this.
This was noticed in wolfi-dev/os/check.yaml . Melange said:
Added shbang dep cmd:awk for usr/bin/checkmk
> Do not add a cmd:awk dependency as nothing will ever provide cmd:awk

- pkg/container/qemu_runner.go
When using `make debug/<foo>` to build a package, the shell you're dropped in does not instantiate a pty
Fix this so it now correctly instantiates an usable shell to the QEMU runner
> fix(qemu): fix missing pty allocation for debug shell in qemu runners

- docs/md/melange_build.md
- docs/md/melange_test.md
- pkg/build/build.go
- pkg/build/options.go
- pkg/build/test.go
- pkg/build/test_options.go
- pkg/cli/build.go
- pkg/cli/test.go
- pkg/container/bubblewrap_runner.go
Followup to #1529 
`melange build` already had a `--rm` flag (default `false`) that cleaned up containers after execution. Instead of adding a redundant `--cleanup` flag, we can just repurpose that, and make it default `true`.
This also pipes `remove` to the bubblewrap runner which creates temp guest dirs. 
This also adds `--rm` (default `true`) to `melange test`, which wasn't wired up before and so was always false.
> cleanup glow up

- pkg/container/bubblewrap_runner.go
schroot, choort, rpmbuild, docker, lxd, incus, systemd-nspawn, qemu
VMs, and bare-metal machines all have /sys (sysfs) mounted.
During test pipelines some of the software we build and run, tries to
use /sys which is expected to be available and currently fails. Fix
this compatability by providing /sys in the bubblewrap sandbox, by
making it look ever so slightly like a normal chroot.
This fixes running jemalloc test pipeline with stress-ng under
bubblewrap runner.
> bublewrap_runner: add /sys mount

- pkg/build/compile.go
- pkg/build/compile_test.go
Melange allows users to define "test" pipelines which are executed via `melange test` (or `wolfictl test`), [ex](https://github.com/wolfi-dev/os/blob/main/apko.yaml):
```yaml
package:
name: apko
version: 0.19.2
epoch: 0
test:
pipeline:
- runs: |
apko version || exit 1
```
Melange will automatically add the package that is being tested (in this case `apko`) to the package constraints/world where the test environment is run as it's assumed that you're trying to test the package that was just built, ex:
```
2024/09/23 16:29:04 INFO image configuration:
2024/09/23 16:29:04 INFO   contents:
2024/09/23 16:29:04 INFO     build repositories: []
2024/09/23 16:29:04 INFO     runtime repositories: []
2024/09/23 16:29:04 INFO     keyring:      []
2024/09/23 16:29:04 INFO     packages:     [apko]
``` …
> Pin the package version used during tests

- pkg/build/compile.go
- pkg/build/compile_test.go
commit 57e3f4cfac3af9417db6e68ff2f6b5e8eaf7e349 (via #1518)
broke test of wolfi python packages where they relied on the test of the
'main' package to install a subpackage that `provides` the main package.
For an example, see:
https://github.com/wolfi-dev/os/blob/cd5e90dc01bc7d5/py3-fastbencode.yaml
The main package is provider-priority 0 and the subpackages
have specific provider-priorities > 0.
With the pkg=version change, we got the main package installed, which
is empty.  Using ~ gets the desired behavior even for historic
packages.
> Pin the package version with ~ rather than =.

- .github/workflows/release-scheduled.yaml
This was adapted from wolfictl's weekly release workflow: https://github.com/wolfi-dev/wolfictl/blob/main/.github/workflows/release.yaml
...but made **_daily_**.
I believe this will produce tags, which will end up trigger the pre-existing release workflow in melange: https://github.com/chainguard-dev/melange/blob/main/.github/workflows/release.yaml
> ci: add workflow to tag releases daily

- pkg/cli/build.go
This improves Melange builds + SBOM generation in two ways:
1. Use the directory containing the build config for the git auto-detection.
2. When auto-detection doesn't completely work, fallback to filler values (`"unknown"`). In a future PR, we might introduce some sort of "strict" flag that get Melange to fail if the correct (non-fallback) values aren't all available.
> Git data fallbacks

- pkg/build/pipelines/cargo/build.yaml
compiling a simple application with rust requires cc linker so adding build-base to cargo/build pipeline so that we can omit specifying build-base at environment blocks in package level melange config.
```bash
$ docker run --name wolfi --rm -it cgr.dev/chainguard/wolfi-base:latest sh
/ # apk add rust
/ # cargo new demo
Creating binary (application) `demo` package
note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
/ # cd demo/
/demo # cargo build
Compiling demo v0.1.0 (/demo)
error: linker `cc` not found
|
= note: No such file or directory (os error 2)
error: could not compile `demo` (bin "demo") due to 1 previous error
/demo # apk add build-base
/demo # cargo build
Compiling demo v0.1.0 (/demo)
Finished `dev` profile …
```
> add build-base to cargo/build pipeline

- pkg/cli/build.go
And specifically do not attempt to autodetect it from local git state. HEAD detection is still in place. User must pass in a build config repo URL explicitly to avoid a fallback value being used.
Fixes #1591
> fix(build): require build config repo URL

- pkg/build/pipelines/cargo/build.yaml
In the current pipeline, the build fails because cargo doesn't recognizes all the input options we're passing and fails.
```bash
cargo auditable build "--release --frozen --package=linkerd2-proxy"
~ # cargo auditable build "--release --frozen --package=linkerd2-proxy"
error: unexpected argument '--release --frozen --package' found
tip: a similar argument exists: '--release'
Usage: cargo build --release
For more information, try '--help'.
```
removing quotes will make it recognizable. 
this is tested using the following command after building melange again. 
```bash
make melange
```
write a melange config with custom opts `opts: --release --no-default-features -vv`
<details><summary>Details</summary>
<p>
```yaml
package:
name: linkerd-await
version: 0.2.9
epoch: 2
description: "A program …
```
> allow passing more than one opts to cargo build

- pkg/container/bubblewrap_runner.go
- pkg/container/bubblewrap_runner_test.go
Bubblewrap pipeline is run with same uid of the user that run melange by default, mapped for the child user namespace, leading to possible consistency problems on the resulting package filesystem, while standardizing uid to 1000 or 0.
The classic example is the difference between running melange with sudo and without.
Furthermore, passwd database is already set for the uid 1000 with name build, instead of the user that is run as, when not explicitely specified. The same applies to the gid map.
Fixes #1570
Notes:
> fix(bubblewrap_runner): run as build 1000 by default

- pkg/build/pipelines/cargo/build.yaml
this patch passes `--target-dir` flag with cargo at build time. 
This is required because `cargo/build` pipeline uses modroot and when we `cd` into a specific directory and invoke cargo build, the resulting binary still ends up in root of the repository at `GIT_ROOT_DIR/target/release/foo` 
After which when we use the following install command it fails to find the binary. 
```bash
OUTPUT_PATH="target/release"
install -Dm755 "${OUTPUT_PATH}/${{inputs.output}}" "${INSTALL_PATH}/${{inputs.output}}"
```
by passing `--target-dir` flag to target, we are creating the `target/release/foo` binary in the current working directory hence the install command will succeed. 
This change is looking good considering backwards compatibility with the use of this pipeline in existing package. 
We change the …
> pass --target-dir with cargo/build pipeline

- pkg/build/build.go
- pkg/build/compile.go
- pkg/build/test.go
These methods are used only in the build package.
Also delete unused functions.
> chore: unexport build pkg methods

- pkg/container/qemu_runner.go
Fix situation when crosscompiling would not work because of missing cpumodel and machine types
> fix(qemu): use proper machine type and cpu model based on host arch

- pkg/build/pipelines/fetch.yaml
Print the checksums as a part of the pipeline as it is helpful to not have to validate the checksum all over again when correcting it
> chore(pipelines/fetch): Print expected and found checksums

- pkg/convert/apkbuild/apkbuild.go
- pkg/convert/apkbuild/apkbuild_test.go
- pkg/renovate/bump/bump.go
- pkg/renovate/cache/cache.go
- pkg/util/util.go
`util.DownloadFile` is mainly used to get a local file which we can hash with `util.HashFile`. But, it's unnecessary to download the file to disk if it's only going to get hashed and deleted. So instead, the renovate code that just does that now does that with just `net/http` and `crypto/sha{256,512}`.
The only remaining user of `util.DownloadFile` and `util.HashFile` is the cache populator, which copies the file to another location (or to GCS), which can keep this for now.
Also remove some generic methods with stuff from stdlib `slices`.
There are more methods we can probably clean up or unexport or make `internal`, but this is a good stopping point for now.
> cleanup: remove unnecessary utils

- pkg/container/qemu_runner.go
This doesn't need to be printed each time. If you care, you can `--log-level=debug`
> qemu: reduce logspam for qemu runner

- pkg/build/build.go
Moving the creation of the subpackage dir before running the pipelines means that the subpackage directory was created as the user that ran melange rather than the user that is doing the build.  Those uids can be different depending on the runner.
SBOMs are written as the uid that invoked melange.  It assumes that it can create Workspace/package-dir/var/lib/db/sbom . Previously, the 'package-dir' portion of that would sometimes get created by the uid inside the build (probably as a result of 'mkdir -p ${{targets.contextdir}}/usr/bin' or the like).  The result was that the uid running melange could not create var/lib/db/sbom because it did not have write perms to package-dir.
By creating package-dir first, we (mostly) ensure that we can later create var/lib/db/sbom, and this will succeed …
> Create sub-package directories in WorkDir before building subpackage

- pkg/build/build.go
- pkg/build/pipeline.go
When running privileged docker as an unprivileged user, the files that are created in the WorkspaceDir are created as root. Even if the build were run as non-root, they would not necessarily be the same ownership as the user invoking melange.
As a result, WorkspaceDir would not be able to be cleaned up and melange would just leave files there to later be cleaned up with a dangerous 'sudo rm -Rf' by the user.
The change here is to clean up the WorkspaceDir from _inside_ the container, where the uid is the same as the uid that created the files.
I believe this will waste IO and/or time on the qemu runner, where /home/build isn't actually bind'd in.  Later we could expose a CleanWorkspace from the runner that was a noop in qemu.
> Clean up workspace dir from inside runner to avoid permission errors.

- .github/workflows/release.yaml
This is a follow-on to #1653.
Closes #1655 (see this issue for more info!)
> release: check for both tag and release

- pkg/build/pipeline.go
Fix https://github.com/chainguard-dev/internal-dev/issues/1571
We don't want to pass possible code execution to `expected-sha{256,512}`, the comparison is done in shell
this opens the possibility to inject values and/or commands.
SHA checksums only contains [0-9a-zA-Z] chars, so ensure we only have those. This will prevent any injection at that stage.
> fix(pipeline): do preliminary checks for checksum invalid chars

- pkg/build/pipelines/cargo/build.yaml
Some projects exports the binaries to different paths so that we couldn't use the cargo/build pipeline properly.
Example case here: https://github.com/wolfi-dev/os/pull/34028
Notes:
Notes:
Notes:
> pipelines/cargo: ability to override the hardcoded output-dir

- .github/workflows/e2e.yaml
That public image has been pulled, and we don't really need it anyway since we rely on the SPDX check to tell us whether SBOMs are valid.
> drop ntia e2e test

- pkg/sca/sca.go
Some packages provide symlinks in /usr/lib/ that point to the library installed in another path.
Examples:
lua5.3 usr/lib/liblua-5.3.so.0 -> lua5.3/liblua-5.3.so.0
lua5.4 usr/lib/liblua-5.4.so.0 -> lua5.4/liblua-5.4.so.0
llvm17 usr/lib/libRemarks.so.16 -> ../lib/llvm17/lib/libRemarks.so.17
The total number of these cases in wolfi is only 12 links from a system lib dir to elsewhere
across 5 origins:
llvm15-15.0.7-r7
llvm16-16.0.6-r3
llvm17-17.0.6-r2
lua5.3-5.3.6-r5
lua5.4-5.4.7-r1
The result was that those packages don't get listed as providing the library that the _do_ provide.
The target of the symlink above previously would get considered itself, but the fact that the target was not in isInDir(libDirs) meant it would get marked as vendored.
It meant that packages that depend on …
> Consider symlinks as potential provides for so:

- RELEASE.md
- pkg/build/build.go
- pkg/build/test.go
2 small changes
1. add a statement that after running the release workflow it should have created a github release and tag
2. put melange version output in `Summarize` output.
Now, you'll see something like:
```
$ ./melange build --git-repo-url=github.com/wolfi-dev/os test-me.yaml  --arch=x86_64
2024/11/22 16:57:28 INFO git commit for build config not provided, attempting to detect automatically
2024/11/22 16:57:28 INFO melange v0.15.13-2-g2bf668c is building:
2024/11/22 16:57:28 INFO   configuration file: test-me.yaml
2024/11/22 16:57:28 INFO   workspace dir: /home/user/tmp/melange-workspace-2077411557
2024/11/22 16:57:28 INFO evaluating pipelines for package requirements
```
> Minor RELEASE.md cleanup, add git version in Summarize output.

- pkg/build/pipeline.go
Similar to PR #1659 we should validate expected commits too
> fix(pipeline): validate expected commit before passing to git-checkout pipeline

- pkg/build/compile_test.go
We can expand on this whenever we want to — but just wanted to get something to codify minimal expectations of comment stripping since it's load bearing now.
> test(compile): basic tests for stripComments

- docs/md/melange_compile.md
- pkg/build/build.go
- pkg/build/compile.go
- pkg/build/compile_test.go
- pkg/build/test.go
- pkg/cli/compile.go
Before, these looked like:
```
compiling main pipelines: compiling Pipeline[0]: stripping runs comments: 14:13: not a valid test operator: -m
```
Now, these look like:
```
compiling "hwloc" test pipelines: compiling Pipeline[0]: stripping runs comments: 14:13: not a valid test operator: -m:
> if [[ uname -m == 'x86_64']]; then
^
```
First big change is that we include the package name in the error. Without this, it was really challenging to find which package actually had a syntax error.
Second big change is that we use the nice structured error we get back from the shell parsing library to include the line that failed with a cursor pointing at the column that failed.
> Improve comment stripping errors

- docs/md/melange_build.md
- pkg/cli/build.go
- pkg/container/qemu_runner.go
Properly support x86 emulation on MacOS
> fix(qemu): fix MacOS crosscompile path

- pkg/sca/sca.go
- pkg/sca/sca_test.go
Ruby is being modified to be coinstallable across versions. To avoid different versions of Ruby from clashing, we need to generate a dependency on ruby-\*-base instead of ruby-\*
Notes:
Notes:
Notes:
> fix(sca): Generate dependency for ruby-*-base instead of ruby-*

- pkg/sca/sca.go
- pkg/sca/sca_test.go
Everything that depends on cmd:ruby fails to resolve, this was poorly timed and would require a Ruby world rebuild
> fix(sca): Revert recent SCA changes for Ruby

- pkg/linter/linter.go
This is causing a panic so we don't know what the underlying error is.
Fixes https://github.com/chainguard-dev/melange/issues/1552
> Handle WalkDir errors

- pkg/build/pipelines/cargo/build.yaml
This PR introduces an input option for the `cargo/build` pipeline to pass rust flags to all compilers.
It leverages the `RUSTFLAGS` [environment variable](https://doc.rust-lang.org/cargo/reference/environment-variables.html).
Notes:
To make _build package_ pipelines pass, the following PR is needed I think:
* https://github.com/wolfi-dev/os/pull/36623
> feat(pipelines/cargo): add support for rustflags

- Makefile
- e2e-tests/numpy-test.yaml
- pkg/build/sign.go
- pkg/sign/apk_test.go
Switch to SHA2-256 signature by default for the `melange sign`
command.
Use the same runtime opt-out back to SHA1 signatures as apko.
With apko from:
- https://github.com/chainguard-dev/apko/pull/1440
This will use RSA256 signature type for both .apk & APKINDEX.tar.gz
signing.
> sign: switch to SHA2-256 signature by default

- pkg/renovate/bump/bump.go
- pkg/renovate/bump/bump_test.go
Before this change, `melange bump foo.yaml 1.2.3` would produce:
```
package:
name: foo
version: 1.2.3
epoch: 0
```
Note the blank line, which would trip up on our `yam` config.
With this change, `melange bump foo.yaml 1.2.3` produces:
```
package:
name: foo
version: "1.2.3"
epoch: 0
```
Which is functionally equivalent, without the trailing empty line.
I tried other styles, but none worked but this. I'm open to hearing better alternatives.
> bump: double-quote bumped version strings, avoid trailing newline

- pkg/container/qemu_runner.go
This improves a bit the logging, making it less noisy and adhere to other runners' output.
Also, improve a bit the connection check, which gets very spammy on less performant machines (or cross compiles) where IO timeout was set way too low.
> fix(qemu): improve logging, make connection  check less spammy

- e2e-tests/numpy-test.yaml
The test was failing because 'numpy' is now installing a python3.13 version.  Instead of making an assumption on what it installs, let the pipeline do the rigth thing.
The python/import pipeline will search for exactly one python installed and use it to test the import.
> Fix numpy-test to work across python 3.12 to 3.13 transition.

- pkg/build/pipelines/go/build.yaml
- fix: Move `go mod tidy` after `cd` to `modroot` dir
- Previously, in the `go/build` pipeline, if `modroot` was set and `tidy=true`, the `go mod tidy` command ran in the home directory instead of the `modroot` directory.
- feat: Validate existence of `go.mod` in `modroot`
- Added a check to ensure `go.mod` exists in the `modroot` directory, ensuring `modroot` is set correctly. This will help the reliability of `go/bump` automation as it also set its modroot by looking into the `go/build` pipeline modroot.
> Notes: this will result in build failure of PR if there is any package where the modroot is set incorrectly.
> go/build pipeline: Move `go mod tidy` after `cd` to `modroot` dir AND Validate existence of `go.mod` in `modroot`

- Makefile
- pkg/build/pipeline.go
- pkg/build/pipeline_test.go
- pkg/convert/relmon/release_monitoring.go
- pkg/http/http.go
- pkg/renovate/cache/cache.go
- pkg/sbom/package.go
- pkg/sbom/package_test.go
Some minor improvements on sha validations 
sample benchmark code https://gist.github.com/ajayk/869fedfbcdb0a64444858c14de7c7a31
Results here 
```
goos: darwin
goarch: arm64
pkg: a.com
cpu: Apple M2 Pro
BenchmarkMatchValidShaCharsDynamic-12                  1             57416 ns/op
BenchmarkMatchValidShaCharsPrecompiled-12              1             12833 ns/op
BenchmarkMatchValidShaCharsManual-12                   1               625.0 ns/op
PASS
ok      a.com   0.233s
```
> minor go cleanup and some performance improvements 

- e2e-tests/capabilities-add-drop-build.yaml
- e2e-tests/capabilities-add-drop-nopkg-test.yaml
- examples/capabilities-add-drop.yaml
- go.mod
- go.sum
- pkg/build/build.go
- pkg/build/test.go
- pkg/config/config.go
- pkg/container/bubblewrap_runner.go
- pkg/container/config.go
- pkg/container/docker/docker_runner.go
This PR adds the configuration to add and drop Linux capabilies to the container for bubblewrap and docker runners, enabling a declarative way to do least privilege. The capabilities added or dropped are relative to the minimum set of capabilities Docker sets. They are applied to all both build and test pipelines.
Furthermore, the minimum set of process capabilities in Bubblewrap container is now the same of Docker default capabilities, to improve result consistency.
Fixes #1703
Notes:
Notes:
Notes:
> feat: add support to add and drop linux capabilities

- .github/workflows/release.yaml
- .goreleaser.yaml
melange homebrew is in homebrew core now, so we dont need to generate the update script to our hosted tap
https://github.com/Homebrew/homebrew-core/blob/master/Formula/m/melange.rb
this cleans up our side a bit.
will remove the sts policy as soon this PR is approved and merged
> stop generation homebrew update as melange in in homebrew core

- pkg/build/testdata/goldenfiles/sboms/7zip-two-fetches-2301-r3.spdx.json
- pkg/build/testdata/goldenfiles/sboms/crane-0.20.2-r1.spdx.json
- pkg/sbom/document.go
**sbom: switch SPDX namespace from SHA1 to FNV-1a**
Similar in design choice to https://github.com/golang/go/commit/092d18b31824d35a07f796c90380d5e607b61681 switch SPDX namespace calculation from a broken security hash to a non-cryptographic [FNV-1a](https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function) hash.
This helps to completely remove SHA1 usage in melange.
If we want to preserve the same IDs we should consider switching from crypto/sha1 to github.com/pjbgf/sha1cd, which is not registered with the crypto framework.
The difference is that SPDX namespace URI will be different in length:
- https://spdx.org/spdxdocs/chainguard/melange/29949ae152def3411439e863d8039ac59c083862
- https://spdx.org/spdxdocs/chainguard/melange/635ba484b06e356eb6c8e67e49e70dcb
It is still …
> sbom: switch SPDX namespace from SHA1 to FNV-1a

- pkg/build/build.go
Write out a GCC specs file into the workspace, that toolchain can
import to adjust build settings on per-package basis. For now, this
only adds Package Metadata ELF note settings.
In the future, this can be extended with other settings, for example
controlling generation of debug symbols, march/mtune/optimisations,
etc.
Potentially workspace is not a good location for this file. Maybe
worth considering to move this from /home/build/.melange.gcc.spec to
/etc/melange/gcc.spec.
By itself this PR is innert, until our default spec files start including the newly generated snippets when present. See:
- https://github.com/wolfi-dev/os/pull/39152
For the proposed usage of this change, which initially makes it opt-in for 3 packages to shake out any e2e integration.
> build: Write a GCC specs file into workspace

- README.md
- pkg/build/pipeline.go
- pkg/config/config_test.go
- pkg/config/vars.go
I've noticed a growing pattern of using `$(basename ${{targets.contextdir}})` in our YAML to calculate the subpackage name. This only works when the string is processed by a shell, and is really just a hack anyway. Let's introduce a formal substitution.
> Add ${{subpkg.name}} string substitution

- pkg/build/testdata/goldenfiles/sboms/7zip-two-fetches-2301-r3.spdx.json
- pkg/build/testdata/goldenfiles/sboms/crane-0.20.2-r1.spdx.json
- pkg/config/config.go
There is logic bug interating all the copyright stanzas which always
appened a single "/n" into the copyrightText field of the SBOM
package.
The SPDX spec says that empty or whistespace only value should be
treated same as "NOASSERTION" when no determination was possible to
reach, or it was not attempted, or intentionally is not being
provided. However it is better to use "NOASSERTION" value to convey
this more exactly precise meaning.
See:
- https://spdx.github.io/spdx-spec/v2.3/package-information/#717-copyright-text-field
- https://spdx.github.io/spdx-spec/v3.0.1/model/Software/Properties/copyrightText/
Fixes: https://github.com/chainguard-dev/internal-dev/issues/8822
> sbom: update copyrightText from "/n" to "NOASSERTION"

- pkg/build/pipelines/patch.yaml
- This PR adds the flag `--verbose` to the patch command. Nowadays it is a bit hard to debug any issues whenever a patch pipeline fails, e.g. `Hunk #1 FAILED at 14`.  Those errors are cryptic and sometimes even misleading to what is the root cause. As a consequence I decided to propose to use the `--verbose` flag by default so anyone could get additional information whenever a patch fails on our packages.
Notes:
This is the output of a `--verbose` flag set for and a successful execution:
```
2025/01/27 15:47:21 INFO | uses=patch
2025/01/27 15:47:21 INFO |diff --git a/frontend/server/package.json b/frontend/server/package.json uses=patch
2025/01/27 15:47:21 INFO |index 8395b2c49..8b21a4eb1 100644 uses=patch
2025/01/27 15:47:21 INFO |--- a/frontend/server/package.json uses=patch
2025/01/27 …
```
> patch: add --verbose flag to patch pipeline

- pkg/build/pipelines/patch.yaml
- This change exposes the flag `--fuzz` from the patch pipeline so anyone could set its value to `0` or any other value. Otherwise it defaults to its original value `2`.
```
Sets the maximum fuzz factor. This option only applies to context diffs, and causes patch to ignore up to that many lines in looking for places to install a hunk. The default fuzz factor is 2.
```
> patch pipeline: expose fuzz flag so we can set a different value

- pkg/build/pipelines/npm/install.yaml
add `npm` to `npm/install` pipeline given it's required.
> add npm to npm/install pipeline

- pkg/build/test_test.go
- pkg/config/config.go
This change adds the build user as a default to the Test pipeline environments; without this change the qemu runner does not successfully make its ssh initial connection to the qemu microvm to get the VM's host ssh public key; see https://github.com/chainguard-dev/melange/issues/1732 which this PR is intended to resolve.
It changes the emitted apko config for test pipelines to include:
```yaml
accounts:
runas:  
users:
- uid=1000(build) gid=824637199472
groups:
- gid=1000(build) members=[build]
```
Fixes #1732
Notes:
I have not rebuilt the world with this, but attempts to rebuild and run the test pipelines random packages (systemd, openjdk, and some others) in a variety of runners with this change have not shown breakage.
> Add build user to test pipeline environments

- pkg/build/test_test.go
> Cast GID pointer to apko_types.GID in test_test.go

- pkg/build/build_test.go
- pkg/build/test_test.go
- pkg/config/config.go
This PR controls the build user/group string from only two places rather than hard-coding the value in several places.
> Consolidate build user/group strings

- .gitignore
- docs/md/melange.md
- docs/md/melange_rebuild.md
- pkg/build/pipelines/README.md
- pkg/build/pipelines/cargo/README.md
- pkg/cli/commands.go
- pkg/cli/rebuild.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/schema.json
This adds a new top-level command, `melange rebuild`, which takes an existing APK (or multiple), and extracts the `.melange.yaml` and `.PKGINFO` embedded in the control section, and uses it to build the package again from locked inputs.
The intention is that we would be able to tell _whether_ package builds are reproducible when built with all the same config and versions of the tools that were originally used, and if they're not reproducible, _how_.
Initial tests are promising!
To rebuild our `crane` package:
```
$ go run ./ rebuild <(curl -sL https://apk.cgr.dev/chainguard/x86_64/crane-0.20.3-r2.apk)
```
Its `crane` binary has the same digest as the original package:
```
$ tar -Oxf x86_64/crane-0.20.3-r2.apk usr/bin/crane | sha256sum - …
```
> new command: rebuild

- pkg/cli/rebuild.go
With this change:
```
$ go run ./ rebuild <(curl -sL https://apk.cgr.dev/chainguard/x86_64/crane-0.20.3-r2.apk)
$ diff \
<(tar -Oxf x86_64/crane-0.20.3-r2.apk var/lib/db/sbom/crane-0.20.3-r2.spdx.json) \
<(curl -sL https://apk.cgr.dev/chainguard/x86_64/crane-0.20.3-r2.apk | tar -Ox var/lib/db/sbom/crane-0.20.3-r2.spdx.json)
8c8
<       "Tool: melange (devel)",
---
>       "Tool: melange (v0.19.4)",
```
This should go away if I was using melange 0.19.4 to rebuild, which of course I'm not. Once a version of melange is released with `rebuild` and is used to build packages, this diff should disappear 🪄 
Diffs to rebuilt file owner groups and `.melange.yaml` still persist.
> rebuild: make SBOM more reproducible

- pkg/build/pipelines/go/README.md
- pkg/build/pipelines/go/build.yaml
The extra-args input variable for the go/build pipeline should allow to specify extra arguments to be passed to the go build command.
Notes:
Notes:
Notes:
> feat(pipelines/go/build): add extra-args input variable

- .github/workflows/e2e.yaml
- examples/minimal.yaml
- pkg/cli/rebuild.go
- pkg/config/config.go
This demonstrates that minimal no-op builds produce reproducible packages, with no diffs to metadata, filesystem, or melange config.
The only functional change to existing code is that adding the build user won't add it again if it's already specified.
Having this stake in the ground, we can detect future changes that inadvertently break reproducibility. We can also expand the set of configs that are checked for reproducibility and hopefully fix breaking issues in built in build pipelines, like `go/build`.
> rebuild: add e2e test

- pkg/build/build.go
- pkg/linter/linter.go
- pkg/linter/linter_test.go
We didn't have access to know if the test/pkgconf pipeline was present in the package definition, so we've plumbed the package configuration around to all the linter functions so we can avoid warning in cases where the package is actually doing the right thing already.
In a future change we can make this fatal once we fixed everything that would fail this lint.
This also sets us up to fix a TODO in the empty linter.
> Fix pkgconf lint

- .gitignore
- e2e-tests/README.md
- e2e-tests/greeter-build-test.yaml
- e2e-tests/run-tests
*  Add support in e2e-tests for melange build and then test.
Now a yaml file in this directory named '*-build-test.yaml'
will have 'melange build' run and then 'melange test'.
Add creation of a signing key and ignore it in git-ignore.
*  add greeter-build e2e-test that does build and test.
> Add support in e2e-tests for melange build and then test.

- .github/workflows/e2e.yaml
- README.md
- pkg/build/pipeline.go
- pkg/config/config_test.go
- pkg/config/vars.go
Many of the places where subpkg.name is used now would be even nicer with a context-specific name.
Ie, we have this stanza in wolfi lots of times:
uses: test/ldd-check
with:
packages: ${{subpkg.name}}
But if we changed the default in test/ldd-check to be 'context.name' then we could replace those with:
uses: test/ldd-check
> Add ${{context.name}} string substitution

- .github/workflows/e2e.yaml
- pkg/build/build.go
- pkg/build/compile.go
- pkg/build/compile_test.go
- pkg/build/options.go
- pkg/cli/rebuild.go
- pkg/cli/scan.go
- pkg/linter/linter.go
Prior to this change `build.New`'s options only accepted a config file path, which it would parse and use. The filename of the config is passed to the SBOM.
This complicated `rebuild` which doesn't have a real file path to rebuild, but it wanted to populate the same file path to be able to rebuild reproducibly.
With this change, `build.WithConfiguration(cfg, filename)` populates the pre-parsed config struct, and populates the filename to report in the SBOM, which is a little disingenuous, but 🤷.
I suspect there are lots of places where we call `build.New` with a temp file just to be able to pass it to `build.WithConfig(tmpfile)`, which we no longer need to do. If we find them, we can clean them up and maybe hopefully deprecate `WithConfig`.
I'm not married to the name …
> rebuild: populate Config directly without file

- pkg/build/package.go
- pkg/config/config.go
- pkg/config/config_test.go
This draft PR is trying out an idea where a package's build config could specify its own CPE values. Today our scanning system maintains its own list of known CPEs for packages with certain names. But perhaps it's better if each package is capable of defining the correct CPE on its own (if it has a CPE), which would remove the need for us to keep a central list up to date.
Improving CPE identification for packages will help us find CVEs for packages better (specifically, by improving recall) because it's not always possible to derive the correct CPE just from the package's other metadata.
Example of how this might look for cosign, for example:
```yaml
package:
name: cosign
version: 2.4.1
epoch: 5
description: Container Signing
cpe:
vendor: sigstore
product: cosign
copyright:
- license: …
```
> feat: build config can specify package CPE

- .github/workflows/verify.yaml
- Makefile
- pkg/build/pipelines/go/README.md
This commit adds a make target to generate documentation for pipelines. It also makes it run during the verify github workflow, alongside the generation of documentation of melange itself.
> chore(docs): automatic generate pipeline docs

- pkg/build/pipelines/llvm/README.md
- pkg/build/pipelines/llvm/covreport.yaml
It produces a statements by functions based-coverage percentage report via llvm-profdata merge and llvm-cov report as summary. It requires the produced binary to be instrumented for coverage using the ‘llvm.instrprof.increment’ Intrinsic [1].
For instance:
```diff
diff --git a/helix.yaml b/helix.yaml
index e6e94fa50..9922e4737 100644
--- a/helix.yaml
+++ b/helix.yaml
@@ -25,6 +25,7 @@ pipeline:
- name: Build
uses: cargo/build
with:
+      rustflags: "-C instrument-coverage"
opts: --locked --profile opt
output-dir: target/opt
output: hx
@@ -51,3 +52,7 @@ test:
- uses: test/ldd-check
with:
packages: ${{package.name}}
+    - uses: llvm/covreport
+      with:
+        # Exclude the sources for dependencies from the coverage results.
+        ignore-filename-regex: /.cargo/registry
```
> In …
> feat(build/pipelines): add llvm/covreport

- Makefile
- pkg/build/sign.go
- pkg/sign/apk_test.go
This removes support for creating SHA-1 signatures via melange.
Similar removal is done in apko at:
- https://github.com/chainguard-dev/apko/pull/1496
> sign: drop support for creating SHA-1 signatures

- pkg/build/pipelines/go/covdata.yaml
This PR adds the missing `jq` runtime dependency for the pipeline to work, in order to parse the statements by function coverage profile generated by the go tool covdata.
> fix(pkg/build/pipelines/go/covdata.yaml): add jq dep

- README.md
Since I'm still learning Wolfi packaging I find myself wanting to know what keys can go in a .yaml file and trying to remember when I can use what where. Instead of grep'ing all the yaml files in Wolfi it'd be better if there was a central place to look up the answer. README.md seemed to have a lot of the possibilities so I added some more.
> Expand the sample yaml in README

- docs/md/melange_build.md
- docs/md/melange_lint.md
- pkg/linter/linter.go
- pkg/linter/linter_test.go
Notes:
I don't have a just newest copy of wolf packages locally but the failures I see are all packages we've replaced.
```
❯ melange lint packages/aarch64/wolfi-baselayout-20230201-r18.apk 
2025/03/10 14:48:58 INFO Required checks: [dev infodir tempdir usrmerge varempty]
2025/03/10 14:48:58 INFO Warning checks: [lddcheck object opt pkgconf python/docs python/multiple python/test setuidgid srv strip usrlocal worldwrite]
2025/03/10 14:48:58 INFO linting apk: wolfi-baselayout (size: 14 kB)
2025/03/10 14:48:58 WARN linter "usrlocal" failed on package "wolfi-baselayout": /usr/local path found in non-compat package: usr/local/lib64; suggest: This package should be a -compat package
```
```
❯ melange lint packages/aarch64/util-linux-misc-2.40.1-r0.apk 
2025/03/10 15:09:37 INFO Required checks: …
```
> linter: update usrmerge and make it required

- pkg/sca/sca.go
Both luajit and fluent-bit provide `cmd:luajit`. The `luajit` implementation for fluent-bit is specific to fluent-bit. `cmd:luajit` currently resolves to fluent-bit instead of luajit. A change in priority isn't enough as `cmd:luajit` will resolve to whatever's found first that satisfies the dependency (at the moment, that's fluent-bit)
Require that we're explicit with what we want here
This change does not impact any current packages in Wolfi
> fix(sca): Don't generate dependency on luajit

- .github/workflows/wolfi-presubmit.yaml
- go.mod
- pkg/build/build.go
- pkg/container/bubblewrap_runner.go
- pkg/container/qemu_runner.go
#1836 allowed xattrs to work for QEMU but broke xattrs for Bubblewrap and Docker. This PR stores any xattrs in the workspace directory prior to the in-memory filesystem being created and then applies them to the new filesystem afterward.
I tested this with all three runners and it seemed to work, though QEMU errored during extraction which is expected:
```
usr/sbin/fping
tar: setxattrat: Cannot set 'security.capability' extended attribute for file 'usr/sbin/fping': Operation not supported
```
This PR does not fix `getcap` tests in pipelines, but I'm not sure if that ever worked regularly or not. For example the fping `getcap` test shows nothing on `v0.22.2` prior to the QEMU changes:
```
2025/03/24 22:38:25 INFO running step "Test file capabilities"
2025/03/24 22:38:25 WARN + '[' -d …
```
> Store and apply xattrs correctly for all builds

- examples/fetch-directory.yaml
- pkg/build/pipelines/README.md
- pkg/build/pipelines/fetch.yaml
Howdy all 👋 I used https://github.com/chainguard-dev/melange/pull/1792 as a meter stick to compare this change against for conventions, etc. Next steps for me are:
Notes:
Notes:
Notes:
👶🍼 This is my first contribution to `melange`, first time using it to build wolfi, etc. Your patience as I work through the checklist is appreciated 🙏
> Add `directory` parameter for `fetch` to be passed to `tar -C`

- .github/workflows/e2e.yaml
- examples/npm-install.yaml
- examples/pnpm-install.yaml
- pkg/build/pipelines/npm/README.md
- pkg/build/pipelines/npm/install.yaml
If users want to use `npm/install` with `pnpm`, they can do so with `npm-package: pnpm` -- the existing behavior to use `npm` remains the default.
This change also adds `npm-install.yaml` and the new `pnpm-install.yaml` examples to our e2e rebuild test, which exposed a reproducibility-breaking change in `pnpm` when using `overrides` (disabled so it doesn't block the PR, just FYI)
To help debug rebuild tests, I refactored e2e.yaml a bit so it uploads the original and rebuilt APKs for local inspection.
> npm/install: allow using pnpm instead

- .github/workflows/e2e.yaml
- examples/cargo-build.yaml
- examples/pnpm-install.yaml
- pkg/cli/rebuild.go
This adds a `rebuild --diff` flag (default `true`) that checks the just-rebuilt package for diffs against its original.
If there are diffs to `.PKGINFO`, `.melange.yaml` or the SBOM, those diffs are printed out, otherwise if a path has a different digest, only the path+digest is printed in the error.
This changes CI e2e to _only_ test build+rebuild scenarios, since they were mostly the same as those in the old `e2e` job -- this will require changes to our required checks.
This also drops the `rebuild --arch` flag, since it can detect the arch of the original package and use that.
This also "handles" (by ignoring) packages which are subpackages, which we'll want to fix in a future change. Attempting to rebuild a subpackage will warn and exit successfully for now.
> check diff after rebuilding

- examples/cargo-build.yaml
- examples/minimal.yaml
- pkg/cli/rebuild.go
In the last change, we'd just skip subpackages.
With this change, we'll rebuild a subpackage (effectively rebuilding its origin and all of its subpackages), and skip re-rebuilding other subpackages that share the same origins.
The intention is that if you `melange rebuild sub-a.apk origin.apk, sub-b.apk`, we'll:
1. rebuild `sub-a.apk` (effectively rebuilding `origin` and all its subpackages))
a. diff `sub-a.apk` vs `./rebuilt-packages/sub-a.apk`
2. _not_ rebuild `origin.apk` (since it's already built)
a. diff `origin.apk` vs `./rebuilt-packages/origin.apk`
3. _not_ rebuild `sub-b.apk` (since it's already built)
a. diff `sub-b.apk` vs `./rebuilt-packages/sub-b.apk`.
Moved example subpackages from `examples/cargo-build.yaml` to `examples/minimal.yaml`.
> rebuild: support subpackages

- e2e-tests/ipset-build-test.yaml
- pkg/linter/linter.go
- pkg/linter/linter_test.go
Notes:
We've just usrmerged all of /usr/sbin in Wolfi.
Example run of select packages:
```
amelia-crate@amelia-crate-16 ~/w/packages> ~/work/melange/melange lint wolfi-baselayout-20230201-r20.apk
2025/03/31 13:36:44 INFO Required checks: [dev infodir tempdir usrmerge varempty]
2025/03/31 13:36:44 INFO Warning checks: [lddcheck object opt pkgconf python/docs python/multiple python/test setuidgid srv strip usrlocal worldwrite]
2025/03/31 13:36:44 INFO linting apk: wolfi-baselayout (size: 13 kB)
2025/03/31 13:36:44 WARN linter "usrlocal" failed on package "wolfi-baselayout": /usr/local path found in non-compat package: usr/local/lib64; suggest: This package should be a -compat package
amelia-crate@amelia-crate-16 ~/w/packages> ~/work/melange/melange lint wolfi-baselayout-20230201-r19.apk …
```
> linter: update usrmerge to include /usr/sbin

- .gitignore
- pkg/build/build.go
- pkg/build/cache.go
- pkg/build/test.go
- pkg/cli/rebuild.go
Previously every time we'd tested `melange rebuild` it was just after we `melange build`ed, which meant we had the original config.yaml there.
When we don't, like when we `melange rebuild $WOLFI/packages/aarch64/foo.apk`, we might not have the original config _file_, but we will have the original config _struct_.
To rebuild reproducibly you still need the original private key though, if the package you're rebuilding is signed.
You also need the original `--source-dir`, so let's also add the `--source-dir` flag.
> rebuild: don't require original file to rebuild

- pkg/linter/linter.go
/usr/sbin will trigger a failure if found; include in the error message if this is the case.
> Improve failure message for usrmerge linter

- .github/workflows/wolfi-presubmit.yaml
Bump epochs prior to building new packages, such that just rebuilt
packages are tested later on.
During apk installability tests, pass through the full registry of
packages such that they can resolve any new dependants, when needed.
This should fix CI when making invasive SCA changes.
> github: fixup presubmit workflow

- pkg/build/test.go
In our Makefiles we currently need to manually create the source directory if it doesn't exist.  If we forget to do that, melange will segfault (see
https://github.com/chainguard-dev/extra-packages/pull/2165 for an example of such case).
melange can do better here and create the missing source directory by itself, so that's what this commit does.
Relates: https://github.com/chainguard-dev/extra-packages/pull/2165
> test.go: Invoke `apkofs.DirFS` with option to create dir if missing

- .github/workflows/wolfi-presubmit.yaml
- pkg/build/pipeline.go
Stock default PATH variables are widely documented. Unfortunately
setting PATH in the envFile passed to melange yields no effect, as
pipeline overrides start with a PATH provided. It is understandable,
as the PATH set here is more comprehensive and in a better order than
the one built-into busybox ash (quiet unusual order, and lacks
/usr/local).
On the other hand programs and users get confused when the canonical
location of the binaries, is not the one discovered by PATH.
Without breaking existing workflows, and ability to keep building
pre-usrsbinmerge package repositories, reorder the default pipeline
PATH slightly. Specifically ensure that `/usr/bin` leads before
`/sbin`, `/usr/sbin`, `/bin` locations. This way discovery of binaries
in the post usrsbin-merge world will find the …
> sbin-merge: reorder default pipeline path

- e2e-tests/git-checkout-build.yaml
- e2e-tests/run-tests
- pkg/build/pipelines/git-checkout.yaml
This commit adds explicit `--no-same-owner` to tar extraction of
the git repository to the destination directory, which in most
of the cases is the Melange workspace.
--no-same-owner option makes:
>Extract files as yourself (default for ordinary users).
which means that when the Melange runner is root, ownership
of existing files is overwritten when the option is not set.
When the git-checkout pipelines extracts the content of the
git repositories locally from the temporary directory to the
destination directory [1], which is usually the Melange pipeline
workspace (/home/build inside the runner container), does not
preserve ownership of the directories that already existed in
the destination directory.
When the runner user does not match the user who runs Melange,
this ends up in …
> fix(pipelines/git-checkout): preserve ownership of existing files

- pkg/sca/sca.go
This PR adds `/usr/local/bin` and `/usr/local/sbin` to the paths considered when generating shbang dependencies and drops `/bin` which is no longer used.
> Include /usr/local paths in generateShbangDeps; drop /bin

- pkg/build/pipelines/cmake/build.yaml
This will make it easier to debug failures.
Signed-off-by: dann frazier <dann.frazier@chainguard.dev>
> pipelines: cmake/build: Use verbose mode by default

- .github/workflows/wolfi-presubmit.yaml
- pkg/build/build.go
#1867 fixed xattrs for bind mounts but did not address mode bits.
@sergiodj pointed out that building the `sudo` package no longer showed the `setuid` bit being set and @astrojerms also encountered the same thing with the `fixuid` package.
This PR stores the mode bits of files within `melange-out` and sets them appropriately similar to xattrs.
I tested these changes in Docker with `fixuid` and it looks like the bits are being persisted correctly now (previously only QEMU worked):
```
Building package fixuid with version fixuid-0.6.0-r0 from file fixuid.yaml
/Library/Developer/CommandLineTools/usr/bin/make yamlfile=fixuid.yaml pkgname=fixuid packages/aarch64/fixuid-0.6.0-r0.apk
@SOURCE_DATE_EPOCH= .../melange build fixuid.yaml --runner=docker --repository-append .../wolfi-dev/os/packages …
```
> Fix mode bit persistence for bind mounts

- pkg/build/pipelines/ruby/clean.yaml
We don't need them and they're causing reproducibility isuses.
```
❯ diff (curl -sL https://packages.wolfi.dev/os/aarch64/ruby3.2-date-3.4.1-r0.apk | tar -t | psub) (tar -tf ./package
s/aarch64/ruby3.2-date-3.4.1-r0.apk | psub)
0a1
> .SIGN.RSA256.local-melange.rsa.pub
1a3
> .melange.yaml
15,16d16
< usr/lib/ruby/gems/3.2.0/extensions/aarch64-linux-gnu/3.2.0/date-3.4.1/gem_make.out
< usr/lib/ruby/gems/3.2.0/extensions/aarch64-linux-gnu/3.2.0/date-3.4.1/mkmf.log
```
> pipelines/ruby/clean: remove build logs

- pkg/config/config.go
- pkg/config/schema.cue
- pkg/config/schema.json
- pkg/convert/apkbuild/testdata/no_sub_packages.yaml
- pkg/convert/apkbuild/testdata/with_multi_sub_packages.yaml
- pkg/convert/apkbuild/testdata/with_unrecognised_sub_packages.yaml
Most of these are not treated as required by tooling, this is just updating the
metadata and regenerating the schema.
I found testing out cue and the vet feature on wolfi using the config schema.json
we generate here.
Including the cue file as an example for the draft but if it's not removed
it should be auto generated.
> config.go: Update optional annotations for schema.json generation

- pkg/build/build_test.go
- pkg/build/test_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- ParseConfiguration does NOT propagate the `Range` field on the subpackages when set on the yaml definition.
> fix: propagate Range field of subpackages

- pkg/build/build.go
- pkg/config/config.go
- pkg/config/config_test.go
This PR picks up the ideation from #1902 and adds support for declarative capabilities. This will [hopefully] avoid permissions issues via `setcap` and is a more controlled way of handling what is generally a rare occurrence.
Capabilities can be set one per line or on a single line and will look like this:
```yaml
package:
name: fping
version: "5.3"
epoch: 40
description: A utility to ping multiple hosts at once
copyright:
- license: GPL-2.0-only
dependencies:
runtime:
- merged-usrsbin
- wolfi-baselayout
setcap:
- path: /usr/bin/fping
add:
cap_net_raw: "+ep"
reason: "cap_net_raw is needed if not using root or the setuid bit"
...
```
Multiple capabilities can be added one per line:
```yaml
setcap:
- path: /usr/bin/fping
add:
cap_net_raw: "+ep"
cap_net_admin: "+ep"
reason: "cap_net_raw and …
```
> Add support for declarative file capabilities

- pkg/build/pipelines/ruby/clean.yaml
If the install location is customized at all, these find commands will fail and cause the build to exit. Wrapping it in a validity check is a simple way to prevent this from failing outright. This can be seen in ruby-rails packages like [ruby3.4-rails-7.2 for example ](https://github.com/chainguard-dev/enterprise-packages/blob/488a49accda28c6205fe5e83773c8d778ffd9849/ruby3.4-rails-7.2.yaml#L48-L51). As well as[ where this will fail in CI](https://console.cloud.google.com/logs/query;query=logName%3Dprojects%2Fprod-wolfi-os%2Flogs%2Fstderr%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22elastic-pre-a%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.namespace_name%3D%22pre-wolfi%22%0Alabels.%22k8s-pod%2Fmelange_chainguard_dev%2Fbuild-id%22%3D%2200d …
> Validity check to prevent builds failing when the install location is customized

- pkg/build/build.go
- pkg/config/config.go
- pkg/config/config_test.go
Follow-up for #1938. There were a few gaps since the tests weren't emulating what the runners actually do (it'll be nice to have a real testcase now that we're parsing the capabilities correctly as of this PR). The path also wasn't correct and the path is different depending on the runner.
I tested these changes with Bubblewrap and QEMU and was able to set capabilities without privilege, though testing still requires privilege.
Setting via QEMU:
```
2025/04/23 21:19:19 INFO retrieving workspace from builder:
[1 0 0 3 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] // debug output
2025/04/23 21:19:19 INFO fetching remote workspace
setting xattr security.capability on melange-out/fping/usr/bin/fping
```
Setting via Bubblewrap:
```
2025/04/23 21:21:51 INFO retrieving workspace from builder:
[1 0 0 …
```
> Update declarative capabilities; add functionality to set within QEMU

- pkg/build/build.go
Relates to #1940. #1836 removed the xattr allowlist which filtered out specific xattrs that require additional permissions to set when testing/installing packages.
This PR re-adds the allowlist to restore the original behavior.
> Re-add xattr allowlist from readlinkFS

- pkg/build/build.go
- pkg/config/config.go
- pkg/container/config.go
- pkg/container/qemu_runner.go
Right now, we automatically try to use a microVM for QEMU builds which may not work in all cases. This PR adds a configuration option to control whether to use microVM as well as the ability to override said option via an environment variable.
The new configuration option defaults to false, so we'll use `-virt` by default (unless we want to default to `true` like we did originally and then rely on opting out).
If there's a better way of thinking about this I'm definitely open to suggestions.
It's also hard to debug boot issues with QEMU, so this PR implements @89luca89's suggestions to asynchronously start up the VM and then capture logs which can be viewed with `--log-level debug` (and warnings will be displayed separately).
> Add config/env var support for microVM usage; display boot logs in debug

- pkg/build/build.go
- pkg/container/qemu_runner.go
This changes the QEMU runner to retrieve the full workspace, not just `melange-out`.  This is because the license checker is failing to extract livense files from the workspace.
This also changes the `retrieveWorkspace` logic to allow overwriting files, since we otherwise see issues with files we seeded the workspace with prior to the build.
We see this using the QEMU runner on `db.yaml` and other builds with `license-path` set.
> Retrieve the full workspace.

- pkg/build/build.go
- pkg/config/config.go
- pkg/container/config.go
- pkg/container/qemu_runner.go
This PR makes a few tweaks to the QEMU runner code, namely:
- Increased memory usage instead of capping at 1/4th of the system's memory (we can go lower than 85%, too)
- Relying on a single way to specify microVM usage
- Pedantic change for units
TBD if we can land a fix for using QEMU on baremetal ARM instances.
> QEMU runner tweaks

- pkg/container/qemu_runner.go
This change makes QEMU logging do to info logs by default, but quiets the kernel/init logging unless the log level is set to debug.
> Improve QEMU logging.

- pkg/build/pipeline.go
`filepath.Join` doesn't behave as I, or Gemini, thought.  This adds an explicit check to properly handle when the working directory is absolute.
> Fix absolute path handling.

- pkg/license/license.go
- pkg/license/license_test.go
Currently `melange license-check` will report that there's a lot of ignored licenses, due to a typo in code. Let's fix that and add a test for this particular case.
> Fix typo in license reporting re: ignored results.

- .github/workflows/wolfi-presubmit.yaml
- pkg/container/qemu_runner.go
Fifos when compressed/extracted won't work anyway and they are usually problematic (see dpkg package)
> fix: exclude fifos in WorkspaceTar

- docs/md/melange_test.md
- pkg/build/test.go
- pkg/build/test_options.go
- pkg/cli/test.go
This flag seems to have been forgotten while implementing `melange test`. There's already a field for it in `type Test struct` but it's not populated or read.
This adds `--ignore-signatures` to `melange test`, and passes it through to the apko build to produce the test environment.
> test: add --ignore-signatures

- .github/workflows/wolfi-presubmit.yaml
- pkg/build/build.go
- pkg/build/test.go
- pkg/container/bubblewrap_runner.go
- pkg/container/bubblewrap_runner_test.go
- pkg/container/config.go
- pkg/container/docker/docker_runner.go
- pkg/container/qemu_runner.go
- pkg/container/runner.go
With this we adapt to the equivalent branch of 89luca89/os this way we use this minimal initramfs to unpack the rootfs.tar.gz mounted to /dev/vdb into /mount, and then use SSHD's ChrootDirectory to chroot into it
This solves the following problem:
- multiple compression/decompression cycle of the rootfs, hence a big performance improvement
- we now use `layer.Uncompressed()` which is the same as bubblewrap runner now.
- removes the ~2gb limit for the initramfs as now we're using the disk
- cpio initramfs is now cache-able, so for local development things are also faster
- removes need of SSHD inside the build environment
- migrates to use SSHD's `ChrootDirectory` to enter the build environment (avoid access at build time to vmlinuz modules sshd binary etc)
- removes extra files in the …
> experiment: on the fly disk for melange QEMU runner

- pkg/build/build.go
- pkg/container/config.go
- pkg/container/qemu_runner.go
When using QEMU runners we were forced to add gnutar/attr packages to the build environment in order to copy back the workspace outputs.
With the new version of the microvm init, we can instead use the alternative SSHD port, that avoid chrooting into the build environment.
This will let us use the initramfs packages instead of injecting them into the build environment.
Depends on:
> feat: avoid adding additional packages on QEMU runners

- pkg/build/build.go
- pkg/container/qemu_runner.go
Add some output to tar generation
Make sure that parent directory of unpacked files exists
> fix: ensure make parent dirs when unpacking files from workspace

- pkg/build/testdata/goldenfiles/sboms/7zip-two-fetches-2301-r3.spdx.json
- pkg/build/testdata/goldenfiles/sboms/crane-0.20.2-r1.spdx.json
- pkg/config/config.go
- pkg/sbom/package.go
For packages that related to fetch and git-checkout actions in build pipelines populate the downloadLocation and checksums fields alongside the purl's that are already present in externalRefs.
Download location is either a URL or a Vcs reference as defined in the SPDX specification.  Checksums are provided for both types.
[SPDX reference for examples](https://spdx.github.io/spdx-spec/v2.3/package-information/#773-examples)
> sbom: Populate downloadLocation and checksums

- .github/workflows/wolfi-presubmit.yaml
- pkg/container/qemu_runner.go
Default to use 85% or available memory and all CPU cores. If a resource snippet is declared, it will be treated as an upbound limit for resources.
Fixes: https://github.com/chainguard-dev/prodsec/issues/143
> fix: improve QEMU resource limits handling

- pkg/container/qemu_runner.go
- pkg/license/license.go
- pkg/license/license_test.go
We have recently added license-checking to the build pipeline, running our license identification against the build workspace to come up with what licenses are present in the source.
This works fine for bubblewrap as the workspace directory operates via bind mounts, but for qemu, the workspace is on the qemu disk and we only get the artifacts via `retrieveWorkspace()` - which only syncs the `melange-out/` dir + any other files we explicitly ask for. So licensing checks can't run properly, as they need the source from the workspace for analysis.
Modify the qemu runner to fetch all the license related files and copy them over as part of `retrieveWorkspace()`.
> license-check: fix running checks for builds using qemu

- pkg/config/config.go
Ensure the correct checksum is used when generating downloadLocation checksums.
> sbom: pass SHA512 not SHA256 when in use.

- pkg/container/qemu_runner.go
- pkg/license/license.go
- pkg/license/license_test.go
This way we ignore huge number of files that are not actually part of the source
Fixes: https://github.com/chainguard-dev/prodsec/issues/156
> fix: add ignore paths to license files

- .github/workflows/wolfi-presubmit.yaml
- pkg/build/test.go
- pkg/container/config.go
- pkg/container/qemu_runner.go
Instead of using session.Run() we use session.Shell() and use session.Stdin to "write" the command in it.
Also, deduplicate clients, and only keep them as singletons.
Makes it more resilient to random EOFs
Avoid leaking qemu processes, kill by pid if things go wrong
Fix: https://github.com/chainguard-dev/prodsec/issues/170
> fix: improve SSH command handling

- pkg/container/qemu_runner.go
- pkg/container/qemu_runner_test.go
The old approach was getting total memory, which caused errors on my mac. This passes locally now!
Notes:
Notes:
Notes:
> Fix detection of available memory.

- pkg/container/qemu_runner.go
Fix: https://github.com/chainguard-dev/prodsec/issues/151
> fix: try to remove Wired memory for MacOS sizing

- pkg/container/qemu_runner.go
When using the qemu runner with the debug build option, the user's public ssh key is supposed to get appended to the guests authorized_keys files, but attempts to use this were failing with:
```
root@localhost: Permission denied (publickey,keyboard-interactive).
```
Examining what melange was injecting into the guest's authorized keys file, the user's public key contained a trailing newline character; e.g.:
```
wolfi-vm:~# cat .ssh/authorized_keys
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDhcpdU0le62vuZ5K6MSe+ywqZBUY6FFcIA6iklvUFwRVfXh7Gh7zDYRSMc5JydcCju9oSxml4YocCWbddOF7m8=
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEMVW0YujhFd5iaIf15QAdQv8YeS3v/F+P+pN10qi4Fg\n
```
Fix this by trimming space/newlines on the stringified public key before injecting it into the …
> qemu runner: fix embedded authorized key when debugging

- .github/workflows/wolfi-presubmit.yaml
- pkg/container/qemu_runner.go
We're currently excluding `fifo` files by name which is preventing certain legitimate files and directories that are needed in the emitted APK.
This PR deletes any named pipe files before we try to archive the workspace instead of potentially excluding valid directories or files.
> Delete named pipes instead of broadly excluding fifo files

- pkg/build/build_integration_test.go
- pkg/build/testdata/build_configs/bogus-version.yaml
- pkg/cli/build.go
As described in https://github.com/chainguard-dev/apko/issues/1704 , There are some packages that have gotten into the archive with versions that apko cannot parse.
This change makes melange error if it sees a version that cannot be parsed.
> Error if a package version is not parseable by apk.ParseVersion

- pkg/container/qemu_runner.go
Right now to fetch extra files from the workspace (mainly licenses) we simply append the list of files to the `tar` command.
This will lead to "-ash: sh: Argument list too long" for cases where the list of arguments surpasses `MAX_ARG_STRINGS`
Instead we write the list to a file, and use the `-T/--files-from` option in order to populate the tar from that list. To avoid network problems, also the streaming of the list is divided in small chunks.
> fix: avoid sending huge command when fetching extra files from workspace

- docs/VAR-TRANSFORMS.md
- pkg/renovate/bump/bump.go
Prior to this commit, bumps updated `expected-commit` for any git checkout node who's `tag` attribute matched the regular expression `\${{vars\..+}}` (i.e. anything which used a variable).
This made the logic very greedy, clobbering values for unrelated checkouts (for example [here](https://github.com/wolfi-dev/os/pull/52449/commits/4bc6632241cd0487b22349344dcea4c25647ef7d))
We only want bumps to update those where `tag` matches either `package.version` or `vars.mangled-package-version`. 
Currently we use the following vars in `tag` attributes:
```
ben@cosmos:~/Repos/os$ grep -h 'tag: ${' *.yaml | grep -v 'package\.version' | cut -d: -f2 | sort | uniq
${{vars.docker-machine-tag}}
${{vars.exporter-tag}}
${{vars.mangled-package-version}}
```
It also adds a check to ensure that …
> fix: make checkout expected-commit bump less greedy

- .github/workflows/melange-test-pipelines.yaml
- e2e-tests/capabilities-add-drop-build.yaml
- e2e-tests/capabilities-add-drop-nopkg-test.yaml
- e2e-tests/git-checkout-build.yaml
- e2e-tests/greeter-build-test.yaml
- e2e-tests/run-tests
This PR sets the QEMU runner as the default runner for e2e tests for pipelines.
It uses the Alpine kernel, the same way we do for the Wolfi presubmit CI workflow.
Notes:
Notes:
Notes:
> test(e2e/pipelines): run tests on qemu runner

- pkg/cli/scan.go
We defer a bunch of Close() calls to clean up temporary directories, but defers aren't executed if you call os.Exit, so these were leaking when using the --diff flag.
Instead, just return an error, which will still exit with an error code of 1, but only after running the clean up defers.
> scan: Return an error instead of os.Exit(1)

- pkg/cli/license_check.go
A really small bugfix - currently if you run `melange license-check ./` when in a source directory, for instance, the command will fail. It's fine for yaml and apk files, but not source directories. This fixes it.
> license-check: allow relative paths for extracted-source paths

- pkg/renovate/copyright/copyright.go
- pkg/renovate/copyright/copyright_test.go
The recently added `melange license-check --fix --format=simple` was not doing what it was supposed to: the generated license string was not properly added as a `license:` field. This PR fixes that.
> license-check: fix --format=simple

- e2e-tests/env-vars-build-test.yaml
- e2e-tests/run-tests
- pkg/build/build.go
- pkg/build/test.go
Currently, we only include the contents of `imgcfg.Environment` which looks specifically at a test's environment variables; however, this will ignore top-level environment variables that may be needed by the tests and this is usually just an empty map.
This PR adds the contents of `t.Configuration.Environment.Environment` to `cfg.Environment` for tests and then adds the contents of `imgcfg.Environment` afterward to include any test-specific environment variables that may take precedence over the top-level values.
For example,
```
environment:
environment:
FOO: bar
...
test:
pipeline:
- runs: |
echo $FOO
```
will not display anything (and the same goes for sub-package tests).
Using the new e2e example:
```
2025/07/15 12:17:32 INFO running the main test pipeline
2025/07/15 12:17:32 INFO + …
```
> Include top-level environment variables in tests

- pkg/build/build.go
- pkg/build/test.go
- pkg/cli/license_check.go
- pkg/license/license_test.go
- pkg/linter/linter.go
We don't need this anymore, and the signature changed to require a context.Context, so I'm just dropping it rather than dealing with that.
> Use os.DirFS over apkofs.DirFS

- pkg/build/build.go
- pkg/build/test.go
- pkg/cli/license_check.go
- pkg/license/license_test.go
- pkg/linter/linter.go
Reverts chainguard-dev/melange#2079
> Revert "Use os.DirFS over apkofs.DirFS"

- pkg/container/qemu_runner.go
We noticed a subtle edge case during builds (not tests) with `session.Stdin` + `session.Shell()` where the commands would hang and cause OOMs.
This PR moves back to `session.Run` which resolves the issue, but TBD if other edge cases will pop up as a result. I know EOFs were a concern previously, but I don't know if there's a solution that satisfies all issues.
As far as I could tell, there was no way to mitigate this ad-hoc in the pipeline. Input/output redirection, subshells, and other combinations thereof didn't seem to make any difference.
> Use session.Run instead of session.Shell

- pkg/sca/sca.go
In addition to not generating runtime dependencies or provides for libcuda.so.1 we also do not want to create them for libnvcuvid.so.1 and libnvidia-encode.so.1.
> Expand check for libraries provided by the host

- .github/workflows/wolfi-presubmit.yaml
- docs/BUILD-FILE.md
- pkg/config/config.go
- pkg/sca/e2e_test.go
- pkg/sca/sca.go
It turns out that this feature uncovered another bug in melange, which
is also being addressed by this commit.
When a package X ships a vendored shared library, and a subpackage Y
links against said library, melange fails to detect that the shlib is
vendored and generates a "depends" for it on Y, which is wrong because
X will never have a "provides" for said library.  I believe we hadn't
come accross this problem before because vendored libraries tend not
to be versioned (i.e., their names end in ".so"), which melange
happily ignored until now.  The underlying cause of this problem is
the fact that melange performs SCA for each (sub)package
independently, without taking into consideration everything that's
being built by the package.
I implemented a way to detect vendored libraries on the …
> SCA: Generate `depends` for shlibs ending in `.so`

- pkg/sca/sca.go
There is no reason to require .so files to be executable and other distributions like Ubuntu do not make their .so files executable. So let's drop that requirement.
I did a melange scan of the archive with this change (details in the linked issue) and the additional provides from this change are minimal and should not cause an issue.
> Do not require .so files to be executable

- .github/workflows/wolfi-presubmit.yaml
- docs/BUILD-FILE.md
- pkg/config/config.go
- pkg/sca/e2e_test.go
- pkg/sca/sca.go
Temporary revert to the previous known working state regarding shlib dependency generation.
> Revert "SCA: Generate depends for shlibs ending in .so" and related commits

- pkg/build/build.go
- pkg/build/test.go
- pkg/cli/build.go
The change here makes test actually output its 'Summarize', and build and test are now show the runner that is used.
example of output is:
```
melange v0.30.7-0.20250814112845-f15c64318984+dirty with runner qemu is testing:
```
> More summarize output info.

- docs/PIPELINES-GO.md
- pkg/build/pipelines/go/README.md
- pkg/build/pipelines/go/bump.yaml
gobump v0.9.2 introduces support for go work vendor; adding support in build pipelines go bump
> feat: go bump - go work vendor

- pkg/container/qemu_runner.go
The commit 4df0da8e ("qemu runner: report kernel version (#2132)") added reporting the kernel version in the QEMU guest, but I somehow managed to overlook that the trailing newline from the version string was being passed along. To fix, strip leading and trailing space before returning the kernel version string.
> qemu runner: strip newline from kernel version
