pkg/build/build.go
pkg/build/pipeline.go

Hello, first of all I'm really excited about this project, really nice to see declarative package builds coming up to Alpine :-)
I know the project is still in the early phases so just reporting few minor issues I encountered while playing with the example locally and also while at it just pushing some local fixes I did. In case they make sense, otherwise feel free to ignore if there are upcoming changes to fix them anyway :)
* add missing wget, help2man packages to the build environment. Not sure how it worked before though, as the build runs in a chroot?
* use a tmp directory for the build directory
* bind-mount /etc/resolv.conf instead of copy but maybe useless change ?
* run build sandbox in PID namespace, but likely other namespaces could be used (user, mount, ..) to lock down the …

example minor issues and possible fixes

---

go.mod
pkg/build/pipeline.go
pkg/build/pipeline_test.go

variables were not being substituted in `evalRun()`, as demonstrated live on @rawkode's stream 😅
ensure variables are being properly substituted by refactoring the code and substituting variables everywhere.  also add regression tests.

fix variable substitution bug

---

examples/gnu-hello.yaml
pipelines/fetch.yaml
pkg/build/build.go
pkg/build/pipeline.go

This is a prerequisite for build options and pipeline conditionals.

pipelines: add input validation and defaults

---

pkg/build/package.go

This is a prerequisite for keyless signatures.

package: modularize APKv2 package generation phases

---

examples/mbedtls.yaml
pipelines/cmake/build.yaml
pipelines/cmake/configure.yaml
pipelines/cmake/install.yaml

This implements tasks to build packages with CMake.

add cmake package building pipelines

---

.github/workflows/build.yaml
.github/workflows/go-tests.yaml
.github/workflows/release.yaml
.github/workflows/verify.yaml

use the recommended way to install the latest go

use the recommended way to install the latest go

---

.github/workflows/add-issues.yaml

updating the action to:
- Retrieve project and custom field details.
- Use issue to create new project item.
- Update custom field date /w created on timestamp.
- Update custom field tent-pole w/ value Images.
- Update custom field issue priority w/ value P2 (default priority of new issues).

updating action to include more steps.

---

pkg/cli/sign.go

Otherwise an index can be signed twice, resulting in `BAD signature` errors from apk.

sign: check if an index is already signed before signing again

---

README.md

Signed-off-by: Priya Wadhwa <priya@chainguard.dev>

Add details for default substitutions and templating to README

---

README.md

Signed-off-by: Adrian Mouat <adrian@chainguard.dev>

Add container usage instructions.

---

README.md

This PR brings a few updates to the README, including debug info and how to generate the apk indexes for manual builds.

Minor updates to the README, including debug info

---

pkg/build/build.go

Persist apko environment key-pairs in pipeline runs

---

.github/workflows/sync-issues-to-project-board.yaml

Signed-off-by: Patrick Flynn <patrick@chainguard.dev>

add project syncer

---

pkg/build/build.go

annotate melange structs to help when marshalling

---

.ko.yaml
README.md
pkg/build/build.go
pkg/build/pipeline.go
pkg/cli/build.go

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-by: Furkan Türkal <furkan.turkal@trendyol.com>
Fixes #157 
/cc @dentrax @kaniini

extend the built-in pipelines with the pipelines within the given diectory

---

go.mod
go.sum
pkg/build/build.go

this is needed to enable metaprogramming in melange YAML files

build: template: allow templater to work without supplied inputs

---

examples/gnu-hello-wolfi.yaml
go.mod
go.sum
pkg/build/build.go
pkg/build/build_test.go
pkg/build/pipeline.go

Building on the work in apko, we expose the triplets to Melange.

Add GNU and Rust triplet support to Melange

---

pkg/build/build.go

It's currently difficult to use native tooling to parse Melange config files, for the reasons cited in #161.
This PR updates Melange to provide a function to lib consumers that handles the parsing of Melange config files, such that other applications can use this for config parsing until #161 is resolved.

Export function for parsing Melange file

---

examples/conditional.yaml
go.mod
go.sum
pkg/build/build.go
pkg/build/pipeline.go
pkg/cond/parser.go
pkg/cond/parser_test.go

Allows things like:
```yaml
uses: fetch
if: ${{build.arch}} == 'x86_64'
with:
uri: some-x86-64-binary-here
...
```

add conditionals ("if" clauses)

---

pkg/renovate/bump/bump.go

fix issue with sourceforge redirects

---

pkg/build/build.go

Signed-off-by: Ariadne Conill <ariadne@dereferenced.org>

build: downgrade to anonymous storage client mode if an error is encountered

---

pkg/build/build.go

avoid marshalling new empty range field

---

pkg/container/docker_runner.go

Signed-off-by: Dan Luhring <dluhring@chainguard.dev>

Ping Docker to test usability

---

pkg/build/build.go

Signed-off-by: Dan Luhring <dluhring@chainguard.dev>

Advisories: Require pkg version for fixed status

---

pkg/index/index.go

This step seems to take awhile in CI (~5m+), so I figured it might make sense to parallelize. I did some testing locally and with my smaller package set on a Mac in docker (so no real comparisons at all), it improved by about 8s on average.
Without this the step takes 30s, with it somewhere around 22s.
Signed-off-by: Dan Lorenc <dlorenc@chainguard.dev>

Parallel processing of packages.

---

mac/README.md
mac/lima/melange-playground.yaml

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
/cc @kaniini @rawlingsj @dentrax

use lima to use melange on mac

---

go.mod
go.sum

bump apko dependency

---

README.md

I think this link should point to the melange instructions for Lima.

Update Lima link

---

README.md

Also use "apk" instead of APK.
Signed-off-by: Adrian Mouat <adrian@chainguard.dev>

Update README to mention wolfi.

---

pkg/build/build.go
pkg/sbom/bom.go
pkg/sbom/generator.go
pkg/sbom/implementation.go

Revert "Generate build environment SBOM"

---

pkg/build/pipelines/git-checkout.yaml

Fixes: #264 
Signed-off-by: Tuan Anh Tran <me@tuananh.org>

add expected-commit to git-checkout

---

pkg/build/build.go

for example:
```yaml
package:
name: ${{vars.package-name}}
version: ${{vars.package-version}}
...
vars:
package-name: example
package-version: 1.2.3
package-sha256: abcdef123456
...
pipeline:
- uses: fetch
with:
uri: https://example.com/${{package.name}}-${{package.version}}.tar.gz
expected-sha256: ${{vars.package-sha256}}
...
```

build: configuration: add support for variable substitution in more places

---

.github/workflows/verify.yaml
docs/main.go
docs/md/melange.md
docs/md/melange_build.md
docs/md/melange_bump.md
docs/md/melange_index.md
docs/md/melange_keygen.md
docs/md/melange_sign-index.md
docs/md/melange_update-cache.md
docs/md/melange_version.md

I dropped the timestamp in the metadata, I hope that's okay.

docs: ensure docs are up to date in CI

---

go.mod
go.sum
pkg/container/bubblewrap_runner.go
pkg/container/docker_runner.go

With these fixes, I am able to build the bootstrap package set of Wolfi using the Docker backend.  Tested on both Linux and Darwin hosts.

Bootstrap fixes

---

docs/UPDATE.md
pkg/build/build.go
pkg/build/build_test.go
pkg/build/testdata/update/github.melange.yaml
pkg/build/testdata/update/release-monitor.melange.yaml

add Update struct for identifying how a melange package can be updated

---

go.mod
go.sum
pkg/cond/parser.go

cond: parser: use newer fork of goparsify

---

pkg/build/build.go

build: check for signing key existence before using it

---

pkg/build/pipelines/fetch.yaml

pipelines: fetch: use wget quiet mode

---

.github/workflows/add-issues.yaml
.github/workflows/build.yaml
.github/workflows/e2e.yaml
.github/workflows/go-tests.yaml
.github/workflows/release.yaml
.github/workflows/sync-issues-to-project-board.yaml
.github/workflows/verify.yaml
.gitignore
.goreleaser.yaml
.ko.yaml
Makefile
go.mod
hack/sign-images.sh

rehearsal: https://github.com/cpanato/melange/releases/tag/v99.99.01
job: https://github.com/cpanato/melange/actions/runs/4561946298

Upgrade go to 1.20 and clean up ci

---

pkg/cli/commands.go

If this LGTY I'll make the same change in apko as well.

feat: send useragent in HTTP requests

---

go.mod
go.sum
internal/sign/sign.go
pkg/build/package.go
pkg/build/readlinkfs.go

The functionality has been removed from apko anyways.

use go-apk library instead of apko

---

go.mod
pkg/build/readlinkfs.go

This is needed for xattr support in Melange.

upgrade go-apk to latest commit, implement go-apk XattrFS interfaces

---

pkg/cond/parser.go
pkg/cond/parser_test.go
pkg/cond/subst.go
pkg/cond/subst_test.go

cond: allow underscores and capitalization in variable expressions

---

pkg/build/pipelines/fetch.yaml

pipeline: fetch: optionally delete fetched artifacts after unpacking

---

go.mod
go.sum
pkg/container/kubernetes_runner.go

- print kontext image size (which in my tests is normally at least 200MB 😬)
- print status details while pending -- I tried to keep it compact

some small UX improvements for k8s runner

---

go.mod
go.sum

Pulls in the fix from apko from [this PR](https://github.com/chainguard-dev/apko/pull/803)

pull in apko with fix for blank SOURCE_DATE_EPOCH

---

pkg/container/kubernetes_runner.go

Fixes https://github.com/chainguard-dev/melange/issues/520

Remove use of deprecated WaitImmediate

---

pkg/container/kubernetes_runner.go

- ensures the workspace environment variables are passed to the builder pod
- properly allow user defined `volumes` and `volumeMounts` to be set so that they don't override the melange provided ones

K8s runner template bugs

---

pkg/build/pipelines/patch.yaml

I believe this was typo'd here: https://github.com/chainguard-dev/melange/pull/554/files#r1266041214

Correct the variable name in the patch pipeline

---

pkg/container/kubernetes_runner.go

Log when we fail to publish the build image.
Set the termination grace period to zero so that build pods terminate immediately instead of after the 30s default.
Use `sleep infinity` instead of a loop around `sleep 5`

Several fixes to k8s runner.

---

pkg/build/package.go
pkg/build/sign.go
pkg/build/sign_test.go
pkg/cli/sign.go

follow up to #11 , this time retaining SDE

plumb through SDE to EmitSignature

---

pkg/build/package.go

pgzip's default is GOMAXPROCS(0)
This is fine for single builds, but we will starve CPU for larger builds. 8 is our max because modern laptops tend to have ~8 performance cores, and large CI machines tend to have ~64 cores.
This gives us near 100% utility on workstations, allows us to do ~8 concurrent builds on giant machines, and uses only 1 core on tiny machines.

Set reasonable concurrency levels for pgzip

---

pkg/build/readlinkfs.go

Certain security modules (such as Apple SIP and Google Container Threat Detection) use xattrs to store their state.  Ignore this state when generating packages.

readlinkfs: ignore some security-module specific xattrs

---

pkg/build/pipelines/python/build-wheel.yaml
pkg/build/pipelines/python/build.yaml
pkg/build/pipelines/python/install.yaml
pkg/convert/python/python.go
pkg/convert/python/python_test.go

Also use them in `melange convert python`, resolving a TODO.

add builtin pipelines for python

---

pkg/build/pipelines/python/install.yaml

remove extra backtick.

---

docs/md/melange_build.md
pkg/build/pipeline_test.go
pkg/cli/apkbuild.go
pkg/cli/build.go
pkg/cli/bump.go
pkg/cli/completion.go
pkg/cli/convert.go
pkg/cli/gem.go
pkg/cli/keygen.go
pkg/cli/python.go
pkg/cli/query.go
pkg/cli/sign.go
pkg/cli/update_cache.go
pkg/config/config.go
pkg/container/docker_runner.go
pkg/container/kubernetes_runner.go
pkg/container/lima_runner.go
pkg/convert/apkbuild/apkbuild.go
pkg/convert/apkbuild/apkbuild_test.go
pkg/convert/github/github.go
pkg/convert/python/pypi.go
pkg/convert/python/python.go
pkg/convert/python/python_test.go
pkg/convert/relmon/release_monitoring.go
pkg/convert/wolfios/wolfi-os.go
pkg/convert/wolfios/wolfi-os_test.go
pkg/renovate/bump/bump_test.go
pkg/renovate/cache/cache.go

I noticed we had tons and tons of lint warnings, which makes it hard to figure out when new lint errors have been introduced. So, start fixing them.

Bunch of lint fixes. No functional changes.

---

pkg/convert/python/python.go

Signed-off-by: Ville Aikas <vaikas@chainguard.dev>

Fix issue: #658

---

docs/md/melange_convert_python.md
pkg/cli/python.go

If we decide to do #648 
Fixes: #648

Change default python-version from 3.11 to 3.

---

pkg/build/pipelines/python/build-wheel.yaml
pkg/convert/python/python.go
pkg/convert/python/python_test.go

* python3 instead of python-3
* use build-wheel instead of build
* add py3-build and py3-installer to build-wheel

Fix some python generation issues:

---

docs/LINTER.md

Exactly as it says on the tin, just update the linter docs for the new `strip` linter.

Update linter docs

---

pkg/convert/python/python.go

nit: fix mistake in function docs

---

.goreleaser.yaml

- update deprecated fields
- fix release url path

Fix and update deprecated fields for goreleaser 

---

go.mod
go.sum
pkg/cli/sign.go
pkg/linter/linter.go

No functional changes (yet). This only adds a function to lint APK files.

Add function to lint APK files.

---

release.md

Document the release steps.

---

README.md

document full-version, add pointer to docs.

---

pkg/cli/lint.go

Notes:
This is a minor formatting fix to the linter's output. This makes it much more easy to read and interpret, especially when linting multiple APK's at once.

Improve linter diagnostic output

---

pkg/build/build.go
pkg/container/docker_runner.go
pkg/container/lima_runner.go

Fix permission issues resulting from running with the build user under Docker. and make the GID/UID remapping work to correct that.
Fixes #501 
Notes:
Notes:
Notes:
I have not tested this yet.

Fix ownership not being preserved

---

pkg/linter/linter_test.go

Fixes #777
No functional changes intended.

linter: refactor check block generation in tests

---

pkg/build/package.go

For packages containing Python modules, automatically add `python3~$VERSION` as a runtime dependency if a `python` dependency is not already specified.  This helps us to provide more specific version constraints for our Python module packages in Wolfi, which in turn makes Python upgrades less disruptive.

SCA: add python dependency generator

---

pkg/cli/lint.go
pkg/config/config.go
pkg/linter/defaults/defaults.go
pkg/linter/linter_test.go

There are currently no separate lints, but there will soon be. Prepare for this eventuality now.
No functional changes intended.

Separate out package and build lints

---

hack/make-devenv.sh

Script was not working because of the typo

Fix Typo in the `./hack/make-devenv.sh`

---

go.mod
go.sum

I believe this fixes a file leak I just introduced.

Bump go-apk

---

README.md
pkg/build/package.go
pkg/build/sign.go

This has been TODO for a while, and I don't know of any concrete plans to do it currently.

remove unimplemented references to fulcio support

---

go.mod
go.sum

Picks up https://github.com/chainguard-dev/go-apk/pull/155

update go-apk dependency

---

pkg/build/cache.go
pkg/build/package.go
pkg/build/runner.go
pkg/build/sca_interface.go
pkg/build/sign.go
pkg/build/sign_test.go

Fix lints, or ignore safe ones. No functional changes.

---

.github/workflows/verify.yaml
Makefile
pkg/config/schema.json

Adds makefile target + runs in CI/verify to check for diffs.

Ensure jsonschema is kept up to date.

---

pkg/build/pipelines/npm/install.yaml

Wolfi prefix is `/usr` by default

prefix should be /usr

---

release.md

- update release to add some clarification regarding the homebrew

update release to add some clarification regarding the homebrew

---

pkg/config/config.go
pkg/config/schema.json

json schema update to please linters.

Mark update.manual as an optional field.

---

.github/workflows/melange-test-pipelines.yaml
.github/workflows/wolfi-presubmit.yaml

- bump upload/download github actions
Closes: https://github.com/chainguard-dev/melange/pull/899 https://github.com/chainguard-dev/melange/pull/890

bump upload/download github actions

---

.github/workflows/melange-test-pipelines.yaml
e2e-tests/numpy-test.yaml
pkg/test/pipelines/python/import.yaml

Add python/import test pipeline, as well as e2e tests for python test pipelines.

---

pkg/build/test.go

If arch is not specified, test all.

---

pkg/build/pipeline.go

This allows you to use ctrl+C inside an interacive debugging session without forcing melange to abort once you exit the interactive session by ignoring Interrupt signals while inside Debug() and resetting the signal context prior to calling Run().

Mostly fix interactive interrupt signal handling

---

docs/UPDATE.md
docs/VAR-TRANSFORMS.md

This have more documentation 🎊 
- Add other case to `var-transform` (`${1}_`)
- Add `version-transform` to update section
cc @vaikas

version-transform and var-transform documentation

---

pkg/cli/sign.go

We were writing to a temp file and then immediately copying that file to a different file. This wastes time and space for no reason.

Don't write APK to temp file during signing

---

pkg/container/bubblewrap_runner.go

This flag breaks job control, which only matters during `--interactive` debugging.

Fix job control with interactive bubblewrap

---

pkg/build/pipelines/maven/pombump.yaml

Rename the default bump file name.

---

pkg/build/pipelines/pecl/install.yaml

Fix the bug in dropping the suffix.

---

.github/workflows/build.yaml
.github/workflows/e2e.yaml
.github/workflows/go-tests.yaml
.github/workflows/melange-test-pipelines.yaml
.github/workflows/release.yaml
.github/workflows/verify.yaml
.github/workflows/wolfi-presubmit.yaml

Adding Github Harden runner configs
Notes:
Notes:
Notes:

Add Harden Runner audit configs

---

.github/workflows/e2e.yaml

This runs the official SPDX validator on SBOMs built in our e2e tests, using the package we build in Wolfi.
https://github.com/spdx/tools-java
There's more to do after this, downstream of this, but this is a start.

verify SPDX SBOMs using spdx-tools-java

---

pkg/sca/sca.go

Temporary hack for https://github.com/chainguard-dev/melange/issues/1172

Drop -release from pc versions

---

go.mod
go.sum
pkg/build/build.go
pkg/config/config.go
pkg/config/schema.json
pkg/sbom/generator.go
pkg/sbom/implementation.go

- **copyright: allow custom license texts**
Allow specifying and including custom license texts in the package.
Related: https://github.com/chainguard-dev/melange/issues/1212
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@chainguard.dev>

custom license

---

docs/md/melange_test.md
pkg/build/test.go
pkg/build/test_options.go
pkg/cli/test.go

For consistency with melange build.

Add --env-file to melange test

---

pkg/build/pipelines/git-checkout.yaml

Quote issues when evaluating the depth condition

---

docs/md/melange.md
docs/md/melange_build.md
docs/md/melange_bump.md
docs/md/melange_completion.md
docs/md/melange_convert.md
docs/md/melange_convert_apkbuild.md
docs/md/melange_convert_gem.md
docs/md/melange_convert_python.md
docs/md/melange_index.md
docs/md/melange_keygen.md
docs/md/melange_lint.md
docs/md/melange_package-version.md
docs/md/melange_query.md
docs/md/melange_scan.md
docs/md/melange_sign-index.md
docs/md/melange_sign.md
docs/md/melange_test.md
docs/md/melange_update-cache.md
docs/md/melange_version.md
pkg/build/build.go
pkg/build/options.go
pkg/build/test.go
pkg/build/test_options.go
pkg/cli/build.go
pkg/cli/commands.go
pkg/cli/test.go

cc @imjasonh 
(will lint in time)

Remove ability to set logging policy 

---

.github/workflows/build.yaml
.github/workflows/release.yaml
.goreleaser.yaml
Makefile

https://goreleaser.com/deprecations/#-skip

stop using deprecated flags for goreleaser

---

pkg/config/config.go

This looks like it's been broken forever.

Fix missing commit in ranged subpackages

---

pkg/build/compile.go
pkg/build/compile_test.go

Also, add a test to prevent regression.

compile: Fix miscompilation of subpkg tests

---

main.go
pkg/cli/lint.go
pkg/linter/linter.go

Plumb ctx around the linters to make sure we gracefully handle sigint.

Restore signalcontext

---

docs/PIPELINES-GIT.md
e2e-tests/git-checkout-build.yaml
e2e-tests/test-fixtures/create-git-repo
pkg/build/pipelines/git-checkout.yaml

Add git-cherry-pick pipeline

---

pkg/build/pipeline.go

My initial implementation of this was very naive and just used single-quote strings for history, which is almost certainly wrong most of the time.
This just writes the file to the workspace directory, which is less error prone.

debug: Populate history file via mounts

---

pkg/build/pipelines/autoconf/make-install.yaml

This makes it consistent with `make`.
https://github.com/wolfi-dev/os/pull/22762#pullrequestreview-2145700069

Add opts to make-install pipeline

---

pkg/build/compile.go

We have had a lot of silently ignored inputs for a while, this makes those loudly fail instead.
Make sure we merge https://github.com/wolfi-dev/os/pull/22762 before this lands.

Fail on invalid pipeline inputs

---

pkg/build/pipeline.go

I introduced this in:
https://github.com/chainguard-dev/melange/pull/1280

Fix ${{host.triplet.rust}} default value

---

.github/dependabot.yml
.github/workflows/verify.yaml
go.mod

- Updates for go/dependabot/golangci-lint

Updates for go/dependabot/golangci-lint

---

pkg/cli/keygen.go

to be used by calling from a program

expose keygen options

---

pkg/sca/sca.go

Generates a dependency on the version of Ruby used to build gems when missing
Notes: Built several Ruby packages that do not explicitly declare ruby as a runtime dependency and with it declared to validate intended functionality

feat(sca): Generate dependency on Ruby when building gems

---

.github/workflows/wolfi-presubmit.yaml

From the CI logs:
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Attempt to fix qemu ci

---

pkg/sca/sca.go

Returning early is nice to avoid doing extra work, but it confuses the control flow and makes it too easy to miss places where we should be skipping certain provides. This centralizes where we check for no-provides, no-commands, and no-depends so that we can't do this accidentally again.

Centralize sca options handling

---

pkg/config/config.go
pkg/config/config_test.go

Replace "needs" in range pipelines

---

docs/cmd/pipeline-reference-gen/main.go
docs/cmd/pipeline-reference-gen/template.md.tmpl
go.mod
go.sum
pkg/build/pipelines/R/README.md
pkg/build/pipelines/README.md
pkg/build/pipelines/autoconf/README.md
pkg/build/pipelines/cargo/README.md
pkg/build/pipelines/cmake/README.md
pkg/build/pipelines/docs.go
pkg/build/pipelines/go/README.md
pkg/build/pipelines/goreleaser/README.md
pkg/build/pipelines/maven/README.md
pkg/build/pipelines/meson/README.md
pkg/build/pipelines/npm/README.md
pkg/build/pipelines/pecl/README.md
pkg/build/pipelines/perl/README.md
pkg/build/pipelines/python/README.md
pkg/build/pipelines/ruby/README.md
pkg/build/pipelines/split/README.md

Generates markdown documentation for pipeline files.
Documentation is group per-folder.

Add pipeline markdown reference markdown generator.

---

pkg/config/config.go
pkg/config/config_test.go

This enables packages in the build environment for subpackages to be based on range values.

Support string replacement in ImageContents

---

docs/BUILD-FILE.md

Notes: It's just documentation, it should not cause any build failures.
Notes: Shouldn't be applicable. 
Notes: There is no new check.

Added additional documentation for package version selection

---

pkg/cli/test.go

This error message is a bit misleading.

test: Fix typo

---

pkg/sca/e2e_test.go
pkg/sca/sca.go

These changes surface worse problems.

sca: revert melange changes for naked sca

---

go.mod
go.sum

This one: https://github.com/chainguard-dev/apko/pull/1360

bump apko to pick up chainguard key fix

---

pkg/container/qemu_runner.go

We are seeing issues with large >2G initrd files with QEMU immediately rejecting them as invalid.
It doesn't seem like anything is wrong with the initrd itself because compressing it makes things work, so the current working theory is that there is some signed 32-bit ceiling we aren't seeing documented.
I thought about making this conditional on whether the layer was above a certain size, but the only `Size()` accessor on the layer is the compressed size and so to get a realistic picture of the uncompressed size of the initrd we'd have to uncompress and read through it.  Given that our initial motivation for using things uncompressed was to avoid the extra decompression it felt most pragmatic to just unconditionally compress things.

Compress the initrd to workaround issue

---

pkg/build/build.go
pkg/build/test.go
pkg/cli/build.go
pkg/cli/compile.go
pkg/cli/test.go
pkg/container/docker/docker_runner.go
pkg/container/qemu_runner.go
pkg/convert/apkbuild/apkbuild.go

Improve error and be less spammy

move unnecessary logs from info to debug or error

---

pkg/config/config.go

If a pipeline didn't have a name, we would just call it "" in a warning, which wasn't super helpful, instead we'll default name -> uses -> index if the previous option doesn't exist.
This also gives more context on which pipeline failed to validate when dealing with recursive pipelines.

Give better names for invalid pipelines errors

---

pkg/build/pipelines/cmake/configure.yaml

It helps to have more verbose builds when investigating something.

Improve cmake build verbosity

---

go.mod
pkg/container/qemu_runner.go

Improve the debug shell in qemu runners
This properly instantiates a terminal, with hotkeys and resizes

fix(qemu): improve debug shell to instantiate a proper terminal

---

.github/workflows/verify.yaml
Makefile

Upgrade golangci-lint in the action, and makefile.
Also fix action version comment to the correct one.
References:
- https://github.com/dependabot/dependabot-core/issues/7912

Upgrade golangci-lint to 1.64.8

---

pkg/container/qemu_runner.go

The two changes here are:
1. use a virtconsole (virtio) for the serial device on both arm64 and amd64.  And use console=hvc0 for this rather than passing both arch-specific console= values.
2. turn on isa-serial in microvm so that stdout can get through (-serial is a isa-serial device).
In my testing with qemu-10.0.0 in wolfi, it is still broken but at least you get serial output.

Use virtconsole for stdout, and serial in microvm.

---

.github/workflows/wolfi-presubmit.yaml
pkg/build/build.go

There is only a single package in Wolfi that exhibits this.

Drop the `isBuildLess` optimization.

---

pkg/container/qemu_runner.go

This also improves the logging on this key command, which is painful to debug.

Fix test user permissions for `logstash-8`

---

examples/split-bin.yaml
pkg/build/pipelines/split/README.md
pkg/build/pipelines/split/bin.yaml

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

Add split/bin pipeline

---

docs/md/melange_build.md
docs/md/melange_lint.md
pkg/linter/linter.go
pkg/linter/linter_test.go

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

Add a linter for CUDA driver-specific libraries

---

e2e-tests/xcover-nopkg-test.yaml
examples/test-xcover.yaml
pkg/build/pipelines/xcover/README.md
pkg/build/pipelines/xcover/ensure.yaml
pkg/build/pipelines/xcover/profile.yaml
pkg/build/pipelines/xcover/status.yaml
pkg/build/pipelines/xcover/stop.yaml
pkg/build/pipelines/xcover/wait.yaml

feat(pkg/build/pipelines): add xcover pipelines
